#!/usr/bin/env python3
"""Generate DEFECT_REGISTER.json/.md and PROVISIONAL_FINDING_ADJUDICATION.json for RES-80.

Single source of truth for the audit defect register. Read-only w.r.t. science:
writes only the audit artifacts under the repo audit directory.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent

def D(id, title, severity, types, status, files, loc, declared, implemented, proof,
      numeric, effect, cause, r001, claim, authority, deps, fix, test, requal, evidence, preflight=None):
    return {
        "ID": id, "TITLE": title, "SEVERITY": severity, "TYPE": types, "STATUS": status,
        "FILE": files, "LINE_OR_FUNCTION": loc, "DECLARED_BEHAVIOR": declared,
        "IMPLEMENTED_BEHAVIOR": implemented, "REPRODUCTION_OR_PROOF": proof,
        "NUMERIC_EVIDENCE": numeric, "OBSERVED_EFFECT": effect, "ROOT_CAUSE": cause,
        "R001_IMPACT": r001, "SCIENTIFIC_CLAIM_IMPACT": claim,
        "AUTHORITY_INVALIDATED_OR_LIMITED": authority, "DEPENDENCIES": deps,
        "FIX_CLASS": fix, "REQUIRED_REGRESSION_TEST": test,
        "REQUALIFICATION_SCOPE": requal, "EVIDENCE_POINTERS": evidence,
        "PREFLIGHT_REFERENCES": preflight or [],
    }

DEFECTS = [
# ============================== CRITICAL ==============================
D("CRIT-001", "Knee hinge direction is anatomically inverted; human knee flexion is outside the joint range",
  "CRITICAL", ["MODEL_FORM_DEFECT", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/assets/v2_plant.xml", "src/loaded_cmj/v2/constants.py"],
  ["v2_plant.xml:97 (left_knee axis 0 -1 0, range 0 2.40)", "v2_plant.xml:125 (right_knee)", "constants.py:138-139"],
  "XML/constants comment: knee '0 extended, flexion positive'; range [0, 2.40]",
  "Positive knee q rotates the shank so the ankle moves anteriorly (+x) and up relative to the knee; negative q (human flexion direction, heel toward buttocks) is outside [0, 2.40].",
  "Deterministic forward-kinematics probe on the frozen XML (probes/probe_geometry.py, PROBE A1): knee q=0.4/0.8/1.2 gives ankle_x-knee_x=+0.167/+0.309/+0.401 m. Accepted trajectory: knee q peaks at +1.269 rad at t=0.4875 s; at E3 the ankle is +0.181 m anterior of the knee and the knee is 29 cm posterior to the ankle-plane.",
  {"knee_q": [0.0, 0.4, 0.8, 1.2], "ankle_minus_knee_x_m": [0.0, 0.1674, 0.3085, 0.4008],
   "R001_knee_max_rad": 1.2690245, "R001_knee_at_E6_rad": 0.5413, "R001_ankle_minus_knee_x_at_E3_m": 0.181},
  "The accepted countermovement/landing is performed with a reverse-bending knee (knee apex posterior); the model cannot represent a human knee-flexed pose.",
  "Hinge axis sign (0 -1 0) plus positive-only range; XML/constants naming asserts the opposite convention.",
  "Entire accepted R001 squat/extension/landing is reverse-knee; the owner-observed knee/leg flick and back/forward leg motion are direct consequences.",
  "Biomechanical claim 'loaded countermovement jump' is invalid at the kinematic level; no human technique interpretation is possible.",
  ["Plant XML", "Plant hash (content changes under any fix)", "all trajectory-dependent evidence"],
  ["CRIT-002", "HIGH-019", "MED-007"],
  "MODEL_FORM_CHANGE (flip knee axis/range and re-derive controller knee signs) + full requalification",
  "FK sign test: positive knee q must move the ankle posteriorly (-x) relative to the knee; R001-class run must show human knee flexion during countermovement.",
  "Plant, controller, events/scorer, measurements, full V2.1 requalification; historical R001 remains reproducible-only.",
  ["audit/.../probes/probe_geometry.py", "audit/.../probes/probe_skeleton.py", "DEFECT_REGISTER.md#CRIT-001"],
  ["P13-adjacent"]),

D("CRIT-002", "Hip range/convention allocates 1.80 rad to extension and only 0.50 rad to flexion; countermovement is driven into hip extension",
  "CRITICAL", ["MODEL_FORM_DEFECT", "CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/assets/v2_plant.xml", "src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/res72_integration.py"],
  ["v2_plant.xml:88 (axis 0 1 0, range -0.50 1.80)", "constants.py:136-137", "res72_integration.py:59-60 (FLEX_TAU/EXTEND_TAU positive hip)"],
  "Hip flexion positive (human squat requires ~0.8-1.5 rad hip flexion)",
  "Positive hip q rotates the thigh posteriorly (extension); the range excludes human deep hip flexion beyond 0.50 rad. FLEX_TAU=+20 Nm drives extension during the countermovement (q rises +0.135 -> +0.587 rad).",
  "FK probe (probe_geometry.py) plus accepted qpos trace; at deepest crouch the thigh is rotated posteriorly with the knee behind the pelvis.",
  {"R001_hip_max_rad": 0.5874, "hip_at_E4_rad": 0.376, "hip_at_E6_rad": -0.3181, "range_rad": [-0.50, 1.80]},
  "The body sinks by extending the hip rather than flexing it, forcing a non-anatomical leg 'Z' and contributing to the backward body motion.",
  "Joint axis sign + range allocation inverted relative to human hip flexion; controller 'FLEX' program uses positive hip torque.",
  "Countermovement posture is anatomically invalid; contributes to reverse-knee geometry and to the takeoff lurch.",
  "Loaded-CMJ biomechanics claim invalid; hip flexion range is a task-critical requirement.",
  ["Plant XML", "controller FLEX/EXTEND programs", "countermovement metrics"],
  ["CRIT-001", "HIGH-019"],
  "MODEL_FORM_CHANGE (hip range/sign) + controller sign re-derivation + requalification",
  "Hip flexion >= 1.0 rad reachable during countermovement with human femoral direction; postural signature test.",
  "Plant/controller/events; full V2.1 requalification.",
  ["audit/.../probes/probe_geometry.py", "traj_summary.json"],
  []),

D("CRIT-003", "No meaningful jump-performance requirement exists; a 3.6 cm hop qualifies as task success",
  "CRITICAL", ["SCORER_SPEC_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/events.py", "src/loaded_cmj/v2/canonical_runtime.py"],
  ["constants.py:181-209 (V2_EVENT_THRESHOLDS)", "events.py:193-202 (only TAKEOFF_VZ_MIN checked at E6 onset)", "events.py:1076-1079 (apex metrics computed)", "canonical_runtime.py:540-590 (output omits them)"],
  "Task acceptance criteria include a genuine loaded CMJ; TAKEOFF_VZ_MIN=0.60, PREFERRED=0.80",
  "No minimum jump height, no minimum flight time, no minimum foot clearance, no minimum COM rise/apex gate. GENUINE_FLIGHT_GAP_M=0.010, APEX_DWELL_S=0.005 and TAKEOFF_VZ_PREFERRED_MPS=0.80 are declared but never referenced by executable code.",
  "Source grep (unused constants) + accepted-run quantification: apex COM z 1.11118 m vs standing 1.07485 m = 0.0363 m net jump height; takeoff-to-apex rise 0.0768 m; flight 0.2268 s; max foot clearance 0.0496 m.",
  {"net_jump_height_above_standing_m": 0.03627, "com_rise_from_takeoff_m": 0.07684,
   "flight_duration_s": 0.22675, "max_foot_clearance_m": 0.049606,
   "takeoff_vz_mps": 1.2274, "TAKEOFF_VZ_MIN_MPS": 0.60},
  "The qualification logic cannot distinguish a small hop from a functional loaded CMJ; the owner's 'extremely little visible flight' is compatible with a PASS.",
  "Task contract lacks performance gates; only event-completion gates exist.",
  "R001 PASS is compatible with a 3.6 cm hop; SHIP_STATUS blocked mainly on visual review, not on any quantitative floor.",
  "Any 'successful loaded countermovement jump' claim is unsupported; 'computational event-chain PASS' is the maximum valid claim.",
  ["events.py (SCORER_SHA256)", "constants.py (unhashed)", "qualification criteria"],
  ["HIGH-010", "HIGH-011", "HIGH-013", "MED-011"],
  "SPEC/QUALIFICATION_CHANGE (add owner-approved performance gates) - REQUIRES_OWNER/SCIENTIFIC_CONTRACT_DECISION for values",
  "Negative-control trajectory that completes 12/12 events with an objectively trivial hop must FAIL the task gate.",
  "Scorer spec + qualification scope; no plant change required for the gate itself.",
  ["traj_summary.json", "DEFECT_REGISTER.md#CRIT-003"],
  ["P01", "P02", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"]),

D("CRIT-004", "Candidate identity does not freeze the executing system",
  "CRITICAL", ["PROVENANCE_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["CANONICAL_V2_CANDIDATE_SPEC.json", "CANONICAL_CANDIDATE_IDENTITY.json", "src/loaded_cmj/v2/canonical_runtime.py", "tests/test_res78_canonical_runtime.py"],
  ["CANONICAL_V2_CANDIDATE_SPEC.json (CONTROLLER_COMPOSITION_SHA256 over 5 files)", "test_res78_canonical_runtime.py:75-79", "canonical_runtime.py:50-55 (imports)"],
  "CONTROLLER_COMPOSITION_SHA256 is the frozen controller identity",
  "The hash covers res72_integration, balance_capture, stable_recovery, terminal_capture, full_closure. full_closure is imported only by tests (dead on the canonical path); the executed orchestration lives in unhashed canonical_runtime.py, plus unhashed constants.py, plant.py, measurement.py, drive.py, support_continuity.py and tools/{core52, soft_contact, evid_trace_v2}.py. No runtime recomputation of any hash exists.",
  "Hash recomputation (composition hash verified correct over the 5 files), import-graph grep, wheel inspection; canonical_runtime only checks the --candidate string.",
  {"hashed_files": 5, "executed_but_unhashed_modules": 9, "hash_bearing_file_dead_on_canonical_path": "full_closure.py",
   "runtime_hash_checks": 0},
  "Two different working trees can both emit a result labeled V2.1-R001 with the declared hashes intact.",
  "Hash domain chosen as a five-file concatenation rather than the executable closure; orchestrator/authorities excluded.",
  "R001's own reproducibility is real (same tree), but 'frozen candidate' provenance is not enforceable.",
  "'Frozen V2.1-R001' identity claim is invalid; candidate identity is a partial fingerprint only.",
  ["CONTROLLER_COMPOSITION_SHA256", "CANDIDATE_SPEC_SHA256", "RUNTIME_CONTRACT_SHA256", "CONTROLLER_FILES map"],
  ["CRIT-005", "MED-015", "MED-016", "HIGH-007"],
  "PROVENANCE_CHANGE (expand hash domain to full executable closure and verify at runtime)",
  "Clean-clone test: mutate any executed-but-unhashed module -> identity verifier must FAIL before execution.",
  "Successor candidate identity definition; R001 historical hash remains valid as a partial fingerprint.",
  ["PROVENANCE_REVIEW.md", "DEFECT_REGISTER.md#CRIT-004"],
  []),

D("CRIT-005", "Five external evidence JSON authorities are loaded at runtime without hash verification",
  "CRITICAL", ["PROVENANCE_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py"],
  ["canonical_runtime.py:74-85 (_load_authorities)", "canonical_runtime.py:104-106, 250, 355"],
  "Frozen authorities RR spec, recovery manifold, handoff spec, T_RISE, terminal controller constants",
  "Runtime json.loads() of /home/litju/.../EXP-RES10-*/{recovery_ready_spec.json, RECOVERY_MANIFOLD_AUTHORITY.json, stand_handoff_ready_spec.json, RECOVERY_TIME_SCALING_AUTHORITY.json, experiment_spec.json} with no sha256/SPEC_SHA256 check and no fallback.",
  "Source inspection; no hash call on this path; support_continuity.load_spec() (which verifies a spec hash) is never called by the runtime.",
  {"authority_files_loaded_unverified": 5, "paths_absolute": True, "hash_checks": 0},
  "Mutating non-Git evidence can change the RR dwell/thresholds, the 13-node recovery manifold, handoff gates/T_RISE and terminal BVLS constants while the candidate identity is unchanged.",
  "External authorities are consumed as trusted inputs outside the hash domain.",
  "R001 evidence was produced from one evidence state; the provenance of that state is not cryptographically bound to the candidate.",
  "Reproducibility claim depends on external mutable files; 'same candidate' cannot be assumed across evidence mutations.",
  ["RR spec", "RECOVERY_MANIFOLD_AUTHORITY", "stand_handoff_ready_spec", "RECOVERY_TIME_SCALING_AUTHORITY", "RES-52 experiment_spec"],
  ["CRIT-004", "CRIT-006"],
  "PROVENANCE_CHANGE (vendor authorities into repo or pin hashes in identity and verify at load)",
  "Hash-mutation negative test: alter one authority byte -> run must fail closed before any controller construction.",
  "Successor qualification; historical evidence remains valid as reproduced.",
  ["PROVENANCE_REVIEW.md", "DEFECT_REGISTER.md#CRIT-005"],
  ["P25"]),

D("CRIT-006", "Production package is not self-contained and cannot run from a clean install",
  "CRITICAL", ["PROVENANCE_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["pyproject.toml", "uv.lock", "src/loaded_cmj/v2/canonical_runtime.py", "tools/res52/soft_contact.py"],
  ["pyproject.toml:6-9 (deps), :18-19 (packages)", "uv.lock (no scipy)", "canonical_runtime.py:53-55 (imports core52/soft_contact/evid_trace_v2)", "balance_capture.py:26 / stable_recovery.py:34 / soft_contact.py:35 (scipy)"],
  "Declared runtime environment: mujoco 3.8.0, numpy 2.5.1, scipy 1.18.1; canonical command `python -m loaded_cmj.v2.canonical_runtime --candidate V2.1-R001`",
  "Wheel contains only src/loaded_cmj; tools/ modules are absent; scipy is not declared and not present in uv.lock; all controller JSON authorities use absolute developer paths.",
  "Built wheel with `uv build --wheel` (audit/.../probes runs in /tmp): 64 entries, tools/ absent, v2_plant.xml present, no scipy dependency metadata. `import core52`, `from soft_contact import SoftContactPolicy`, `from tools.evid_trace_v2 import ...` follow immediately from canonical_runtime imports.",
  {"wheel_entries": 64, "tools_in_wheel": False, "scipy_in_metadata": False, "scipy_in_uv_lock": False},
  "No clean environment can execute the canonical candidate; deployment reproducibility fails.",
  "Packaging boundary excludes the modules that implement the executed controller; dependency declaration incomplete.",
  "R001 was reproduced only in the developer tree with a manually provisioned scipy and the external evidence tree.",
  "Deployment/reproducibility claims invalid outside the author's machine.",
  ["pyproject.toml", "uv.lock", "wheel contents", "CANONICAL_COMMAND"],
  ["CRIT-004", "CRIT-005", "MED-016"],
  "PACKAGING_CHANGE (include tools or move modules into package; declare scipy; remove absolute paths)",
  "Clean-venv install test: install wheel + declared deps, run canonical runtime against a vendored evidence fixture.",
  "Successor release qualification.",
  ["PROVENANCE_REVIEW.md", "wheel listing captured in AUDIT_COMMAND_LOG.txt"],
  ["P32", "P33"]),

D("CRIT-007", "Premature SUPPORTED->FLIGHT switch (single-sample guard) commands a ~0.94 action step while feet are still loaded; violent non-human takeoff",
  "CRITICAL", ["CONTROL_BUG", "MODEL_FORM_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/res72_integration.py"],
  ["res72_integration.py:156-159 (maxf<10 single sample, no dwell/direction)", "res72_integration.py:201-203 (zero-pose FLIGHT PD)"],
  "Flight starts at bilateral physical support loss with a bounded/continuous action",
  "Phase 1->2 fires on one control sample with maxf<10; the flight law commands a stiff PD to zero pose (KP 80/KD 12), causing a 0.944 (hip/knee ~236/270 Nm) step in one 5 ms interval at t=0.640, 6.75 ms before true bilateral support loss (0.64675) / 8.125 ms before sealed E6 (0.648125).",
  "Sealed action schedule analysis (probe_skeleton.py) + true support reconstruction from ctrl-aware contact forces (probe_forces2.py) + pelvis pitch-rate trace.",
  {"switch_t_s": 0.640, "true_support_loss_t_s": 0.648125, "E6_occ_s": 0.648125,
   "max_du": 0.9439, "u_before": [-0.01,-0.323,-0.323,-0.543,-0.543,-0.1,-0.1],
   "u_after": [0.179,0.621,0.621,0.358,0.358,0.100,0.100],
   "pelvis_pitch_rate_min_radps": -9.6837, "pelvis_pitch_rate_min_t_s": 0.649875},
  "The body is whipped backward at ~9.7 rad/s at takeoff; whole-body backward motion and a violent transition are direct consequences; takeoff occurs before physical separation.",
  "Guard lacks dwell/hysteresis and vz direction; flight reference is zero pose with no ballistic/COM authority; free root pitch is unregulated.",
  "R001 takeoff is control-induced rather than physics-caused; contributes to the low jump and the owner's takeoff observations.",
  "Takeoff mechanics claim invalid; E6 is latched after the fact and does not certify a physical takeoff timing.",
  ["res72_integration.py (CONTROLLER_COMPOSITION_SHA256)", "E6 semantics", "controller phase guards"],
  ["HIGH-005", "HIGH-006", "HIGH-002", "MED-008"],
  "CONTROL_CHANGE (dwell/direction gate; state-based extension completion; flight authority)",
  "Adversarial guard test: single noisy control sample of maxf<10 must not switch to FLIGHT; takeoff action step must be bounded and occur at/after support loss.",
  "Controller + events requalification; successor candidate.",
  ["probe_skeleton.py output", "probe_forces2.py output", "DEFECT_REGISTER.md#CRIT-007"],
  ["P04", "P05", "P20-adjacent"]),

# ============================== HIGH ==============================
D("HIGH-001", "E10 impact-absorption predicate is underconstrained (vertical-only, no horizontal/angular/posture)",
  "HIGH", ["SCORER_SPEC_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/events.py", "src/loaded_cmj/v2/canonical_runtime.py"],
  ["events.py:241-245 (_guard_impact_absorption)", "canonical_runtime.py:338 (E10 streak predicate)"],
  "Impact absorption means vertical momentum is absorbed with a stable posture",
  "Guard is only abs(com_vz)<0.05, plus bilateral Fz>10 N and no fall/prohib at the runtime switch. Horizontal velocity, angular momentum, trunk posture and CoP are unconstrained.",
  "Source inspection + R001 trace: during impact Hy rises from 3.33 to 9.88 kg m2/s while com_vx rises 0.181->0.211 m/s; E10 latches regardless.",
  {"Hy_at_E9_occ_kgm2ps": 3.333, "Hy_at_E10_occ_kgm2ps": 9.880, "com_vx_at_E9_mps": 0.1814,
   "com_vx_at_E10_occ_mps": 0.2115},
  "The system declares absorption while forward rotational momentum is growing; the subsequent forward lunge is uncertified.",
  "Predicate omits horizontal/angular/posture state; canonical runtime mirrors the same vertical-only condition.",
  "E10 timing in R001 is driven by a transient |vz|<0.05 window; the lunge occurs during/after it.",
  "'Impact absorption PASS' does not imply absorbed landing; claim is limited to vertical-speed capture.",
  ["events.py (SCORER_SHA256)", "E10 definition", "landing qualification"],
  ["HIGH-002", "HIGH-003", "HIGH-004", "CRIT-003"],
  "SCORER_SPEC_CHANGE + CONTROL_CHANGE (add horizontal/angular/postural criteria)",
  "Negative control: a landing with large inherited vx/Hy must not latch E10.",
  "Events + landing qualification; successor candidate.",
  ["traj_summary.json", "probe_landing.py output"],
  ["P08"]),

D("HIGH-002", "RES-58 terminal capture regulates only vertical momentum; it has no horizontal/angular/CoP authority",
  "HIGH", ["CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/terminal_capture.py", "tools/res52/soft_contact.py"],
  ["terminal_capture.py:79-97 (capture_force_command/vz target)", "soft_contact.py:219-237 (no Fx/Hy/CoP rows)"],
  "Terminal capture arrests the fall and stabilizes the body",
  "FZ_DES = clamp(BW - m*vz/DT, 0.6BW, 1.5BW); the inner LS has Fz/FzL/FzR, dist, nvel, vz, qdot rows only. No Fx, Hy/Hdot, CoP, or absolute posture is commanded.",
  "Source inspection; accepted-run Hy peak 9.88 kg m2/s and com_vx 0.28-0.34 m/s at/after E10.",
  {"Hy_peak_after_impact_kgm2ps": 9.880, "com_vx_peak_after_impact_mps": 0.3418},
  "The landing's forward pitch/translation cannot be caught by the terminal layer; the-9.7 rad/s takeoff pitch and impact Hy are structurally outside its authority.",
  "Vertical-only outer law derived from a fall-arrest objective.",
  "R001 reaches BALANCE with substantial forward momentum that the terminal layer never addressed.",
  "Terminal-capture claim is limited to vertical arrest.",
  ["terminal_capture.py (CONTROLLER_COMPOSITION_SHA256)", "RES-58 authority", "E10->BALANCE handoff"],
  ["HIGH-003", "HIGH-004", "HIGH-009"],
  "CONTROL_CHANGE (add horizontal/CAM/CoP authority or a dedicated landing strategy)",
  "Landing with a lateral/forward perturbation must keep CoM/CAM bounded through capture.",
  "Controller + landing requalification.",
  ["probe_landing.py output"],
  ["P14"]),

D("HIGH-003", "Balance controller authority is braking-only and cannot command forward CoP/Fx; forward lunge is uncorrectable in principle",
  "HIGH", ["CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/balance_capture.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["balance_capture.py:33-34 (FX_BRAKE_MIN=-120, FX_BRAKE_MAX=0; HDOT_MIN=-60, HDOT_MAX=0)", "balance_capture.py:143 (CoP clamp)"],
  "Centroidal balance with feasible CoP projection",
  "Fx demand is clamped to [-120, 0] and Hy reduction to [-60, 0]; only backward braking/reduction is representable. Accepted R001 needs forward acceleration of the CoM (from -0.058 at t=2.117; but the forward lunge requires +Fx earlier) and the controller cannot ask for it.",
  "Source + accepted trace: com_vx accelerates 0.181 -> 0.342 m/s after touchdown while the controller can only brake; forward CoM reversal occurs at t=2.117 s.",
  {"FX_range": [-120.0, 0.0], "HDOT_range": [-60.0, 0.0], "com_vx_peak_after_touchdown_mps": 0.3418,
   "com_vx_at_RR_conf_mps": 0.0729},
  "The owner-observed forward lunge/bounce is not preventable by the balance layer's authority set.",
  "One-sided authority deliberately frozen (braking only).",
  "R001's balance/capture phase is a waiting game until momentum decays; posture degrades (trunk pitch to 25 deg) meanwhile.",
  "'Balance capture' claim is weaker than named; only backward braking is implemented.",
  ["balance_capture.py (CONTROLLER_COMPOSITION_SHA256)", "RES-73 authority", "E11 definition"],
  ["HIGH-001", "HIGH-002", "HIGH-004", "MED-009"],
  "CONTROL_CHANGE (two-sided feasible CoP/Fx authority within support)",
  "Perturbation test requiring both forward and backward CoP authority; posture bound during capture.",
  "Balance/landing requalification.",
  ["probe_landing.py", "DEFECT_REGISTER.md#HIGH-003"],
  ["P23"]),

D("HIGH-004", "RECOVERY_READY predicate constrains rates only; recovery begins from a 24-degree forward lean with 0.65 rad knee and 15 cm forward CoM",
  "HIGH", ["CONTROL_BUG", "SCORER_SPEC_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/full_closure.py", "src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["full_closure.py:62-75 (rr_predicate_ok)", "canonical_runtime.py:352-361 (inline RR)", "stable_recovery.py:612-634 (_handoff_ready)"],
  "Recovery-ready means the athlete can begin standing recovery",
  "RR conditions: |vx|<=0.15, |vz|<=0.05, |Hy|<=1.5, |root pitch rate|<=0.5, |trunk rate|<=1.0, qdot<=1.0, margin>=0.05, Fz>10, pen<=0.01. No absolute trunk pitch, joint configuration, COM-x relative to feet, or CoP-position constraint.",
  "Source + accepted trace at RR entry/confirmation: root pitch 0.4226/0.4315 rad, knee 0.6476/0.6529, COM x +0.149/+0.160 m.",
  {"root_pitch_at_RR_entry_rad": 0.4226, "knee_at_RR_entry_rad": 0.6476,
   "com_x_at_RR_entry_m": 0.1493, "com_x_at_RR_conf_m": 0.1604, "recovery_span_s": 13.15},
  "The 13.15 s RISE/SETTLE recovery starts from a poorly postured state; the long recovery is a symptom, not a designed behavior.",
  "Predicate built only from rate/velocity envelopes.",
  "RR entry is much later than E11 (E11 occ 0.9935, RR entry 1.237) because velocity decays; posture is never corrected before RISE.",
  "'Stable recovery' certificate begins only after 13 s and does not encode posture quality at entry.",
  ["full_closure.py (in composition hash but dead)", "RR spec external JSON", "E11/E12 semantics"],
  ["HIGH-003", "CRIT-005", "MED-013"],
  "SCORER_SPEC_CHANGE + CONTROL_CHANGE (add absolute posture/CoP envelope to RR)",
  "Posture-at-entry test: recovery may only start inside a declared standing-approach posture set.",
  "Balance/recovery requalification.",
  ["probe_landing.py", "DEFECT_REGISTER.md#HIGH-004"],
  ["P16"]),

D("HIGH-005", "BALANCE->RECOVERY resets the held action to zeros, discarding up to 0.545 and breaking the previous-action continuity nominal",
  "HIGH", ["CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["canonical_runtime.py:253 (held = zeros)", "stable_recovery.py:127 (u_prev=zeros)"],
  "Action-history continuity nominal: each control layer starts from the previously applied action",
  "At the BALANCE->RECOVERY switch the runtime sets held=zeros; the recovery controller initializes u_prev=zeros; the first recovery action is bounded relative to a false origin.",
  "Sealed control schedule: |du|=0.5449 at t=1.337 from the last balance action to the first recovery action.",
  {"max_du_at_switch": 0.5449, "switch_t_s": 1.337},
  "A 0.545 controller step occurs exactly at the transition, in addition to the law change.",
  "Explicit action-history reset at regime switch.",
  "R001 recovery entry contains an unnecessary action discontinuity.",
  "Continuity claim in the controller documentation is violated at this switch.",
  ["canonical_runtime.py (unhashed)", "StableRecoveryController", "soft-contact PREVIOUS_APPLIED_ACTION nominal"],
  ["CRIT-007", "HIGH-006"],
  "CONTROL_CHANGE (carry held action across the switch)",
  "Continuity test: sup |u_k - u_{k-1}| bounded by the trust region across every regime switch.",
  "Controller requalification.",
  ["probe_skeleton.py output"],
  ["P19"]),

D("HIGH-006", "Direct torque at 200 Hz with no activation dynamics or action-rate limiting produces non-physiological command steps",
  "HIGH", ["MODEL_FORM_DEFECT", "CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/drive.py", "src/loaded_cmj/v2/res72_integration.py"],
  ["drive.py:25-36 (tau = limit*u)", "res72_integration.py:191-210 (discrete program switches)"],
  "Credible model of human loaded-CMJ actuation",
  "Each 5 ms control interval applies a directly commanded bounded torque; there is no activation state, no action slew, and phase programs switch in one interval. Observed steps: 0.568 (t=0.400), 0.944 (t=0.640), 0.545 (t=1.337).",
  "Sealed action schedule (probe_skeleton.py).",
  {"action_steps": [{"t": 0.400, "du": 0.568}, {"t": 0.640, "du": 0.944}, {"t": 1.337, "du": 0.545}],
   "control_rate_hz": 200.0},
  "Muscle-like force rise times (tens of ms) are absent; takeoff extension and landing absorption are impulse-like command changes.",
  "Direct-torque actuator model chosen for transparency; no activation/slew layer.",
  "R001 takeoff shock and the sense of a mechanical/non-human transition are partially attributable to this abstraction.",
  "Any claim of human-like loaded-CMJ actuation is unsupported; this is a declared model simplification with material trajectory effect.",
  ["drive.py", "controller programs", "R001 action schedule"],
  ["CRIT-007", "HIGH-005", "MED-008"],
  "MODEL_FORM_CHANGE (activation dynamics or command slew; may be scoped as declared limitation instead)",
  "Activation/slew regression test: command steps bounded by the declared rise-time model and documented as a limitation.",
  "Plant/controller model-form decision + requalification.",
  ["probe_skeleton.py", "DEFECT_REGISTER.md#HIGH-006"],
  ["P20"]),

D("HIGH-007", "Scorer-code predicate is a control input (RES-43 handoff gate) despite the declared scorer/controller separation",
  "HIGH", ["SCORER_SPEC_DEFECT", "PROVENANCE_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/events.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["canonical_runtime.py:232-240 (_is_true_standing_neighborhood -> env0)", "canonical_runtime.py:268 (env0 passed to recoverer.step)", "stable_recovery.py:580 (in_envelope gates HANDOFF)", "events.py:259-390"],
  "Scorer runs observationally only; no scorer state for control",
  "The runtime calls the scorer's private method _is_true_standing_neighborhood and passes the boolean into StableRecoveryController.step, which uses it (with the 0.05 s sustain) to switch SETTLE->HANDOFF. events.py is bound only by SCORER_SHA256; its constants live in unhashed constants.py.",
  "Static call-graph proof; the private predicate resolves TRUE_STANDING_ENVELOPE/BILATERAL_FZ_THRESHOLD from constants.py.",
  {"handoff_gate": "in_envelope (scorer private predicate)", "scorer_hash_separate_from_controller_hash": True,
   "constants_hash": None},
  "Modifying events.py or constants.py can change the applied action stream and the handoff time, while the controller composition hash stays valid.",
  "Separation claim is prose-only; a pure physical predicate implemented in scorer code is consumed by control.",
  "R001's handoff time (14.487 s) depends on this predicate; E12 occurred 50.8 ms before that handoff.",
  "'Scorer observational only' claim is false as implemented; provenance of control depends on scorer code.",
  ["events.py (SCORER_SHA256)", "constants.py", "RES-43 handoff authority", "CANONICAL_RUNTIME_AUTHORITY.md:121"],
  ["CRIT-004", "CRIT-005", "MED-013"],
  "PROVENANCE/CONTRACT_CHANGE (move shared physical predicate into a hashed neutral module or extend controller hash)",
  "Separation test: changing scorer-only code must not change the action stream; shared predicate must live in the hashed closure.",
  "Successor candidate identity + separation proof.",
  ["PROVENANCE_REVIEW.md", "CONTROL_REVIEW.md"],
  ["P26"]),

D("HIGH-008", "Support margin does not represent the active support polygon and is positive even in flight",
  "HIGH", ["MEASUREMENT_BUG", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py", "src/loaded_cmj/v2/constants.py"],
  ["plant.py:285-300 (AABB from both foot geom centers, hx=0.150, hy=0.060)", "constants.py:183 (0.02 gate)", "full_closure.py:42 (0.05 gate)"],
  "Support margin = distance from COM-xy to the edge of the actual contact support polygon",
  "The margin is computed from an axis-aligned box spanning BOTH foot geom centers with the FULL box half-extents; foot rotation is ignored, and inactive/airborne feet are included. The y-term is structurally ~0.155 m because the model has no lateral DOF.",
  "Recomputation over all 121,889 samples using the production formula: minimum margin 0.0839 m; during true flight 0.0966-0.1285 m. Sample at t=1.06525: fzR=0 N (right foot airborne) yet margin=0.1463 m. True contact-row-based margin can be smaller.",
  {"margin_min_all_samples_m": 0.08385, "margin_during_flight_m": [0.09660, 0.12852],
   "gate_E1_m": 0.02, "gate_RR_m": 0.05, "lateral_DOFs": 0},
  "All margin-based predicates (E1 >=0.02 m, RR/tube/handoff >=0.05 m) are trivially satisfied; the metric cannot detect loss of support.",
  "Support polygon approximated by AABB of full foot boxes, ignoring rotation and active contact.",
  "R001 passes all margin gates without them carrying information.",
  "Any claim resting on 'COM inside the support polygon' is unsupported.",
  ["plant.py (unhashed)", "support_margin semantics", "E1/RR/tube gates", "TRACE_SCHEMA_V2.md:61-62"],
  ["CRIT-003", "MED-005"],
  "MEASUREMENT_CHANGE (compute the convex hull of active contact points; expose support active flags)",
  "Support-margin adversarial test: single-support and airborne states must not report positive margins; rotated-foot hull test.",
  "Measurement + qualification requalification; invalidates margin-based gate evidence.",
  ["CONTACT_REVIEW.md", "probe_forces2.py output"],
  ["P12"]),

D("HIGH-009", "Inactive-foot geometric gap and normal velocity are wrong when the foot is rotated (up to 0.094 m)",
  "HIGH", ["MEASUREMENT_BUG", "SOFTWARE_BUG"], "CONFIRMED",
  ["tools/res52/core52.py", "tools/res52/soft_contact.py", "src/loaded_cmj/v2/balance_capture.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["core52.py:203-218, 226-232", "soft_contact.py:85-97", "balance_capture.py:63-67, 106-110", "stable_recovery.py:179-185"],
  "Lowest foot material point used for the inactive-foot geometric gap and its normal velocity",
  "dist = geom_xpos[2] - geom_size[2] (half thickness 0.010) and p_low = geom_xpos - [0,0,0.010], valid only when the foot is flat. The true lowest corner is geom center + R @ (±hx,±hy,±hz).",
  "Deterministic probe on the frozen XML (probe A2): at ankle q=-0.70 the true lowest z is -0.0582 m vs code value +0.0360 m (error 0.0943 m); at q=+0.35 error 0.0508 m. Accepted R001 keeps feet nearly flat (max |foot pitch| 0.1384 rad at E9; <=0.004 rad during stance), so R001 is not exposed.",
  {"foot_pitch_rad_R001_max": 0.1384, "gap_error_at_limit_m": 0.0943, "gap_error_at_0.35rad_m": 0.0508},
  "For rotated feet the soft-contact layer can believe a foot is ~9 cm clear when it is near contact, corrupting re-engagement targets and normal-velocity rows.",
  "Geometric lowest-point approximation assumes a flat foot; frozen in TRUE_FOOT_POINT_VELOCITY_CONTRACT.md and SOFT_CONTACT_STATE_CONTRACT.md.",
  "Latent in R001 (flat feet); a successor with foot roll/heel-rise will be materially affected.",
  "Contracts that define 'lowest foot-box corner' with this formula are invalid for pitched feet.",
  ["core52.py (unhashed)", "soft_contact.py (unhashed)", "RES-55 contract", "RES-52 contract", "support continuity liftoff evidence"],
  ["HIGH-008", "CRIT-004"],
  "MEASUREMENT_CHANGE (true rotated-box lowest-corner via geom_xmat)",
  "Rotated-foot gap test: code gap must equal true lowest-corner height within 1e-6 m for ankle q in [-0.7,0.5].",
  "Measurement/soft-contact requalification; rotated-foot successors blocked until fixed.",
  ["probe_geometry.py PROBE A2", "CONTACT_REVIEW.md"],
  ["P11"]),

D("HIGH-010", "Declared genuine-flight geometric gap is never implemented (E7 checks force only)",
  "HIGH", ["SCORER_SPEC_DEFECT", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/events.py"],
  ["constants.py:198 (GENUINE_FLIGHT_GAP_M=0.010)", "events.py:211-216 (_guard_genuine_flight)"],
  "Genuine flight requires a minimum geometric foot-floor gap of 0.010 m",
  "E7 guard checks only left_Fz<10 and right_Fz<10 for an 0.08 s dwell; no clearance geometry is consulted anywhere in the event detector.",
  "grep: GENUINE_FLIGHT_GAP_M appears only at its definition; event sample contains no clearance field.",
  {"GENUINE_FLIGHT_GAP_M": 0.010, "uses": 1, "guard_inputs": ["left_Fz", "right_Fz"]},
  "A 10 N force dropout of 0.08 s counts as 'genuine flight'; geometric clearance is uncertified.",
  "Declared threshold never wired into the predicate.",
  "R001 true flight is real (0.043-0.050 m clearance for ~0.223 s), so the accepted result is not false for this run; the specification is still false.",
  "'Genuine flight' claim rests on force thresholds, not geometry; contract wording is unsupported.",
  ["events.py (SCORER_SHA256)", "constants.py", "E7 definition", "BILATERAL_SUPPORT_CONTINUITY_CONTRACT"],
  ["CRIT-003", "HIGH-011"],
  "SCORER_SPEC_CHANGE (wire geometric clearance into E7 or remove the false declaration)",
  "Force-dropout-without-clearance negative control must not latch E7.",
  "Event requalification.",
  ["CONTACT_REVIEW.md", "probe_forces2.py"],
  ["P06"]),

D("HIGH-011", "Apex has no dwell and its fallback path can latch without a flight check",
  "HIGH", ["SCORER_SPEC_DEFECT", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/events.py"],
  ["constants.py:199 (APEX_DWELL_S=0.005)", "events.py:56 (DWELL_S['apex']=0.0)", "events.py:408-439 (_detect_apex_crossing)", "events.py:430-436 (fallback)"],
  "Apex requires a dwell above/below the zero-crossing after genuine flight",
  "DWELL_S['apex']=0.0 and WIN=1; APEX_DWELL_S is unused. _detect_apex_crossing first tries a two-sided flight check but then falls through to an unconditional sign-crossing path that does not verify either foot is unloaded.",
  "Source inspection; first branch condition (lines 414-425) plus fallback at 430-436.",
  {"APEX_DWELL_S": 0.005, "implemented_dwell_s": 0.0},
  "Any com_vz sign crossing after E7 latches apex, including one during ground contact; apex time can be recorded without a physical apex.",
  "Declared dwell not wired; fallback lacks the flight check.",
  "R001 apex (t=0.771976) is inside true flight and plausible; the false-PASS path is latent.",
  "'Apex' event semantics are weaker than declared.",
  ["events.py (SCORER_SHA256)", "E8 definition", "constants.py"],
  ["HIGH-010", "CRIT-003"],
  "SCORER_SPEC_CHANGE (implement dwell + mandatory flight condition)",
  "Contact-phase vz-crossing negative control must not latch E8.",
  "Event requalification.",
  ["EVENT analysis in TEST_SUITE_FORENSIC_REPORT.md"],
  ["P07"]),

D("HIGH-012", "True-standing envelope is a one-trajectory overfit (micron-scale windows, one-U LP expansion)",
  "HIGH", ["QUALIFICATION_DEFECT", "SCORER_SPEC_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/events.py"],
  ["constants.py:220-253 (V2_TRUE_STANDING_REFERENCE/ENVELOPE)", "events.py:259-390 (_is_true_standing_neighborhood)"],
  "Frozen empirical neighborhood for true standing (RES-16/RES-43)",
  "Envelope derived from one deterministic 2 s standing hold: joint windows ~1e-5..6e-4 rad; COM z window ~3.2e-6 m; root z window ~2e-6 m; expanded by one ULP. E12/true-standing certification requires all 7 joints plus COM/root/trunk inside these windows.",
  "Numeric inspection of constants.py; provenance comment states componentwise median over [0.100125, 2.0] from one run on the zero-damping plant.",
  {"com_z_window_m": 3.220416e-6, "root_z_window_m": 1.992e-6, "joint_window_examples_rad": [-0.0010646, 0.0001107]},
  "A physically valid standing pose with slightly different numerical conditioning or a different step size would fail E12; the envelope certifies 'same trajectory', not 'standing'.",
  "Envelope width driven by deterministic reproducibility rather than a physical stability region.",
  "R001 passes E12 essentially by reproducing the reference hold's numerics.",
  "'Stable recovery' qualification is overfit; population/robustness generality unsupported.",
  ["V2_TRUE_STANDING_ENVELOPE", "RES-16/RES-43 authorities", "E12 semantics"],
  ["HIGH-004", "MED-013"],
  "QUALIFICATION_CHANGE (physical standing envelope with declared tolerance, or robustness replication)",
  "Multiple perturbed standing holds must pass/fail E12 consistently with the declared envelope; envelope width must be traceable to a robustness requirement.",
  "Recovery qualification; successor candidate.",
  ["DEFECT_REGISTER.md#HIGH-012", "recovery evidence"],
  ["P36"]),

D("HIGH-013", "Canonical output omits all jump-performance metrics and violates its own required result schema",
  "HIGH", ["QUALIFICATION_DEFECT", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "CANONICAL_V2_RUNTIME_CONTRACT.md", "src/loaded_cmj/v2/events.py"],
  ["canonical_runtime.py:501, 537 (only event_records extracted)", "canonical_runtime.py:540-590 (result dict)", "CANONICAL_V2_RUNTIME_CONTRACT.md:107-115 (required fields)"],
  "Canonical result exposes the declared schema including ENTRY_HEAD/TREE, hashes, CTRL_MODES, and the candidate's performance",
  "Events raw_metrics (APEX_COM_Z, FLIGHT_RISE_FROM_TAKEOFF, TAKEOFF_VZ, FLIGHT_DURATION, COUNTERMOVEMENT_DEPTH, landing peaks, etc.) are computed in events.py but never serialized; ENTRY_HEAD/TREE, PLANT_SHA256, CONTROLLER_COMPOSITION_SHA256, SCORER_SHA256, CONTROL_DT_SEMANTICS, CTRL_MODES are absent from the JSON (CTRL_MODES exists only in the optional npz).",
  "Code inspection + key listing of the sealed V2.1-R001_CANONICAL_RESULT.json.",
  {"required_schema_fields_present": 0, "raw_metrics_serialized": False,
   "result_keys": "OUTCOME/TERMINATION/T_END/EVENTS/SUPPORT_*/... only"},
  "A reader cannot distinguish a 3.6 cm hop from a functional CMJ from the canonical output alone; the qualification artifact cannot substantiate performance claims.",
  "Metrics discarded at the serialization boundary; contract schema not implemented.",
  "R001's canonical result is silent on the very quantities the owner judged visually.",
  "'Canonical qualification' artifact completeness claim is false; performance claims are unverifiable from the sealed output.",
  ["CANONICAL_V2_RUNTIME_CONTRACT.md", "canonical result schema", "RES-12 qualification evidence"],
  ["CRIT-003", "MED-011", "MED-012"],
  "OUTPUT_SCHEMA_CHANGE (emit required fields + performance metrics + hashes)",
  "Schema conformance test against CANONICAL_V2_RUNTIME_CONTRACT.md; performance metrics presence test.",
  "Successor qualification output.",
  ["PROVENANCE_REVIEW.md", "canonical result JSON key listing"],
  ["P27", "P28", "D9"]),

D("HIGH-014", "Soft-contact FZ-min rows are silently dropped during LS refinement; active-set crossings are not handled in the derivative",
  "HIGH", ["SOFTWARE_BUG", "CONTROL_BUG"], "CONFIRMED",
  ["tools/res52/soft_contact.py"],
  ["soft_contact.py:239-248 (FZ_MIN rows appended once)", "soft_contact.py:250-263 (refinement rebuilds base_rows + dist rows)", "soft_contact.py:182-192 (build_G crossing handling)"],
  "FZ_MIN constraints protect against losing plantar force during each control interval; G is a local model valid across contact-mode changes",
  "On the first refinement pass rows are rebuilt as base_rows + distance rows, dropping the appended W_FZ_MIN rows (proved with an instrumented synthetic solve: pass 0 has 18 rows incl. FZ_MIN, passes 1-2 have 15 rows without). build_G increments active_set_crossings but still computes the two-sided secant across the contact-mode discontinuity.",
  "probes/probe_fzmin.py (deterministic, monkeypatched lsq_linear) and source inspection.",
  {"passes": 3, "FZ_MIN_present_pass0": True, "FZ_MIN_present_pass1": False, "FZ_MIN_present_pass2": False, "crossing_handling": "counted only"},
  "The terminal/balance inner layer may accept a solution that violates the min-force margin exactly when contact is marginal.",
  "Refinement loop rebuilds the row set from base_rows only; crossing branches were never implemented in this module (later modules added one-sided fallbacks).",
  "Latent in R001 (validation gates may catch gross violations); no proof that R001 was affected.",
  "Inner-solver force guarantees are weaker than documented; 'soft-contact force realization' claim is conditional.",
  ["soft_contact.py (unhashed)", "RES-52 authority/spec", "terminal/balance inner layer"],
  ["CRIT-004", "HIGH-002", "HIGH-003"],
  "SOFTWARE_FIX (rebuild rows including all constraint families; add crossing one-sided fallback)",
  "Unit test: FZ_MIN row must be present in every refinement pass; crossing test must be one-sided/zero but never a two-sided secant across modes.",
  "Soft-contact/terminal/balance requalification.",
  ["probe_fzmin.py output", "CONTROL_REVIEW.md"],
  ["P21", "P22"]),

D("HIGH-015", "Legacy 'honest full jump' acceptance file is false assurance: 10 assert-True stubs and >=9 events accepted as 12/12",
  "HIGH", ["TEST_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["tests/test_v2_1_res10_honest_full_jump.py"],
  ["lines 1, 100, 119, 135, 154, 157, 162, 179, 208, 211, 219 (assert True)", "lines 137-145, 164-176 (>=9 events)", "lines 18, 186 (legacy controller)"],
  "25 checks certifying the honest full jump",
  "10 of 25 tests are `assert True`; test_e12/test_event_count/test_no_fall accept >=9 events; test_no_fall cannot detect a fall; all runs use the legacy module-level loaded_cmj.v2.controller, not the canonical composition.",
  "Read of the full file; count of assert True across tests/ = 10 (all in this file).",
  {"assert_true": 10, "tests_total": 25, "min_events_accepted": 9, "canonical_composition_used": False},
  "A run that stops at E9 or falls can pass the tests whose names claim E12/no-fall.",
  "Mission-closure leniency was codified into the test file.",
  "R001's own evidence does not come from this file, but the repo's V2.1 test narrative rests on it.",
  "The test-based '12/12' narrative is not evidence of task success.",
  ["test suite credibility", "V2.1 qualification narrative"],
  ["HIGH-016", "HIGH-017"],
  "TEST_FIX (replace placeholders with behavioral invariants; test the canonical composition)",
  "Mutation test: a trajectory truncated at E9 must fail every test whose name claims E12/stable recovery.",
  "Test suite requalification.",
  ["TEST_SUITE_FORENSIC_REPORT.md", "TEST_FILE_INVENTORY.csv"],
  ["P42"]),

D("HIGH-016", "Seven assertions are neutralized by `or True` (unconditional pass) and one test body is a bare pass",
  "HIGH", ["TEST_DEFECT"], "CONFIRMED",
  ["tests/test_v2_1_res31_honest_planar_root.py", "tests/test_res10_controller_obs_sync.py", "tests/test_res11_deterministic_offline.py",
   "tests/test_v2_1_res6_compliant_landing_contact.py", "tests/test_res52_soft_contact.py", "tests/test_res76_full_closure.py",
   "tests/test_res73_balance_capture.py", "tests/test_v2_1_res8_captured_squat.py"],
  ["test_v2_1_res31_honest_planar_root.py:197", "test_res10_controller_obs_sync.py:199", "test_res11_deterministic_offline.py:91",
   "test_v2_1_res6_compliant_landing_contact.py:296", "test_res52_soft_contact.py:372", "test_res76_full_closure.py:55",
   "test_res73_balance_capture.py:143", "test_v2_1_res8_captured_squat.py:167-170 (pass body)",
   "test_rec01a_synchronized_dynamics.py:208-234 (max(abs)>=0)", "test_res52_soft_contact.py:288-295 (monotone counter)"],
  "Named scientific invariants are actually asserted",
  "Each listed assertion parses as `(condition) or True` (or has a body of pass / a monotonicity check that cannot decrease), so the claimed condition can never fail.",
  "Read of exact lines; count `or True` in tests/ = 7; pass-only test bodies located.",
  {"or_true_count": 7, "pass_only_tests": 1, "always_true_asserts": 2},
  "Named checks for scorer circularity, root contact parameters, live-forward purity, E11-alone sufficiency and fall timing cannot detect regressions.",
  "Debug-time neutralization left in place.",
  "R001 is not certified by these checks regardless of their names.",
  "Test coverage claims for these invariants are void.",
  ["test suite credibility"],
  ["HIGH-015", "HIGH-017"],
  "TEST_FIX (restore real assertions; keep intent but make them failure-capable)",
  "Each restored assertion must be shown to fail on a deliberately mutated implementation.",
  "Test suite requalification.",
  ["TEST_SUITE_FORENSIC_REPORT.md"],
  ["P42"]),

D("HIGH-017", "No test executes the canonical composition; the suite validates stored JSON and breaks at collection",
  "HIGH", ["TEST_DEFECT"], "CONFIRMED",
  ["tests/test_res78_canonical_runtime.py", "tests/test_ml241_qacc_resolution.py", "tests/test_public_support_wrench_contract.py"],
  ["test_res78_canonical_runtime.py:52-56 (_canon_result reads stored JSON)", ":87 (only callability of run_canonical_episode)", ":215-223 (reads external RUN_A/B)",
   "test_ml241_qacc_resolution.py:21 (import-time external evidence path)", "test_public_support_wrench_contract.py:26 (missing symbol)"],
  "The canonical runtime is tested end-to-end",
  "The only invocation of run_canonical_episode in tests is a callable() check; events/checkpoints are asserted against a stored result JSON; two tracked test modules fail at collection (missing external evidence file; ImportError of shift_wrench_to_origin).",
  "pytest --collect-only run during the audit: `Interrupted: 2 errors during collection`.",
  {"pytest_collect_errors": 2, "live_canonical_episode_tests": 0, "stored_result_assertions": 13},
  "A stale but self-consistent evidence bundle passes; the suite cannot reproduce the candidate on a clean machine.",
  "Acceptance anchored to external evidence artifacts instead of executing the composition.",
  "R001's tests certify the stored artifact, not the current source.",
  "The test suite cannot substantiate current-code qualification.",
  ["test suite credibility", "canonical runtime", "clean-clone reproducibility"],
  ["HIGH-015", "HIGH-018", "CRIT-006"],
  "TEST_FIX (one bounded live smoke run or explicit artifact-identity binding; fix collection failures)",
  "Fresh-process canonical smoke test with hash binding; collection must succeed on a clean clone without external evidence.",
  "Test suite + qualification requalification.",
  ["TEST_SUITE_FORENSIC_REPORT.md", "pytest_collect.txt transcript"],
  ["P42"]),

D("HIGH-018", "Qualification orchestration omits two scripts (one hardcodes PASS); test_public_qualification runs only 10 of 19 suites",
  "HIGH", ["TEST_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["tests/test_public_qualification.py", "tests/qualification_causal_runtime.py", "tests/qualification_ml241_wrapped_derivatives.py"],
  ["test_public_qualification.py:14-25 (QUALIFICATION_SUITES), :49 (PASS check exempts policy isolation)",
   "qualification_causal_runtime.py:470-497 (result hardcoded PASS; return 0)", "qualification_ml241_wrapped_derivatives.py:835 (return 0 unconditional)"],
  "The public qualification entry point runs all qualification suites and gates on their PASS/FAIL",
  "Only 10 of 19 qualification scripts are invoked; qualification_causal_runtime.py writes result=PASS and exits 0 unconditionally and is not invoked by the orchestrator; qualification_ml241_wrapped_derivatives.py also returns 0 regardless of evidence.",
  "Read of the orchestrator list and the two scripts' exit paths.",
  {"qualification_scripts_total": 19, "invoked": 10, "ungated_pass_scripts": 2},
  "Two 'proof producer' scripts cannot fail; the qualification suite's PASS surface is incomplete.",
  "Orchestration list stale; results hardcoded during development.",
  "Not part of R001's V2.1 path directly, but part of the repo's qualification credibility.",
  "Repository-wide qualification status is not defensible.",
  ["public qualification", "test suite credibility"],
  ["HIGH-017"],
  "TEST_FIX (include all suites; remove hardcoded PASS; gate on exit codes and evidence)",
  "Orchestrator coverage test: enumerated scripts == executed scripts; each script must fail on a mutated input.",
  "Qualification orchestration requalification.",
  ["TEST_SUITE_FORENSIC_REPORT.md"],
  ["P42"]),

D("HIGH-019", "Rigid single-box foot: no MTP/toe/arch; R001 push-off is flat-footed with no heel rise",
  "HIGH", ["MODEL_FORM_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/assets/v2_plant.xml"],
  ["v2_plant.xml:105-109, 133-137 (single box; ankle only)", "v2_plant.xml:106, 134 (ankle range -0.70..0.50)"],
  "Foot mechanics adequate for a loaded CMJ push-off (ankle plantarflexion/forefoot rocker)",
  "One rigid box per foot attached at the ankle; no metatarsophalangeal joint, no toe segment, no arch. Geometric foot pitch during R001 stance is <=0.004 rad (takeoff 0.0043 rad) and never rolls; peak |pitch| 0.1384 rad during landing is the entire range.",
  "geometry probe A2 + R001 foot-pitch computed from geom_xmat over all 121,889 samples (probe_footpitch.py).",
  {"stance_max_abs_pitch_rad": 0.003970, "pitch_at_E6_rad": 0.0043, "R001_max_abs_pitch_rad": 0.1384,
   "MTP_joints": 0, "toe_segments": 0},
  "No forefoot rocker; the push-off is a flat-foot knee/hip extension; toe-off mechanics observed as 'clearly inadequate' are structural, not a controller tuning issue.",
  "Foot model form; single hinge with no segmentation.",
  "R001's takeoff lacks human ankle/forefoot contribution.",
  "'Loaded CMJ' human foot mechanics claim unsupported; acceptable only under an explicitly reduced-model claim.",
  ["Plant XML", "foot geometry", "contact model"],
  ["CRIT-001", "HIGH-009"],
  "MODEL_FORM_CHANGE (add MTP/toe segmentation or declare the limitation and exclude push-off claims)",
  "Foot-roll/heel-rise capability test with declared geoms and joint; push-off visual/physics coherence review.",
  "Successor plant + full requalification.",
  ["CONTACT_REVIEW.md", "probe_footpitch.py"],
  ["P10", "P45-adjacent"]),

# ============================== MEDIUM ==============================
D("MED-001", "Systematic dwell off-by-one: every dwell event confirms one physics sample (0.125 ms) before the declared duration",
  "MEDIUM", ["SCORER_SPEC_DEFECT", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/events.py"],
  ["events.py:600-601, 660-661, 701-702, 738-739, 776-777, 831-832 (elapsed=idx-start+1)", "events.py:64-68 (_win)"],
  "Dwell of D seconds requires D seconds of sustained condition",
  "Each event latches when idx-start+1 >= round(D/DT), i.e. after (n-1)*DT physical time.",
  "Sealed event records: all 10 dwell events confirm exactly one sample early (0.099875 vs 0.10, 0.029875 vs 0.03, 0.009875 vs 0.01, 0.049875 vs 0.05, 0.079875 vs 0.08, 0.019875 vs 0.02, 0.149875 vs 0.15, 0.499875 vs 0.50).",
  {"dwell_errors_s": -0.000125, "affected_events": 10},
  "Systematic but numerically negligible timing shift (0.125 ms) in event certificates.",
  "Sample counting treats the first sample as elapsed time.",
  "R001 event times are each one sample early relative to declared dwells.",
  "Event timing certificates are off by one physics sample; material only for tight dwell semantics.",
  ["events.py (SCORER_SHA256)", "all event times"],
  ["HIGH-011", "CRIT-003"],
  "SOFTWARE_FIX (require idx-start >= n or document sample-count dwell semantics)",
  "Dwell boundary unit test at the exact declared duration.",
  "Event requalification (numeric shift only).",
  ["EVENT adjudication table in DEFECT_REGISTER.md"],
  ["P29"]),

D("MED-002", "E11 threshold is named COM_SPEED but implemented on com_vz only",
  "MEDIUM", ["SCORER_SPEC_DEFECT", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/events.py", "src/loaded_cmj/v2/constants.py"],
  ["events.py:247-257 (_guard_balance_capture)", "constants.py:204 (BALANCE_CAPTURE_COM_SPEED_MPS)"],
  "Balance capture requires CoM speed below 0.30 m/s (bidirectional)",
  "Guard checks abs(com_vz) < 0.30; horizontal speed is never used.",
  "Source inspection; in R001 both variants cross 0.30 at the same sample (t=0.990), so the defect is latent here.",
  {"R001_first_vz_below_threshold_s": 0.990, "R001_first_speed_below_threshold_s": 0.990, "speed_at_E11_occ_mps": 0.2792},
  "A candidate with large horizontal speed but small vertical speed would latch E11 early.",
  "Name/spec mismatch: speed versus vertical component.",
  "No R001 impact (coincident thresholds).",
  "E11 semantics weaker than named; latent false-PASS for horizontal-momentum landings.",
  ["events.py (SCORER_SHA256)", "E11 definition"],
  ["HIGH-001"],
  "SCORER_SPEC_FIX (use horizontal or total CoM speed as declared)",
  "E11 negative control with |vz|<0.30 but speed>0.30.",
  "Event requalification.",
  ["probe_landing.py", "DEFECT_REGISTER.md#MED-002"],
  ["P09"]),

D("MED-003", "Pelvis orientation observation is a hardcoded identity quaternion",
  "MEDIUM", ["MEASUREMENT_BUG", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py", "src/loaded_cmj/v2/measurement.py"],
  ["plant.py:362-364", "measurement.py:249"],
  "pelvis_orientation_world_quat_wxyz is the true world orientation of the pelvis (root_ry pitch)",
  "Both observation builders return [1,0,0,0] unconditionally; root pitch is available in qpos/root_ry but is not exposed as a quaternion.",
  "Source read; root pitch reaches 0.4315 rad at RR entry, so the reported quaternion is wrong whenever the body pitches.",
  {"root_pitch_max_rad_in_R001": 0.5918, "reported_quat": [1,0,0,0]},
  "Any consumer of the declared observation field receives a false pelvis orientation; V2.1 controllers do not consume this field, so R001 control is unaffected.",
  "Placeholder left in the observation implementation.",
  "R001 controllers unaffected; observation contract broken for external consumers.",
  "CANONICAL observation contract ('pelvis orientation') is not implemented.",
  ["plant.py", "measurement.py (CONTROLLER_OBSERVATION_CONTRACT)", "observation schema"],
  ["MED-004"],
  "MEASUREMENT_FIX (compose the root_ry quaternion)",
  "Observation test: quaternion must match MuJoCo pelvis xmat/quat under nonzero root pitch.",
  "Measurement requalification.",
  ["DEFECT_REGISTER.md#MED-003"],
  ["P18"]),

D("MED-004", "Trunk tilt measurement is unsigned",
  "MEDIUM", ["MEASUREMENT_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py", "src/loaded_cmj/v2/events.py"],
  ["plant.py:178-185 (arccos of torso z-axis)", "events.py:395 (abs(trunk_tilt))"],
  "Signed trunk pitch (forward/backward distinguishable)",
  "trunk_tilt_rad is arccos(up_world[2]) in [0, pi], losing sign; event predicates then take abs().",
  "Source + R001 trace: at E4 the trunk is tilted backward ~18 deg but reports +0.31 rad; at E11 forward ~25 deg reports +0.437.",
  {"trunk_tilt_backward_at_E4_deg": -18.0, "reported_rad": 0.31, "forward_at_E11_deg": 25.0, "reported_rad": 0.437},
  "Backward and forward lean are indistinguishable; guards that already use abs() are unaffected, but claims about posture direction cannot be made.",
  "Unsigned angle by construction.",
  "R001 gate behavior unaffected; posture forensics limited.",
  "Posture-direction claims unsupported by measurement.",
  ["plant.py", "measurement.py", "event predicates"],
  ["HIGH-004"],
  "MEASUREMENT_FIX (atan2 signed pitch)",
  "Signed-tilt test under forward and backward lean.",
  "Measurement/event requalification.",
  ["DEFECT_REGISTER.md#MED-004"],
  ["P17"]),

D("MED-005", "CoP frame/origin is misdeclared and its validity threshold disagrees with the declared constant",
  "MEDIUM", ["MEASUREMENT_BUG", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py", "TRACE_SCHEMA_V2.md", "src/loaded_cmj/v2/constants.py"],
  ["plant.py:263-277 (origin = foot body xpos xy at z=0; validity Fz>20)", "constants.py:180 (V2_CONTACT_FZ_THRESHOLD_N=10)", "TRACE_SCHEMA_V2.md:51"],
  "plantar_cop_xy_m in the plate frame with the documented validity threshold",
  "CoP is computed relative to the moving ankle projection, not the plate/box center; validity uses Fz>20 N while the named per-foot threshold is 10 N; no origin is exposed; no production controller consumes the measured CoP (analytic clamps are used instead).",
  "Source read; numeric example: flat stance CoP should be at box center (0.045, +-0.095) but is reported as (0.045, 0) relative to the ankle.",
  {"validity_threshold_implemented_n": 20.0, "declared_threshold_n": 10.0, "origin": "ankle xy projection"},
  "CoP evidence is frame-ambiguous and cannot be compared across samples without the foot pose; external reuse is error-prone.",
  "Origin choice and magic threshold not tied to the authority constant.",
  "R001: CoP not used by control; evidence semantics only.",
  "CoP-based claims (support/interaction) are unsupported as reported.",
  ["plant.py", "TRACE_SCHEMA_V2.md", "V2_CONTACT_FZ_THRESHOLD_N"],
  ["HIGH-008", "MED-011"],
  "MEASUREMENT_FIX (define origin per plate center, expose origin, unify threshold)",
  "Frame-identity test: CoP + origin + force must reconstruct the world wrench at the contact plane.",
  "Measurement requalification.",
  ["CONTACT_REVIEW.md"],
  ["P13"]),

D("MED-006", "prohibited_contact is structurally always False; PROHIB=false in the canonical result carries no information",
  "MEDIUM", ["MEASUREMENT_BUG", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py", "src/loaded_cmj/v2/canonical_runtime.py"],
  ["plant.py:252-261 (shell geoms scan)", "v2_plant.xml:42-45 (shell contype=0 conaffinity=0)", "canonical_runtime.py:444,561"],
  "prohibited_contact detects non-plantar body support",
  "The scanned shell geoms can never generate contacts (contype/conaffinity zero), so the flag is always False; the only real fall signal is fall_contact (fall shells contype=4 vs floor).",
  "Source + wheel/model inspection; also noted in tests/test_v2_1_res5_honest_fall.py:229-231.",
  {"prohibited_true_possible": False},
  "A false assurance field: 'no prohibited contact' means only 'no impossible contact could be detected'.",
  "Body shell collision disabled by design; the flag was left scanning disabled geoms.",
  "R001 PROHIB=false is vacuous; FALL=false is the meaningful signal.",
  "Prohibited-contact certification is void.",
  ["plant.py", "canonical result PROHIB field", "TRACE_SCHEMA_V2.md prohibited_flag"],
  ["MED-007"],
  "MEASUREMENT_FIX (scan actual load/body colliders or remove the field and its claims)",
  "Injected fall-contact test must raise prohibited/fall flags.",
  "Measurement/qualification requalification.",
  ["CONTACT_REVIEW.md"],
  ["P30-adjacent"]),

D("MED-007", "Collision topology permits anatomically impossible intersections and the 20 kg load has no collision geometry at all",
  "MEDIUM", ["MODEL_FORM_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/assets/v2_plant.xml"],
  ["v2_plant.xml:42-45 (shell class 0/0)", "v2_plant.xml:64-83 (pelvis/torso/load shells)", "v2_plant.xml:143-153 (contact excludes)"],
  "Body self-collision and load collision reasonably approximated",
  "All body shells are non-colliding; the load cylinder has no fall shell; adjacent-segment pairs and pelvis-torso/pelvis-load/torso-load are excluded. Self-overlap is kinematically possible in deep flexion/falls and generates no contact. Foot-shank exclusion has ~6 mm minimum clearance.",
  "Contact-matrix analysis and geometry probe; fall states are only detected by the six fall shells vs floor.",
  {"fall_shells": 6, "load_collision_geoms": 0, "self_collision": False},
  "In fall/landing-collapse states the model can show impossible interpenetration or a load passing through the floor without detection.",
  "Reduced collision model for robustness; load modeled as inertia only.",
  "R001 (flat, symmetric, no fall) is not affected.",
  "Fall-state and load-interaction claims unsupported; visual credibility risk in successors.",
  ["Plant XML", "fall detection", "load model"],
  ["HIGH-019", "MED-006"],
  "MODEL_FORM_CHANGE (add minimal load/self colliders or declare the limitation and forbid fall-state claims)",
  "Fall-state interpenetration audit; load-floor collision detection test.",
  "Successor plant; fall requalification.",
  ["CONTACT_REVIEW.md"],
  ["P30"]),

D("MED-008", "FLEX->EXTEND program switch is a hard scheduled step (0.568) unrelated to state",
  "MEDIUM", ["CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/res72_integration.py"],
  ["res72_integration.py:59-60 (FLEX_TAU/EXTEND_TAU)", "res72_integration.py:191-200 (t_in<0.30 switch)"],
  "Smooth countermovement-to-extension transition",
  "Torque program switches at t_in=0.30 from +20 Nm to -75/-150 Nm with no slew or state condition; observed |du|=0.568 in one 5 ms interval at t=0.400.",
  "Sealed action schedule analysis.",
  {"switch_t_s": 0.400, "max_du": 0.568, "tau_step_hip_nm": 95.0, "tau_step_knee_nm": 170.0},
  "An impulsive extension onset at a fixed time rather than a state-triggered reversal; contributes to the mechanical feel.",
  "Time-programmed controller with no state-feedback termination.",
  "R001 extension onset is a fixed-time torque step; contributes to the non-human transition feel.",
  "Countermovement-to-extension timing is not a physical reversal detection; technique interpretation limited.",
  ["res72_integration.py", "confirmation timing"],
  ["HIGH-006", "CRIT-007"],
  "CONTROL_CHANGE (state-based reversal detection/slew)",
  "Program-switch continuity test bounded by declared slew.",
  "Controller requalification.",
  ["CONTROL_REVIEW.md", "probe_skeleton.py output"],
  ["P03"]),

D("MED-009", "Post-projection clamps can leave the CoP/Fx/Hdot triple off the feasible line",
  "MEDIUM", ["SOFTWARE_BUG", "CONTROL_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/balance_capture.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["balance_capture.py:149-175", "stable_recovery.py:307-325"],
  "Fx/Hdot are projected onto the CoP-feasible line before being commanded",
  "After the weighted projection, Fx is re-clipped to the brake bounds and then Hdot is derived and clipped; if the Hdot clip binds, Fx is recomputed and clipped again, so the final pair can be off the line. COP_X bounds are static and unrelated to actual foot pose.",
  "Line-by-line control-flow analysis of both implementations.",
  {"residual_offline_error_bound": "~cz*|dFx|/Fz", "static_cop_bounds_m": [-0.023, 0.237]},
  "Bounded feasibility error in the outer wrench demand; inner layer limits physical consequence.",
  "Iterative clamp without a final joint projection.",
  "No demonstrated R001 effect; latent.",
  "CoP-feasibility guarantee is approximate, not exact.",
  ["balance_capture.py", "stable_recovery.py"],
  ["HIGH-003"],
  "SOFTWARE_FIX (single final projection onto the feasible set)",
  "Property test: commanded (Fx,Hdot,Fz) always satisfies the CoP line within tolerance.",
  "Balance/recovery requalification.",
  ["CONTROL_REVIEW.md"],
  ["P24"]),

D("MED-010", "Legacy controller swallows all exceptions and commands zero action",
  "MEDIUM", ["SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/controller.py"],
  ["controller.py:127-128 (bare except -> [0]*7)"],
  "Controller failures are surfaced",
  "Any exception in act() (including malformed observation, nonfinite state) results in a silent all-zero action.",
  "Source read; module is not used by the canonical composition but is exercised by multiple tests.",
  {"bare_except": True, "failure_action": "[0]*7"},
  "Silent zero-torque failure is indistinguishable from a valid command, producing falls without diagnostics.",
  "Catch-all for robustness.",
  "No R001 production impact (legacy module); latent test/legacy risk.",
  "Legacy controller qualification claims unsupported.",
  ["controller.py", "legacy tests"],
  ["MED-019"],
  "SOFTWARE_FIX (fail loudly or return explicit fallback state)",
  "Malformed-observation test must surface an error, not zeros.",
  "Legacy module deprecation or requalification.",
  ["BUG_HUNT.md"],
  ["P37"]),

D("MED-011", "Reporting metrics are misdefined or dead: loading rate, apex_height alias, CoP invalid-interval analysis",
  "MEDIUM", ["MEASUREMENT_BUG", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/events.py", "src/loaded_cmj/v2/measurement.py"],
  ["events.py:1133-1136 (loading_rate = peak/(t_peak-land_time))", "events.py:1078 (apex_height = apex_z absolute)",
   "events.py:1224-1240 (CoP invalid intervals loop/dead variable)", "measurement.py:279-305 (event_sample lacks CoP keys)"],
  "Loading rate is a force rise rate; apex_height is jump height; CoP validity intervals are reported",
  "loading_rate is a secant peak/time value ignoring the starting force and is not a maximum slope; apex_height equals absolute COM z (FLIGHT_RISE_FROM_TAKEOFF carries the rise); the CoP interval loop breaks after the first sample and its result is unused, and event samples carry no CoP validity keys so the branch is unreachable.",
  "Source read + key inspection of event_sample output.",
  {"loading_rate_definition": "primary_peak/max(dt_peak,1e-9)", "apex_height": "absolute COM z", "cop_interval_reported": False},
  "Evidence reports can state misleading numbers; CoP handling claims in metrics are unsupported.",
  "Metric definitions not reconciled with their names; event sample never industrialized.",
  "No effect on R001 control; reporting only.",
  "Performance/loading claims derived from these fields are unreliable.",
  ["events.py (SCORER_SHA256)", "measurement.event_sample", "canonical output"],
  ["HIGH-013"],
  "REPORTING_FIX (define each metric, wire CoP validity, rename/derive jump height)",
  "Metric definition tests against a synthetic force trace; CoP validity interval presence test.",
  "Scorer reporting requalification.",
  ["DEFECT_REGISTER.md#MED-011"],
  ["P40", "P41", "P28"]),

D("MED-012", "Full-trajectory support adjudication is NOT_QUALIFIED while reported gates use the post-landing slice only",
  "MEDIUM", ["QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/support_continuity.py"],
  ["canonical_runtime.py:459-461 (SUPPORT_FULL)", ":482-499 (sliced adjudications)", ":562-567 (result fields)"],
  "Support-continuity contract applies to the trajectory; qualification gates reflect it",
  "SUPPORT_FULL reports NOT_QUALIFIED (CONTROL_RELEVANT_SUPPORT_LOSS_COUNT=2, CANONICAL_REFLIGHT=[4,8,1815], CHATTER_TRANSITIONS=188) because flight is counted as reflight; the declared hard gates use SUPPORT_POST_LANDING (from t=0.875) which is QUALIFIED.",
  "Sealed canonical result SUPPORT_FULL / SUPPORT_POST_LANDING blocks.",
  {"SUPPORT_FULL": "NOT_QUALIFIED", "reflights": [4, 8, 1815], "chatter": 188, "SUPPORT_POST_LANDING": "QUALIFIED"},
  "The qualification gate set is a slice choice; the full-contract verdict is negative and this is not surfaced in the receipt.",
  "Flight windows inherently produce reflight under the full-trajectory predicate; gating was scoped to post-landing.",
  "R001 passes the scoped gates; the full adjudication would fail.",
  "Support-continuity claim must be stated as post-landing only; the full verdict is negative.",
  ["support_continuity.py", "post-landing gates", "RES-57 evidence"],
  ["HIGH-008", "HIGH-013"],
  "QUALIFICATION_CHANGE (state and justify the exact adjudicated window in the contract and receipt)",
  "Contract test: the reported gate window must match the declared contract scope.",
  "Qualification reporting.",
  ["support_continuity output in canonical result"],
  []),

D("MED-013", "E12 fires 50.8 ms before the RES-43 handoff; part of its dwell is earned under SETTLE, not the final hold",
  "MEDIUM", ["QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/stable_recovery.py"],
  ["canonical_runtime.py:270-273 (handoff capture), :428-430 (E12 pre-handoff calc)", "stable_recovery.py:580-586 (SETTLE->HANDOFF)"],
  "Stable recovery is certified under the final standing hold",
  "E12 occurrence at 14.436 s precedes the RES-43 handoff at 14.487 s by 50.8 ms; E12 confirmation at 14.936 s includes 0.449 s under RES-43 and 0.0508 s under SETTLE.",
  "Sealed canonical result E12_PRE_HANDOFF_S=0.05075 and E12_UNDER_RES43_S=0.449125.",
  {"E12_occ_s": 14.43625, "handoff_s": 14.487, "E12_pre_handoff_s": 0.05075, "E12_under_RES43_s": 0.44913},
  "The scorer certificate is not exclusively tied to the final controller mode.",
  "Events are observational and cross regime boundaries by design; the receipt presents E12 as the handoff certificate.",
  "R001 E12 crossing the handoff is a qualification-presentation issue.",
  "'E12 under RES-43 hold' claim is only 89.8% of the dwell.",
  ["E12 semantics", "RES-43 handoff", "canonical result"],
  ["HIGH-007", "HIGH-012"],
  "QUALIFICATION_CHANGE (define whether E12 must complete under RES-43 or across regimes)",
  "Regime-boundary test: E12 dwell must satisfy the declared regime coverage.",
  "Recovery qualification reporting.",
  ["canonical result E12 fields"],
  []),

D("MED-014", "Horizon authority drift: four coexisting horizons (4.0/8.0/20.0) with no runtime binding",
  "MEDIUM", ["DOCUMENTATION_DEFECT", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py", "src/loaded_cmj/v2/canonical_runtime.py", "tools/res52/core52.py", "src/loaded_cmj/v2/events.py"],
  ["constants.py:27-28 (8.0/1600)", "canonical_runtime.py:67 (20.0)", "core52.py:50 (4.0)", "events.py:859 (finalize default 4.0)"],
  "One canonical episode horizon",
  "Canonical runtime uses 20.0 s; constants declare 8.0 s; the research core uses 4.0 s; finalize's horizon_s parameter is unused. The doc/authority ledger still says 8.0 s.",
  "Source + sealed environment/registry.",
  {"horizons_s": [4.0, 8.0, 20.0], "runtime_horizon_s": 20.0, "constants_horizon_s": 8.0},
  "Readers and successors can pick the wrong horizon; constants-based tooling is inconsistent with the canonical run.",
  "Const declined to be updated across the V2.1 history; canonical hardcodes its own.",
  "R001 ran 15.236 s of a 20 s budget; the 8 s constant is only documentation-stale here.",
  "Horizon claims must cite the canonical runtime, not constants.py.",
  ["constants.py", "CANONICAL_V2_CANDIDATE_SPEC", "AUTHORITY_LEDGER.json", "core52.py"],
  ["MED-015"],
  "DOCUMENTATION/FIX (single horizon authority)",
  "Authority-consistency test comparing constants/spec/runtime horizon values.",
  "Documentation and constants reconciliation.",
  ["PROVENANCE_REVIEW.md"],
  ["P35"]),

D("MED-015", "Provenance artifacts disagree on entry heads and the authority ledger is stale/corrupted",
  "MEDIUM", ["PROVENANCE_DEFECT", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["CANONICAL_CANDIDATE_IDENTITY.json", "CANONICAL_V2_CANDIDATE_SPEC.json", "CANONICAL_V2_RUNTIME_CONTRACT.md", "tools/res79_smoke_replay.py", "AUTHORITY_LEDGER.json"],
  ["identity ENTRY_HEAD=20e7488/tree a8da465", "spec/contract ENTRY_HEAD=9ca6a8b/tree 41e4dc81", "res79 smoke ENTRY_HEAD=395c194/tree 532dfb4b", "actual audit HEAD=8f26736 (commit message V2.1: add accepted trajectory visual smoke replay)", "AUTHORITY_LEDGER.json uv_lock_hash malformed/stale entries"],
  "One canonical entry head/tree identifies the candidate's source state",
  "At least four different entry heads coexist; test_res78 enforces the spec's 9ca6a8b while the identity file says 20e7488; the ledger references a pre-V2.1 head and a corrupted uv_lock hash.",
  "grep of all authority artifacts; test_res78:80.",
  {"entry_heads": ["9ca6a8b6b01a600a2b8c983d674ddea63b2e53b2", "20e7488ae727c02b581ec4c8e668476ec4432fa5", "395c19426448ea7a3c1b7e612aff1a64e086972f", "8f26736db1231042cbedc61f61ca4862b7be871c"]},
  "A reader cannot determine which commit is the authoritative candidate source.",
  "Authority files updated at different times without a single source of truth.",
  "R001 reproducibility is unaffected; provenance claims are ambiguous.",
  "Entry-head provenance claims unsupported until reconciled.",
  ["CANONICAL_CANDIDATE_IDENTITY", "spec/contract", "AUTHORITY_LEDGER", "res79 metadata"],
  ["CRIT-004", "MED-014"],
  "PROVENANCE_FIX (single identity artifact; regenerate ledger)",
  "Identity-consistency test over spec/contract/identity/tool.",
  "Successor provenance.",
  ["PROVENANCE_REVIEW.md"],
  []),

D("MED-016", "Production modules hardcode developer absolute paths and inject sys.path; evid_trace_v2 is imported under two module identities",
  "MEDIUM", ["PROVENANCE_DEFECT", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/balance_capture.py", "src/loaded_cmj/v2/stable_recovery.py", "src/loaded_cmj/v2/canonical_runtime.py", "tools/res52/core52.py"],
  ["balance_capture.py:18-25", "stable_recovery.py:24-34", "canonical_runtime.py:35-41,74-76", "core52.py:35-37"],
  "Package code is location-independent",
  "Library modules insert /home/litju/... into sys.path; canonical_runtime also bootstraps sibling dirs; evid_trace_v2 loads both as top-level and as tools.evid_trace_v2 (duplicate module identity).",
  "Source grep (35 absolute /home/litju occurrences in src+tools).",
  {"absolute_path_refs": 35, "duplicate_module_identity": ["evid_trace_v2", "tools.evid_trace_v2"]},
  "Relocated clones/integrated deployments fail or import divergent copies; fixes can be masked.",
  "Research-time path shortcuts left on production import paths.",
  "The author's machine works; no R001 numerical effect.",
  "Clean-clone/reproducibility claims limited.",
  ["package layout", "sys.modules identity", "clean-clone audit"],
  ["CRIT-006"],
  "PACKAGING_FIX (relative imports; single module identity)",
  "Relocated-clone test with a different root and CWD.",
  "Successor release qualification.",
  ["PROVENANCE_REVIEW.md", "CRIT-006"],
  ["P34"]),

D("MED-017", "Production swallows diagnostics and reports sentinel values instead of failing closed",
  "MEDIUM", ["SOFTWARE_BUG", "QUALIFICATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/res72_integration.py", "tools/res52/soft_contact.py"],
  ["canonical_runtime.py:388-389 (checkpoint exception swallowed)", "canonical_runtime.py:477-499 (adjudication errors -> {'error'} and -1 sentinels)",
   "res72_integration.py:232-236 (only VALIDATED/FALLBACK/shrinks forwarded)", "soft_contact.py:327-343 (Y_VAL etc. describe the rejected candidate on fallback)"],
  "Fail closed with diagnostics on errors and record what was actually executed",
  "Checkpoint failures are logged and ignored; support-adjudication exceptions become sentinels that the runtime itself does not gate; on soft-contact fallback the returned diagnostics (Y_VAL/du) still describe the rejected trial action while u is the held action.",
  "Source inspection.",
  {"swallowed_checkpoint_exceptions": True, "post_loss_sentinel": -1, "fallback_telemetry_mismatch": True},
  "A failed adjudication or checkpoint silently degrades evidence; fallback telemetry can mislead post-hoc analysis.",
  "Broad except blocks added for robustness without fail-closed gating.",
  "No demonstrated R001 effect (adjudications succeeded).",
  "Evidence completeness/trust limited; a silent failure could pass as an empty result.",
  ["canonical_runtime.py", "soft_contact.py", "adjudication fields"],
  ["CRIT-004"],
  "SOFTWARE_FIX (fail closed; record executed action in fallback)",
  "Fault-injection test: forced adjudication exception must terminate or flag the run.",
  "Runtime/evidence requalification.",
  ["BUG_HUNT.md"],
  ["P38"]),

D("MED-018", "Dwell/threshold literals are duplicated across runtime, mirror module and external JSON with no binding",
  "MEDIUM", ["SOFTWARE_BUG", "PROVENANCE_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py", "src/loaded_cmj/v2/full_closure.py", "src/loaded_cmj/v2/res72_integration.py"],
  ["canonical_runtime.py:70 (E10_NEED=160), :338 (E10 literals)", "full_closure.py:26 (E10_DWELL_SAMPLES=160), :35-45 (RR_THRESHOLDS)", "external recovery_ready_spec.json consumed at runtime"],
  "One frozen authority per constant",
  "E10 dwell/thresholds exist as runtime literals and in full_closure mirrors; RR thresholds/dwell come from external JSON while full_closure carries a different frozen copy that the runtime never reads. Changing either side diverges silently.",
  "Source comparison (full_closure is hash-bound but dead; runtime literals unhashed).",
  {"e10_dwell_duplicates": 2, "rr_threshold_copies": 2, "full_closure_executed": False},
  "Authority drift risk; qualification mirrors may not match executed logic.",
  "Refactor left mirrors for provenance while the executable path was re-implemented.",
  "R001 constants happen to agree.",
  "Frozen-constant claims are not verifiable from a single source.",
  ["full_closure.py", "canonical_runtime.py", "external RR spec"],
  ["CRIT-004", "MED-014"],
  "PROVENANCE_FIX (single imported constant source)",
  "Authority-consistency test over all copies.",
  "Successor provenance.",
  ["PROVENANCE_REVIEW.md"],
  []),

D("MED-019", "Multiple V2.1-named tests exercise the legacy controller, not the canonical composition",
  "MEDIUM", ["TEST_DEFECT", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["tests/test_v2_1_res10_honest_full_jump.py", "tests/test_v2_1_res16_true_standing.py", "tests/test_v2_1_res5_honest_fall.py",
   "tests/test_v2_1_res6_compliant_landing_contact.py", "tests/test_v2_1_res8_captured_squat.py",
   "tests/test_v2_1_res31_honest_planar_root.py", "tests/test_v2_1_res42_zero_root_damping.py",
   "tests/test_res10_controller_obs_sync.py", "tests/test_res10_physics_sample_sync.py"],
  ["controller.py module-level act/reset", "test files import loaded_cmj.v2.controller"],
  "V2.1 controller behavior is tested",
  "These suites import the 128-line legacy module (module-global state, catch-all except) while the production path is Res72Policy/Balance/Recovery; no test imports/executes the canonical composition.",
  "grep of test imports; legacy module has no importers in src.",
  {"legacy_controller_test_files": 9, "canonical_composition_test_files": 0},
  "V2.1 test names overstate what is exercised; legacy behavior may be discontiguous with production.",
  "Historical tests were not migrated when the composition was split.",
  "R001 is not certified by these tests.",
  "V2.1 test-coverage narrative is not defensible.",
  ["test suite credibility", "legacy controller"],
  ["HIGH-015", "HIGH-017"],
  "TEST_FIX (migrate to canonical composition or mark historical)",
  "Coverage test: V2.1-named suites must import the canonical entrypoint.",
  "Test suite requalification.",
  ["TEST_FILE_INVENTORY.csv", "TEST_SUITE_FORENSIC_REPORT.md"],
  []),

D("MED-020", "E1 supported-start guard omits the fall flag (only the dead prohibited flag is checked)",
  "MEDIUM", ["SCORER_SPEC_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/events.py"],
  ["events.py:126-141 (_guard_supported_start checks prohibited, not fall_contact)"],
  "Supported start excludes falling states",
  "The guard checks prohibited (structurally always False) but not fall_contact; a fall shell on the floor during the first 0.1 s would not block E1 (the fall latch would later set physical_fall).",
  "Source read + MED-006.",
  {"fall_checked": False, "prohibited_effective": False},
  "E1 can latch in a fall-adjacent state; subsequent fall handling still fails the run.",
  "Predicate uses the wrong flag.",
  "Latent in R001 (no fall).",
  "E1 semantics weaker than declared.",
  ["events.py (SCORER_SHA256)", "E1 definition"],
  ["MED-006"],
  "SCORER_SPEC_FIX (check fall_contact in E1)",
  "Fall-at-start negative control must not latch E1.",
  "Event requalification.",
  ["TEST_SUITE_FORENSIC_REPORT.md"],
  []),

# ============================== LOW ==============================
D("LOW-001", "Plant XML header documents ngeom=14 while the model has 16",
  "LOW", ["DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/assets/v2_plant.xml"],
  ["v2_plant.xml:12"],
  "Header identity block matches the compiled model",
  "Header says ngeom=14; constants assert 16 (baseline 10 + 6 fall shells).",
  "XML/constants comparison.",
  {"header_ngeom": 14, "actual_ngeom": 16},
  "Documentation inconsistency only.",
  "Header not updated for fall shells.",
  "None.",
  "Identity comment is stale.",
  ["Plant XML documentary header"],
  [],
  "DOC_FIX",
  "Header-vs-model assertion test.",
  "None.",
  ["CONTACT_REVIEW.md"],
  []),

D("LOW-002", "README describes 15 bounded anatomical channels while ACTION_DIM=7",
  "LOW", ["DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["README.md"],
  ["README.md:13"],
  "Documented action dimension",
  "README says 15 channels; V2.1 has 7 (4 effective symmetric channels).",
  "Text vs candidate spec.",
  {"readme_channels": 15, "action_dim": 7},
  "Reader confusion only.",
  "README not updated across the V1->V2.1 transition.",
  "None.",
  "Documentation drift.",
  ["README.md"],
  ["MED-014"],
  "DOC_FIX",
  "Docs consistency check.",
  "None.",
  ["DOCUMENTATION review in DEFECT_REGISTER.md"],
  []),

D("LOW-003", "Stale/incorrect comments and dead branches in contact and support code",
  "LOW", ["DOCUMENTATION_DEFECT", "SOFTWARE_BUG"], "CONFIRMED",
  ["src/loaded_cmj/v2/plant.py"],
  ["plant.py:283-286 (comment 0.13/0.0475 vs code 0.150/0.060)", "plant.py:210-231 (wrong frame-convention comments and dead sys_idx branch)"],
  "Comments describe the implementation",
  "Support-half-size comment disagrees with the literals; the contact-frame comment asserts the opposite transform and a dead branch remains.",
  "Source read; verified transform behavior by contact-force vs qfrc_constraint equality.",
  {"support_half_sizes_code": [0.150, 0.060], "comment_half_sizes": [0.130, 0.0475]},
  "Maintenance hazard; readers may 'fix' correct code or copy the wrong convention.",
  "Comments left from earlier iterations.",
  "None.",
  "Documentation/robustness only.",
  ["plant.py"],
  ["HIGH-008"],
  "DOC/CLEANUP_FIX",
  "Comments-consistency review.",
  "None.",
  ["CONTACT_REVIEW.md"],
  []),

D("LOW-004", "IMPACT KD 'ramp' is an identity no-op presented as a ramp",
  "LOW", ["SOFTWARE_BUG", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/res72_integration.py"],
  ["res72_integration.py:129-134 (_impact_kd returns IMPACT_KD + (IMPACT_KD-IMPACT_KD)*ramp)"],
  "KD ramps from KD_INIT to KD_FINAL over 30 ms after touchdown",
  "KD_INIT==KD_FINAL==IMPACT_KD, so the ramp is identically zero; the constant smoothing call is dead.",
  "Source read.",
  {"kd_init": 20.0, "kd_final": 20.0},
  "None numerically; misleading code.",
  "Sealed candidate had equal init/final gains; the ramp skeleton was retained.",
  "None.",
  "None.",
  ["res72_integration.py"],
  [],
  "CLEANUP_FIX",
  "None required (or implement a real ramp).",
  "None.",
  ["CONTROL_REVIEW.md"],
  []),

D("LOW-005", "Dead code: unused y_of branch, unused unilateral_dropout_samples with misleading return, dead conditional expression",
  "LOW", ["SOFTWARE_BUG", "DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/balance_capture.py", "src/loaded_cmj/v2/support_continuity.py", "tools/res52/soft_contact.py"],
  ["balance_capture.py:52-74 (y_of unused)", "support_continuity.py:97-105 (returns array, docstring says Boolean arrays; unused)", "soft_contact.py:245 (\"FZ_SCALE_M\" if False else)"],
  "Clean minimal implementation",
  "Dead functions/expressions remain; the helper's contract docstring does not match its return.",
  "Call-site grep.",
  {"unused_y_of": True, "unilateral_helper_calls": 0},
  "Maintenance/latent misuse only.",
  "Iteration leftovers.",
  "None.",
  "None.",
  ["balance_capture.py", "support_continuity.py", "soft_contact.py"],
  [],
  "CLEANUP_FIX",
  "Dead-code check.",
  "None.",
  ["CODE_REVIEW.md"],
  []),

D("LOW-006", "WALL_S makes the canonical result JSON non-byte-deterministic",
  "LOW", ["SOFTWARE_BUG", "PROVENANCE_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/canonical_runtime.py"],
  ["canonical_runtime.py:586"],
  "Deterministic machine-readable output",
  "Wall-clock seconds are embedded in the result; byte identity of the JSON is impossible across runs.",
  "Source read; noted in the code itself.",
  {"wall_s_example": 752.18},
  "Artifact-level byte comparison requires excluding WALL_S; no scientific effect.",
  "Diagnostic convenience left in the serialized result.",
  "None.",
  "Determinism claim limited to scientific fields.",
  ["canonical result"],
  ["HIGH-013"],
  "CLEANUP_FIX (move WALL_S to sidecar)",
  "Determinism test on the scientific subset.",
  "None.",
  ["PROVENANCE_REVIEW.md"],
  ["P18-adjacent"]),

D("LOW-007", "Ankle sign comment is unresolved and geometrically inverted",
  "LOW", ["DOCUMENTATION_DEFECT"], "CONFIRMED",
  ["src/loaded_cmj/v2/constants.py"],
  ["constants.py:140-141 (comment: negative plantar, positive dorsiflex; question mark included)"],
  "Ankle sign convention documented",
  "The comment is self-questioning; with axis +y and the box forward of the ankle, positive q pitches the foot toe-down.",
  "FK/geometry probe; no numeric R001 effect.",
  {"range_rad": [-0.70, 0.50]},
  "Documentation/authority clarity only.",
  "Sign convention never closed.",
  "None.",
  "Ankle authority description unreliable.",
  ["constants.py"],
  ["LOW-003"],
  "DOC_FIX",
  "Sign test for the ankle axis.",
  "None.",
  ["CONTACT_REVIEW.md"],
  []),
]

# ---------------- Preflight adjudication ----------------
ADJ = {
 "P01": ("CONFIRMED", "CRIT-003"),
 "P02": ("CONFIRMED", "CRIT-003"),
 "P03": ("CONFIRMED", "MED-008"),
 "P04": ("CONFIRMED", "CRIT-007"),
 "P05": ("CONFIRMED", "CRIT-007"),
 "P06": ("CONFIRMED", "HIGH-010"),
 "P07": ("CONFIRMED", "HIGH-011"),
 "P08": ("CONFIRMED", "HIGH-001"),
 "P09": ("CONFIRMED", "MED-002"),
 "P10": ("CONFIRMED", "HIGH-019"),
 "P11": ("CONFIRMED", "HIGH-009"),
 "P12": ("CONFIRMED", "HIGH-008"),
 "P13": ("CONFIRMED", "MED-005"),
 "P14": ("CONFIRMED", "HIGH-002"),
 "P15": ("CONFIRMED", "HIGH-004"),
 "P16": ("CONFIRMED", "HIGH-004"),
 "P17": ("CONFIRMED", "MED-004"),
 "P18": ("CONFIRMED", "MED-003"),
 "P19": ("CONFIRMED", "HIGH-005"),
 "P20": ("CONFIRMED", "HIGH-006"),
 "P21": ("CONFIRMED", "HIGH-014"),
 "P22": ("CONFIRMED", "HIGH-014"),
 "P23": ("CONFIRMED", "HIGH-003"),
 "P24": ("CONFIRMED", "MED-009"),
 "P25": ("CONFIRMED", "CRIT-005"),
 "P26": ("CONFIRMED", "HIGH-007"),
 "P27": ("CONFIRMED", "HIGH-013"),
 "P28": ("CONFIRMED", "MED-011"),
 "P29": ("CONFIRMED", "MED-001"),
 "P30": ("CONFIRMED", "MED-007"),
 "P31": ("REJECTED", "LOW-003"),
 "P32": ("CONFIRMED", "CRIT-006"),
 "P33": ("CONFIRMED", "CRIT-006"),
 "P34": ("CONFIRMED", "MED-016"),
 "P35": ("CONFIRMED", "MED-014"),
 "P36": ("CONFIRMED", "HIGH-012"),
 "P37": ("CONFIRMED", "MED-010"),
 "P38": ("CONFIRMED", "MED-017"),
 "P39": ("CONFIRMED", "MED-021 (registered as part of HIGH-006 action-program issue)" ),
 "P40": ("CONFIRMED", "MED-011"),
 "P41": ("CONFIRMED", "MED-011"),
 "P42": ("CONFIRMED", "HIGH-015"),
 "P43": ("CONFIRMED", "CRIT-003"),
 "P44": ("CONFIRMED", "CRIT-003"),
 "P45": ("CONFIRMED", "CLAIM_CEILING.md; render non-invasiveness independently re-verified from RES-79 gates"),
}

# override P39 cleanly
ADJ["P39"] = ("CONFIRMED", "HIGH-006")

NEW_FINDINGS = [
 ["CRIT-002", "Hip range/convention inversion (not in P-list)"],
 ["HIGH-012", "Envelope overfit quantified to micron-scale windows (P36 framing sharpened)"],
 ["HIGH-013", "Canonical output violates its own required schema fields (beyond P27)"],
 ["MED-012", "SUPPORT_FULL NOT_QUALIFIED vs sliced gates (new)"],
 ["MED-013", "E12 fires 50.8 ms before RES-43 handoff (new)"],
 ["MED-015", "Entry-head fragmentation and corrupted ledger hash (new)"],
 ["HIGH-011", "Apex fallback path without flight check (new sub-mechanism under P07)"],
 ["MED-020", "E1 supported-start omits fall_contact (new)"],
 ["MED-006", "prohibited_contact is structurally dead (new sub-mechanism under P30)"],
 ["MED-007", "20 kg load has no collision geometry at all; foot-shank ~6 mm fragility (new)"],
 ["MED-017", "Adjudication/checkpoint exceptions become sentinel values (new)"],
 ["MED-018", "Duplicated authority literals across dead mirror and external JSON (new)"],
 ["MED-019", "V2.1-named tests drive the legacy controller (new)"],
 ["LOW-004", "KD ramp is an identity no-op (new)"],
 ["LOW-005", "Dead code + misleading helper contract (new)"],
 ["LOW-006", "WALL_S breaks result byte-determinism (new)"],
 ["LOW-007", "Ankle sign comment inverted (new)"],
]

# ---------------- emit ----------------
sev_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
type_counts = {}
for d in DEFECTS:
    sev_counts[d["SEVERITY"]] += 1
    for t in d["TYPE"]:
        type_counts[t] = type_counts.get(t, 0) + 1

register = {
    "MISSION": "V2_1_POST_RENDER_FULL_SYSTEM_FORENSIC_AUDIT_001",
    "LINEAR_ISSUE": "RES-80",
    "BASELINE_HEAD": "8f26736db1231042cbedc61f61ca4862b7be871c",
    "BASELINE_TREE": "855fe3b418c09b5028396adeaed3ba8cda51e89f",
    "CANDIDATE_ID": "V2.1-R001",
    "DEFECT_COUNTS_BY_SEVERITY": sev_counts,
    "DEFECT_COUNTS_BY_TYPE": type_counts,
    "DEFECTS": DEFECTS,
}
(OUT / "DEFECT_REGISTER.json").write_text(json.dumps(register, indent=2, sort_keys=False) + "\n")

adjudication = {
    "MISSION": "V2_1_POST_RENDER_FULL_SYSTEM_FORENSIC_AUDIT_001",
    "PROVISIONAL_FINDINGS": [
        {"ID": k, "STATUS": v[0], "LINKED_DEFECT": v[1]} for k, v in ADJ.items()
    ],
    "COUNTS": {
        "CONFIRMED": sum(1 for v in ADJ.values() if v[0] == "CONFIRMED"),
        "REJECTED": sum(1 for v in ADJ.values() if v[0] == "REJECTED"),
        "LIMITATION": sum(1 for v in ADJ.values() if v[0] == "LIMITATION"),
        "NEEDS_MORE_EVIDENCE": sum(1 for v in ADJ.values() if v[0] == "NEEDS_MORE_EVIDENCE"),
    },
    "NEW_FINDINGS_BEYOND_PREFLIGHT": NEW_FINDINGS,
    "NOTE": "P31 rejected as an active defect: frame.T @ sign*force matched qfrc_constraint on non-identity contact frames and both geom orderings; the code comments are wrong/fragile (LOW-003) but the implementation is correct for MuJoCo 3.8.0.",
}
(OUT / "PROVISIONAL_FINDING_ADJUDICATION.json").write_text(json.dumps(adjudication, indent=2) + "\n")

# markdown
lines = ["# RES-80 Defect Register (V2.1 post-render full-system forensic audit)", ""]
lines.append(f"Baseline `{register['BASELINE_HEAD']}` / tree `{register['BASELINE_TREE']}`, candidate `V2.1-R001`, audit-only (no fixes).")
lines.append("")
lines.append("## Counts")
lines.append("")
lines.append("| Severity | Count |")
lines.append("|---|---|")
for k in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
    lines.append(f"| {k} | {sev_counts[k]} |")
lines.append("")
lines.append("| Type | Count (multi-label) |")
lines.append("|---|---|")
for k in sorted(type_counts):
    lines.append(f"| {k} | {type_counts[k]} |")
lines.append("")
lines.append("## Index")
lines.append("")
lines.append("| ID | Severity | Title | Type | Status |")
lines.append("|---|---|---|---|---|")
for d in DEFECTS:
    lines.append(f"| {d['ID']} | {d['SEVERITY']} | {d['TITLE']} | {', '.join(d['TYPE'])} | {d['STATUS']} |")
lines.append("")
for d in DEFECTS:
    lines.append(f"## {d['ID']} — {d['TITLE']}")
    lines.append("")
    lines.append(f"- **SEVERITY**: {d['SEVERITY']}")
    lines.append(f"- **TYPE**: {', '.join(d['TYPE'])}")
    lines.append(f"- **STATUS**: {d['STATUS']}")
    lines.append(f"- **FILE**: {', '.join(d['FILE'])}")
    lines.append(f"- **LINE_OR_FUNCTION**: {'; '.join(d['LINE_OR_FUNCTION'])}")
    lines.append(f"- **DECLARED_BEHAVIOR**: {d['DECLARED_BEHAVIOR']}")
    lines.append(f"- **IMPLEMENTED_BEHAVIOR**: {d['IMPLEMENTED_BEHAVIOR']}")
    lines.append(f"- **REPRODUCTION_OR_PROOF**: {d['REPRODUCTION_OR_PROOF']}")
    lines.append(f"- **NUMERIC_EVIDENCE**: `{json.dumps(d['NUMERIC_EVIDENCE'], sort_keys=True)}`")
    lines.append(f"- **OBSERVED_EFFECT**: {d['OBSERVED_EFFECT']}")
    lines.append(f"- **ROOT_CAUSE**: {d['ROOT_CAUSE']}")
    lines.append(f"- **R001_IMPACT**: {d['R001_IMPACT']}")
    lines.append(f"- **SCIENTIFIC_CLAIM_IMPACT**: {d['SCIENTIFIC_CLAIM_IMPACT']}")
    lines.append(f"- **AUTHORITY_INVALIDATED_OR_LIMITED**: {', '.join(d['AUTHORITY_INVALIDATED_OR_LIMITED'])}")
    lines.append(f"- **DEPENDENCIES**: {', '.join(d['DEPENDENCIES'])}")
    lines.append(f"- **FIX_CLASS**: {d['FIX_CLASS']}")
    lines.append(f"- **REQUIRED_REGRESSION_TEST**: {d['REQUIRED_REGRESSION_TEST']}")
    lines.append(f"- **REQUALIFICATION_SCOPE**: {d['REQUALIFICATION_SCOPE']}")
    lines.append(f"- **EVIDENCE_POINTERS**: {', '.join(d['EVIDENCE_POINTERS'])}")
    if d["PREFLIGHT_REFERENCES"]:
        lines.append(f"- **PREFLIGHT_REFERENCES**: {', '.join(d['PREFLIGHT_REFERENCES'])}")
    lines.append("")
(OUT / "DEFECT_REGISTER.md").write_text("\n".join(lines) + "\n")

print("severity:", sev_counts)
print("types:", type_counts)
print("defects:", len(DEFECTS))
print("adjudication:", adjudication["COUNTS"])
