#!/usr/bin/env python3
"""Build SCIENTIFIC_CONTRACT_EVIDENCE_TABLE.csv/.md for RES-82.

Read-only generator. Each row records provenance for contract decisions.
No numerical threshold may enter the contract without a provenance row.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent

FIELDS = [
    "SOURCE_ID", "FULL_CITATION", "DOI_PMID_OR_STANDARD", "SOURCE_TYPE", "POPULATION",
    "TASK", "LOAD", "MEASUREMENT_SYSTEM", "VARIABLE", "DEFINITION", "THRESHOLD_IF_ANY",
    "METHOD", "UNCERTAINTY_OR_RELIABILITY", "APPLICABILITY_TO_OUR_TASK", "LIMITATIONS",
    "DIRECTLY_SUPPORTS_NUMERIC_GATE", "NOTES",
]

ROWS = [
    {
        "SOURCE_ID": "S01",
        "FULL_CITATION": "Eythorsdottir I, Gloersen O, Rice H, Werkhausen A, Ettema G, Mentzoni F, Solberg P, Lindberg K, Paulsen G. The Battle of the Equations: A Systematic Review of Jump Height Calculations Using Force Platforms. Sports Medicine 2024;54(11):2771-2791.",
        "DOI_PMID_OR_STANDARD": "PMID 39425876; DOI 10.1007/s40279-024-02098-x",
        "SOURCE_TYPE": "Systematic review",
        "POPULATION": "Healthy participants across CMJ/SJ/DJ/loaded-jump studies",
        "TASK": "Vertical jump testing on force platforms",
        "LOAD": "Includes loaded jumps",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Jump height equation families",
        "DEFINITION": "Four commonly used equations in two families: two defined from takeoff, two from standing",
        "THRESHOLD_IF_ANY": "No threshold; equation choice can change jump height by up to ~15 cm on the same jump",
        "METHOD": "PRISMA systematic review; 16 included papers",
        "UNCERTAINTY_OR_RELIABILITY": "Reported variation up to ~15 cm across equations",
        "APPLICABILITY_TO_OUR_TASK": "High for definitional structure: qualifies jump-height names and supports the method-qualified naming rule",
        "LIMITATIONS": "Human force-platform processing; does not define a simulation-truth displacement and provides no task floor",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Basis for PRIMARY_CANONICAL_JUMP_HEIGHT adjudication and the prohibition of unqualified 'jump height'",
    },
    {
        "SOURCE_ID": "S02",
        "FULL_CITATION": "Eythorsdottir I, Gloersen O, Rice H, Werkhausen A, Ettema G, Solberg P, Paulsen G. Navigating the Data Processing Maze: A Systematic Review of Jump Height Calculations Using Force Platforms. European Journal of Sport Science 2026;26(1).",
        "DOI_PMID_OR_STANDARD": "PMID 41672931; DOI 10.1002/ejsc.70114 (Europe PMC DOI resolution confirmed 2026-09-13; see citation_resolution.json)",
        "SOURCE_TYPE": "Systematic review",
        "POPULATION": "Healthy participants, force-platform vertical jump testing",
        "TASK": "Data processing for jump height",
        "LOAD": "Not specific",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Processing steps: sampling, filtering, averaging, integration, take-off threshold, gravity constant",
        "DEFINITION": "Effect of each processing decision on jump-height estimate",
        "THRESHOLD_IF_ANY": "Effects from <0.5% to >25%",
        "METHOD": "Systematic review",
        "UNCERTAINTY_OR_RELIABILITY": "Up to 26% change from filtering alone",
        "APPLICABILITY_TO_OUR_TASK": "Justifies preferring direct model-truth COM displacement (processing-independent) as primary and treating force-derived quantities as comparability metrics",
        "LIMITATIONS": "No absolute thresholds; human processing focus",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Supports CG-05/CG-06 diagnostics and compare-with-caution rules",
    },
    {
        "SOURCE_ID": "S03",
        "FULL_CITATION": "Xu J, Turner A, Comfort P, Harry JR, McMahon JJ, Chavda S, Bishop C. A Systematic Review of the Different Calculation Methods for Measuring Jump Height During the Countermovement and Drop Jump Tests. Sports Medicine 2023;53(5):1055-1072.",
        "DOI_PMID_OR_STANDARD": "PMID 36940054; DOI 10.1007/s40279-023-01828-x",
        "SOURCE_TYPE": "Systematic review",
        "POPULATION": "Healthy adults",
        "TASK": "CMJ and drop jump",
        "LOAD": "Unloaded predominantly",
        "MEASUREMENT_SYSTEM": "Force platform, motion capture, jump mats",
        "VARIABLE": "Jump-height calculation methods (IM, FT, double integration, jump-and-reach)",
        "DEFINITION": "Method-specific COM-height definitions",
        "THRESHOLD_IF_ANY": "None",
        "METHOD": "Systematic review, 21 articles, quality scoring",
        "UNCERTAINTY_OR_RELIABILITY": "Impulse-momentum preferred for takeoff-to-apex; double integration preferred for standing-to-apex",
        "APPLICABILITY_TO_OUR_TASK": "Direct support for choosing direct takeoff-to-apex displacement as primary and reporting standing-to-apex as context",
        "LIMITATIONS": "Human methods; no simulation COU",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Method recommendation corroborates the primary/cross-check split",
    },
    {
        "SOURCE_ID": "S04",
        "FULL_CITATION": "Smith JC, Lamont HS, Barefoot M. Comparison of Different Take-off Thresholds When Assessing Vertical Jump Performance. International Journal of Exercise Science 2024;17(1):660-668.",
        "DOI_PMID_OR_STANDARD": "PMID 38863789; DOI 10.70252/QBUA4521 (Europe PMC resolution confirmed 2026-09-13; see citation_resolution.json)",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "21 participants, CMJ",
        "TASK": "Countermovement vertical jump",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Take-off thresholds (20, 10, 5, 1 N, 5SD, PkRes) vs JH, MT, RSImod, netIMP, prIMP",
        "DEFINITION": "Take-off = force crossing the declared threshold",
        "THRESHOLD_IF_ANY": "Thresholds tested: 20 N, 10 N, 5 N, 1 N, 5SD, PkRes",
        "METHOD": "Repeated measures; ICC and CV",
        "UNCERTAINTY_OR_RELIABILITY": "ICC >= 0.835; CV < 10%; differences trivial by effect size but statistically significant",
        "APPLICABILITY_TO_OUR_TASK": "Establishes that force-threshold choice is a declared comparability convention; supports reporting threshold sensitivity; does not justify using a threshold as physical truth in simulation",
        "LIMITATIONS": "Human signal noise context; threshold selection matched to PkRes; not a simulation contact-truth study",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "F_thr candidate 10 N is a comparability convention (OD-09); sensitivity set {1,5,10,20 N, noise} required",
    },
    {
        "SOURCE_ID": "S05",
        "FULL_CITATION": "Barefoot M, Lamont H, Smith JC. Comparison of the Reliability of Four Different Movement Thresholds When Evaluating Vertical Jump Performance. Sports (Basel) 2022;10(12):193.",
        "DOI_PMID_OR_STANDARD": "PMID 36548490; DOI 10.3390/sports10120193",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "21 college-aged participants",
        "TASK": "CMJ and SJ",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Movement-initiation thresholds (5SD, 4SD, 2.5%SW, 10%SW)",
        "DEFINITION": "Movement onset as force deviation from baseline",
        "THRESHOLD_IF_ANY": "5SD, 4SD, 2.5%SW, 10%SW",
        "METHOD": "Repeated measures reliability",
        "UNCERTAINTY_OR_RELIABILITY": "Reliability varies by threshold and variable",
        "APPLICABILITY_TO_OUR_TASK": "Informs countermovement-onset measurement alternatives; supports declaring onset thresholds rather than assuming one",
        "LIMITATIONS": "Unloaded; initiation only",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "E2 onset uses COM-vz (model truth); force-deviation onset remains an experimental comparability option",
    },
    {
        "SOURCE_ID": "S06",
        "FULL_CITATION": "Perez-Castilla A, Rojas FJ, Garcia-Ramos A. Reliability and magnitude of loaded countermovement jump performance variables: a technical examination of the jump threshold initiation. Sports Biomechanics 2022;21(5):622-636.",
        "DOI_PMID_OR_STANDARD": "PMID 31711369; DOI 10.1080/14763141.2019.1682649",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "17 males",
        "TASK": "Loaded CMJ (17-30-45-60-75 kg)",
        "LOAD": "Loaded (17-75 kg)",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Starting threshold effects on reliability/magnitude of loaded-CMJ variables",
        "DEFINITION": "Initiation = first instant vGRF falls below system weight by 10 N, 50 N, 1%SW, 10%SW, 5SDSW",
        "THRESHOLD_IF_ANY": "10 N, 50 N, 1%SW, 10%SW, 5SDSW minus 30 ms",
        "METHOD": "Two sessions, five loads, CV/ICC comparisons",
        "UNCERTAINTY_OR_RELIABILITY": "50 N, 10%SW, 5SDSW more reliable than 10 N and 1%SW especially eccentric-phase variables",
        "APPLICABILITY_TO_OUR_TASK": "Direct loaded-CMJ threshold evidence: the loaded condition changes which temporal variables are sensitive to threshold choice; supports declaring the convention and reporting sensitivity",
        "LIMITATIONS": "Human force signal; no physical-truth contact geometry; not a task-success contract",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Seeded reference verified; magnitudes differ significantly across thresholds, reinforcing comparability-only status",
    },
    {
        "SOURCE_ID": "S07",
        "FULL_CITATION": "Garcia-Ramos A, Jaric S, Perez-Castilla A, Padial P, Feriche B. Reliability and magnitude of mechanical variables assessed from unconstrained and constrained loaded countermovement jumps. Sports Biomechanics 2017;16(4):514-526.",
        "DOI_PMID_OR_STANDARD": "PMID 28632047; DOI 10.1080/14763141.2016.1246598",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "Trained participants",
        "TASK": "Loaded CMJ constrained vs unconstrained",
        "LOAD": "Loaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Mechanical variables reliability/magnitude",
        "DEFINITION": "Loaded-jump variable set",
        "THRESHOLD_IF_ANY": "None",
        "METHOD": "Reliability study",
        "UNCERTAINTY_OR_RELIABILITY": "Variable-dependent",
        "APPLICABILITY_TO_OUR_TASK": "Supports treating loaded-CMJ metrics as measurement-dependent and declaring definitions precisely",
        "LIMITATIONS": "Human; no simulation",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Context for metric-definition rigor",
    },
    {
        "SOURCE_ID": "S08",
        "FULL_CITATION": "Kraska JM, Ramsey MW, Haff GG, Fethke N, Sands WA, Stone ME, Stone MH. Relationship between strength characteristics and unweighted and weighted vertical jump height. International Journal of Sports Physiology and Performance 2009;4(4):461-473.",
        "DOI_PMID_OR_STANDARD": "PMID 20029097; DOI 10.1123/ijspp.4.4.461",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "63 collegiate athletes (19.9 +/- 1.3 y; 72.9 +/- 19.6 kg)",
        "TASK": "SJ and CMJ at 0 kg and 20 kg",
        "LOAD": "0 kg and 20 kg external",
        "MEASUREMENT_SYSTEM": "Force platform; jump height from flight time",
        "VARIABLE": "CMJ jump height 0 kg vs 20 kg; percent decrease",
        "DEFINITION": "Flight-time jump height for CMJ with/without 20 kg",
        "THRESHOLD_IF_ANY": "0 kg CMJ group means: strong 33.53 +/- 10.75 cm, weak 28.27 +/- 6.34 cm; 20 kg CMJ strong group 27.57 +/- 8.64 cm; 20 kg weak-stratum mean NOT directly reported; SJ percent decrease with 20 kg: strong 17.79 +/- 3.44% vs weak 30.40 +/- 7.8% (basis for the derived weak-stratum estimate)",
        "METHOD": "Force-plate testing, flight-time JH, isometric strength correlations",
        "UNCERTAINTY_OR_RELIABILITY": "SDs reported; flight-time method carries assumed symmetric takeoff/landing posture",
        "APPLICABILITY_TO_OUR_TASK": "Primary evidence that a 20 kg loaded CMJ by adult male athletes is a 20-30 cm-scale movement; the weak-stratum 20 kg mean is derived (not reported) as ~19-20 cm by applying the weak group SJ decrease to its 0 kg mean; supports PF-1 (0.15 m) as a conservative task-plausibility bound with a disclosed cross-family (flight-time vs direct-COM) limitation",
        "LIMITATIONS": "Flight-time method; collegiate athletes not a general population; no direct COM displacement; load was a 20 kg bar in trained subjects",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "YES",
        "NOTES": "PF-1 candidate floor anchor (OD-01). The floor is a task definition, not a population percentile. Weak-stratum 20 kg value derived, not reported (independent review OF-1)",
    },
    {
        "SOURCE_ID": "S09",
        "FULL_CITATION": "Leontijevic B, Pazin N, Bozic PR, Kukolj M, Ugarkovic D, Jaric S. Effects of loading on maximum vertical jumps: selective effects of weight and inertia. Journal of Electromyography and Kinesiology 2012;22(2):286-293.",
        "DOI_PMID_OR_STANDARD": "PMID 22209596; DOI 10.1016/j.jelekin.2011.12.002",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "15 male college students",
        "TASK": "Maximum CMJ with arm swing",
        "LOAD": "10-40% body mass as weight, weight+inertia, inertia",
        "MEASUREMENT_SYSTEM": "Force platform + pulley/vest loading",
        "VARIABLE": "Jumping performance (peak velocity) and GRF vs load type/magnitude",
        "DEFINITION": "Selective W / W+I / I loading effects",
        "THRESHOLD_IF_ANY": "10-40% body mass range",
        "METHOD": "Two-way repeated measures ANOVA",
        "UNCERTAINTY_OR_RELIABILITY": "Reliability previously established high across loads",
        "APPLICABILITY_TO_OUR_TASK": "Supports the expectation that a 20 kg load reduces jump performance but preserves the CMJ pattern at these relative loads; the load is 21% of system mass in our task",
        "LIMITATIONS": "Peak velocity not jump height; arm swing; healthy active non-athletes",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Context for performance-floor plausibility and loaded-task interpretation",
    },
    {
        "SOURCE_ID": "S10",
        "FULL_CITATION": "McErlain-Naylor S, King M, Pain MTG. Determinants of countermovement jump performance: a kinetic and kinematic analysis. Journal of Sports Sciences 2014;32(19):1805-1812.",
        "DOI_PMID_OR_STANDARD": "PMID 24875041; DOI 10.1080/02640414.2014.924055",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "18 males of varying jumping experience",
        "TASK": "CMJ",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "2-D motion capture + force platform",
        "VARIABLE": "CMJ height and technique determinants",
        "DEFINITION": "CMJ height range and predictors",
        "THRESHOLD_IF_ANY": "CMJ height range 0.38-0.73 m; mean 0.55 +/- 0.09 m",
        "METHOD": "Kinetic/kinematic regression",
        "UNCERTAINTY_OR_RELIABILITY": "Variation across participants",
        "APPLICABILITY_TO_OUR_TASK": "Context only: unloaded adult male CMJ magnitudes bracket the expected loaded deformation of performance",
        "LIMITATIONS": "Unloaded; wide range; not loaded athletes",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Context only for PF-1; NO numeric gate value is taken from this source (corrected by independent literature review OF-2)",
    },
    {
        "SOURCE_ID": "S11",
        "FULL_CITATION": "Kyne H, Cronin JB. Beyond Jump Height: A Comparison of Concentric Variables in the Squat Jump, Countermovement Jump and Drop Jump for Athletic Profiling. Sports (Basel) 2025;13(11):379.",
        "DOI_PMID_OR_STANDARD": "PMID 41295762; DOI 10.3390/sports13110379",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "23 male athletes (18.1 +/- 0.7 y)",
        "TASK": "SJ, CMJ, DJ",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Jump height across jump types",
        "DEFINITION": "CMJ height 37.8 +/- 4.1 cm; SJ 34.6 +/- 4.4; DJ 31.9 +/- 5.0",
        "THRESHOLD_IF_ANY": "None",
        "METHOD": "Within-subject comparison",
        "UNCERTAINTY_OR_RELIABILITY": "SDs reported",
        "APPLICABILITY_TO_OUR_TASK": "Corroborates CMJ magnitude scale in young male athletes",
        "LIMITATIONS": "Unloaded; small sample",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Corroborative context for PF-1",
    },
    {
        "SOURCE_ID": "S12",
        "FULL_CITATION": "Cabarkapa D, Smith R, Chowning L, Neltner T, Johnson QR, Yang Y, Munce TA. Reliability of Vertical Jump Force-Time Metrics in Collegiate Athletes Compared to Recreationally Active Individuals. Life (Basel) 2025;15(12):1830.",
        "DOI_PMID_OR_STANDARD": "PMID 41465769; DOI 10.3390/life15121830",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "39 NCAA D-I athletes and 35 non-athletes",
        "TASK": "CMJ without arm swing",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Portable dual force plate, 1000 Hz",
        "VARIABLE": "Reliability of force-time metrics incl. jump height, countermovement depth, peak landing force",
        "DEFINITION": "Jump height 38.6 +/- 9.9 cm; countermovement depth 32.5 +/- 7.1 cm; peak landing force 4149-4474 N; SEM/MDC reported (jump height SEM 0.91 cm; depth SEM 1.73 cm)",
        "THRESHOLD_IF_ANY": "Reliability classes: CV < 10%, ICC > 0.750 good-excellent",
        "METHOD": "Test-retest reliability",
        "UNCERTAINTY_OR_RELIABILITY": "SEM/MDC reported for key metrics",
        "APPLICABILITY_TO_OUR_TASK": "Provides measurement uncertainty context for performance and landing quantities; supports required reporting of SEM/MDC-like sensitivity in later RES",
        "LIMITATIONS": "Unloaded; portable system; healthy participants",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Context for measurement realism; countermovement depth in humans is far larger than the current 0.10 m candidate (OD-07 deferred)",
    },
    {
        "SOURCE_ID": "S13",
        "FULL_CITATION": "Anicic Z, Janicijevic D, Knezevic OM, Garcia-Ramos A, Petrovic MR, Cabarkapa D, Mirkov DM. Assessment of Countermovement Jump: What Should We Report? Life (Basel) 2023;13(1):190.",
        "DOI_PMID_OR_STANDARD": "PMID 36676138; DOI 10.3390/life13010190",
        "SOURCE_TYPE": "Primary experimental study / methodological",
        "POPULATION": "79 physically active participants",
        "TASK": "CMJ",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "45 CMJ metrics reliability; PCA factors",
        "DEFINITION": "Reliable metric set (CV <= 10%)",
        "THRESHOLD_IF_ANY": "CV <= 10% acceptance; 24 of 45 metrics acceptable; performance CV 4.2-11.1%",
        "METHOD": "Test-retest + PCA",
        "UNCERTAINTY_OR_RELIABILITY": "Reported per metric",
        "APPLICABILITY_TO_OUR_TASK": "Supports disciplined metric selection and retention; performance metrics are the most reliable class; informs canonical schema discipline",
        "LIMITATIONS": "Unloaded; human measurement noise",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Supports HIGH-013 closure (retain all required metrics)",
    },
    {
        "SOURCE_ID": "S14",
        "FULL_CITATION": "Merrigan JJ, Strang A, Eckerle J, Mackowski N, Hierholzer K, Ray NT, Smith R, Hagen JA, Briggs RA. Countermovement Jump Force-Time Curve Analyses: Reliability and Comparability Across Force Plate Systems. Journal of Strength and Conditioning Research 2024;38(1):30-37.",
        "DOI_PMID_OR_STANDARD": "PMID 37815253; DOI 10.1519/JSC.0000000000004586",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "22 subjects",
        "TASK": "CMJ across three commercial systems",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "ForceDecks, Hawkin Dynamics, Sparta Science",
        "VARIABLE": "Cross-system agreement: jump height, impulses, RFD, mRSI",
        "DEFINITION": "Metric definitions differ across systems",
        "THRESHOLD_IF_ANY": "CCC 0.85-0.95 for jump height; poor test-retest for mRSI/RFD",
        "METHOD": "Cross-system agreement",
        "UNCERTAINTY_OR_RELIABILITY": "Systematic/proportionate bias for some metrics",
        "APPLICABILITY_TO_OUR_TASK": "Justifies declaring one metric definition per quantity and forbidding cross-definition comparisons",
        "LIMITATIONS": "Commercial systems; human",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Supports naming/method-qualifier discipline",
    },
    {
        "SOURCE_ID": "S15",
        "FULL_CITATION": "Niu W, Feng T, Jiang C, Zhang M. Peak vertical ground reaction force during two-leg landing: a systematic review and mathematical modeling. BioMed Research International 2014;2014:126860.",
        "DOI_PMID_OR_STANDARD": "PMID 25243113; DOI 10.1155/2014/126860",
        "SOURCE_TYPE": "Systematic review + modeling",
        "POPULATION": "26 pooled studies",
        "TASK": "Two-leg drop landing",
        "LOAD": "Drop heights",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Peak vGRF vs drop height",
        "DEFINITION": "Square-root relation between pooled peak vGRF and drop height",
        "THRESHOLD_IF_ANY": "No task threshold; conveys landing-force scale and drop-height dependence",
        "METHOD": "Systematic review + regression modeling",
        "UNCERTAINTY_OR_RELIABILITY": "Pooled across studies; moderators (sex, surface, shoes, frequency)",
        "APPLICABILITY_TO_OUR_TASK": "Landing force is a meaningful physical quantity scaled by drop height; supports keeping peak Fz / BW and loading-rate as diagnostic/layer metrics rather than primary task gates",
        "LIMITATIONS": "Drop landing from box heights differs from CMJ landing; no CMJ-specific threshold",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "L4-G6 8 BW retained as project historical hard rule, not from this source",
    },
    {
        "SOURCE_ID": "S16",
        "FULL_CITATION": "Davis DJ, Hinshaw TJ, Critchley ML, Dai B. Mid-flight trunk flexion and extension altered segment and lower extremity joint movements and subsequent landing mechanics. Journal of Science and Medicine in Sport 2019;22(8):955-961.",
        "DOI_PMID_OR_STANDARD": "PMID 30902539; DOI 10.1016/j.jsams.2019.03.001",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "41 participants",
        "TASK": "Jump-landing with mid-flight trunk motion (reach forward/up/back)",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Whole-body kinematics + force platform",
        "VARIABLE": "Trunk/pelvis/leg COM positions and joint kinematics at initial contact and 100 ms after",
        "DEFINITION": "Mid-flight trunk posture changes landing hip/knee/ankle configuration and moments",
        "THRESHOLD_IF_ANY": "No threshold; direction-dependent effects",
        "METHOD": "Randomized within-subject",
        "UNCERTAINTY_OR_RELIABILITY": "Group-level effects",
        "APPLICABILITY_TO_OUR_TASK": "Establishes trunk-pelvis-lower-limb coupling: landing capture cannot be defined by COM vertical velocity alone; supports whole-body landing gates (HIGH-001)",
        "LIMITATIONS": "Unloaded jump-landing; not a loaded bilateral CMJ; no numeric bounds transferable",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Mission seed cited as 'Dai et al.'; verified first author is Davis DJ, senior author Dai B",
    },
    {
        "SOURCE_ID": "S17",
        "FULL_CITATION": "Blackburn JT, Padua DA. Influence of trunk flexion on hip and knee joint kinematics during a controlled drop landing. Clinical Biomechanics 2008;23(3):313-319.",
        "DOI_PMID_OR_STANDARD": "PMID 18037546; DOI 10.1016/j.clinbiomech.2007.10.003",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "40 healthy individuals",
        "TASK": "Drop landing, preferred vs actively flexed trunk",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Motion capture",
        "VARIABLE": "Trunk, hip, knee flexion kinematics",
        "DEFINITION": "Peak trunk flexion 47 deg greater in flexed condition, with +31 deg hip flexion and +22 deg knee flexion",
        "THRESHOLD_IF_ANY": "No threshold",
        "METHOD": "Within-subject",
        "UNCERTAINTY_OR_RELIABILITY": "p < 0.001 for reported comparisons",
        "APPLICABILITY_TO_OUR_TASK": "Trunk flexion is coupled to hip/knee flexion and is a normal/beneficial landing strategy; therefore L4 trunk-pitch bounds must not criminalize flexion per se; the defect is uncaptured forward translation/rotation",
        "LIMITATIONS": "Drop landing; no load; kinematic coupling only",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Shapes L4-T5 rationale",
    },
    {
        "SOURCE_ID": "S18",
        "FULL_CITATION": "Blackburn JT, Padua DA. Sagittal-plane trunk position, landing forces, and quadriceps electromyographic activity. Journal of Athletic Training 2009;44(2):174-179.",
        "DOI_PMID_OR_STANDARD": "PMID 19295962; DOI 10.4085/1062-6050-44.2.174",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "40 healthy volunteers (20 men, 20 women)",
        "TASK": "Drop landing preferred vs flexed trunk",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform + EMG",
        "VARIABLE": "Peak vertical/posterior GRF and quadriceps EMG",
        "DEFINITION": "Trunk flexion decreases vGRF and quadriceps activity",
        "THRESHOLD_IF_ANY": "No threshold",
        "METHOD": "2x2 repeated measures",
        "UNCERTAINTY_OR_RELIABILITY": "p < 0.001; no sex interaction",
        "APPLICABILITY_TO_OUR_TASK": "Landing posture affects load magnitude; supports treating trunk posture as a task variable with bounds not derived from ACL-risk claims",
        "LIMITATIONS": "Unloaded drop landing; no numeric bounds",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "L4-T5 context; no clinical threshold import",
    },
    {
        "SOURCE_ID": "S19",
        "FULL_CITATION": "Chen Y, Zheng S, Yu L, Xue X, Wang Z, Sun Y, Hua Y. Assessment of Landing Stability in Patients After Anterior Cruciate Ligament Injury and Reconstruction: A Systematic Review and Meta-analysis. Sports Health 2026;18(1).",
        "DOI_PMID_OR_STANDARD": "PMID 41017646; DOI 10.1177/19417381251372976",
        "SOURCE_TYPE": "Systematic review / meta-analysis (Level 4)",
        "POPULATION": "ACLI/ACLR patients vs controls (11 studies)",
        "TASK": "Jump-landing stabilization",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "TTS and DPSI methods and group differences",
        "DEFINITION": "TTS = time to return within a stabilization band; DPSI = normalized GRF variance over post-impact window",
        "THRESHOLD_IF_ANY": "No universal threshold; method parameters vary across studies",
        "METHOD": "Systematic review + meta-analysis",
        "UNCERTAINTY_OR_RELIABILITY": "AP SMD 0.438; vertical SMD 0.656 for ACLI/ACLR vs controls",
        "APPLICABILITY_TO_OUR_TASK": "Informs capture structure (sustained window, directional components, relative-to-quiet-stance logic); clinical thresholds are NOT transferred to this simulation COU",
        "LIMITATIONS": "Patient populations; single-leg/hop tasks; heterogeneity; not a deterministic simulation",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Seeded review verified",
    },
    {
        "SOURCE_ID": "S20",
        "FULL_CITATION": "Ross SE, Guskiewicz KM, Yu B. Single-leg jump-landing stabilization times in subjects with functionally unstable ankles. Journal of Athletic Training 2005;40(4):298-304.",
        "DOI_PMID_OR_STANDARD": "PMID 16404451",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "10 FAI, 10 stable, 12 reliability subjects",
        "TASK": "Single-leg jump landing at 50-55% max jump height",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Time to stabilization (AP, ML)",
        "DEFINITION": "TTS from GRF range-of-variation window",
        "THRESHOLD_IF_ANY": "TTS healthy 1.45 +/- 0.30 s vs FAI 1.98 +/- 0.81 s; SEM 0.15-0.26 s",
        "METHOD": "Mixed design + reliability",
        "UNCERTAINTY_OR_RELIABILITY": "ICC 0.65-0.79",
        "APPLICABILITY_TO_OUR_TASK": "TTS semantics: stabilization is defined over a sustained GRF band; supports sustained capture windows in E11",
        "LIMITATIONS": "Single-leg; clinical populations; not transferable numerically",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Structure only",
    },
    {
        "SOURCE_ID": "S21",
        "FULL_CITATION": "Wikstrom EA, Tillman MD, Chmielewski TL, Cauraugh JH, Borsa PA. Dynamic postural stability deficits in subjects with self-reported ankle instability. Medicine & Science in Sports & Exercise 2007;39(3):397-402.",
        "DOI_PMID_OR_STANDARD": "PMID 17473764; DOI 10.1249/mss.0b013e31802d3460",
        "SOURCE_TYPE": "Primary experimental study",
        "POPULATION": "108 subjects (54 FAI, 54 stable)",
        "TASK": "Single-leg-hop stabilization",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "DPSI and directional stability indices",
        "DEFINITION": "Normalized RMS GRF fluctuation over 3 s post-impact",
        "THRESHOLD_IF_ANY": "Reported group means (e.g., composite DPSI stable 0.006 +/- 0.001 vs FAI 0.008 +/- 0.003)",
        "METHOD": "Case-control",
        "UNCERTAINTY_OR_RELIABILITY": "ICC 0.97-0.99 for several indices",
        "APPLICABILITY_TO_OUR_TASK": "Supports multi-component stability structure and the use of a post-impact window; no numerical import",
        "LIMITATIONS": "Ankle-instability COU; single-leg",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Structure only",
    },
    {
        "SOURCE_ID": "S22",
        "FULL_CITATION": "Prieto TE, Myklebust JB, Hoffmann RG, Lovett EG, Myklebust BM. Measures of postural steadiness: differences between healthy young and elderly adults. IEEE Transactions on Biomedical Engineering 1996;43(9):956-966.",
        "DOI_PMID_OR_STANDARD": "PMID 9214811; DOI 10.1109/10.532130",
        "SOURCE_TYPE": "Primary methodological study",
        "POPULATION": "Healthy young and elderly adults",
        "TASK": "Quiet standing",
        "LOAD": "Unloaded",
        "MEASUREMENT_SYSTEM": "Force platform",
        "VARIABLE": "Time- and frequency-domain postural steadiness measures (COP-based)",
        "DEFINITION": "Standardized COP/COM-based steadiness metrics",
        "THRESHOLD_IF_ANY": "Normative differences; no single success threshold",
        "METHOD": "Standardized measurement",
        "UNCERTAINTY_OR_RELIABILITY": "Established metric set",
        "APPLICABILITY_TO_OUR_TASK": "Supports defining stable standing by physical stability measures rather than trace equality; E12 envelope calibration should use quiet-standing logic",
        "LIMITATIONS": "Human COP; no simulation transfer values",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Informs RES-87 envelope structure",
    },
    {
        "SOURCE_ID": "S23",
        "FULL_CITATION": "Hof AL, Gazendam MGJ, Sinke WE. The condition for dynamic stability. Journal of Biomechanics 2005;38(1):1-8.",
        "DOI_PMID_OR_STANDARD": "PMID 15519333; DOI 10.1016/j.jbiomech.2004.03.025",
        "SOURCE_TYPE": "Primary methodological study",
        "POPULATION": "Analytical / human balance",
        "TASK": "Dynamic stability condition",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "Theory + human balance",
        "VARIABLE": "Extrapolated center of mass / capture-point condition",
        "DEFINITION": "Stability requires the extrapolated COM to be inside the base of support",
        "THRESHOLD_IF_ANY": "No numeric threshold",
        "METHOD": "Analytical derivation",
        "UNCERTAINTY_OR_RELIABILITY": "Widely replicated framework",
        "APPLICABILITY_TO_OUR_TASK": "Supports requiring COM-in-support-hull margin for capture (E11) and treating capture as a dynamic condition, not vertical arrest",
        "LIMITATIONS": "General balance theory; no task thresholds",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Structure only",
    },
    {
        "SOURCE_ID": "S24",
        "FULL_CITATION": "ASME. V&V 40-2018: Assessing Credibility of Computational Modeling through Verification and Validation: Application to Medical Devices. American Society of Mechanical Engineers, 2018.",
        "DOI_PMID_OR_STANDARD": "ASME V&V 40-2018; ISBN 9780791872048",
        "SOURCE_TYPE": "Standard",
        "POPULATION": "Medical-device computational models (generalizable framework)",
        "TASK": "Credibility assessment framework",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "V&V methodology",
        "VARIABLE": "Context of use, model risk, credibility factors",
        "DEFINITION": "Credibility established through V&V activities commensurate with the context of use and the consequence of an incorrect decision",
        "THRESHOLD_IF_ANY": "No thresholds; framework",
        "METHOD": "Risk-informed credibility assessment",
        "UNCERTAINTY_OR_RELIABILITY": "Framework not a quantitative method",
        "APPLICABILITY_TO_OUR_TASK": "Direct: our contract freezes a COU and a claim ceiling and separates verification from validation; medical-device risk thresholds are NOT imported",
        "LIMITATIONS": "Written for medical devices; the standard itself states it is general enough for other disciplines",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "V&V principle authority for SUCCESSOR_CONTEXT_OF_USE and SCIENTIFIC_CLAIM_CEILING",
    },
    {
        "SOURCE_ID": "S25",
        "FULL_CITATION": "U.S. Food and Drug Administration. Assessing the Credibility of Computational Modeling and Simulation in Medical Device Submissions. Guidance for Industry and Food and Drug Administration Staff, November 2023.",
        "DOI_PMID_OR_STANDARD": "FDA 2023 guidance; https://www.fda.gov/media/154985/download",
        "SOURCE_TYPE": "Regulatory guidance",
        "POPULATION": "Medical device CM&S submissions",
        "TASK": "Credibility framework",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "V&V/credibility evidence categories",
        "VARIABLE": "Question of interest, context of use, model risk, credibility evidence",
        "DEFINITION": "Credibility = trust in predictive capability for a context of use",
        "THRESHOLD_IF_ANY": "No thresholds",
        "METHOD": "Risk-informed framework building on ASME V&V 40",
        "UNCERTAINTY_OR_RELIABILITY": "Nonbinding recommendations",
        "APPLICABILITY_TO_OUR_TASK": "Supports separating simulation qualification from validation and declaring what evidence a claim needs",
        "LIMITATIONS": "Regulatory context; no numeric transfer",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Claim-ceiling logic",
    },
    {
        "SOURCE_ID": "P01",
        "FULL_CITATION": "Loaded CMJ project. PROJECT_SCIENTIFIC_CONSTITUTION.md (repository canonical document, v1.0.0)",
        "DOI_PMID_OR_STANDARD": "N/A (project internal authority)",
        "SOURCE_TYPE": "Project internal authority",
        "POPULATION": "Computational system",
        "TASK": "Project scientific rules",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "Project constitution",
        "DEFINITION": "Internal scientific governance",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Document",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Governs the successor contract",
        "LIMITATIONS": "Internal, not peer-reviewed",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Internal authority",
    },
    {
        "SOURCE_ID": "P02",
        "FULL_CITATION": "Loaded CMJ project. VVUQ_AND_QUALIFICATION_TAXONOMY.md (repository canonical document, v1.0.0)",
        "DOI_PMID_OR_STANDARD": "N/A (project internal authority)",
        "SOURCE_TYPE": "Project internal authority",
        "POPULATION": "Computational system",
        "TASK": "Terminology governance",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "Verification/validation/qualification taxonomy",
        "DEFINITION": "CODE_VERIFICATION / SOLUTION_VERIFICATION / MODEL_VALIDATION / CONTROL_QUALIFICATION / REPRODUCIBILITY",
        "THRESHOLD_IF_ANY": "Landing peak <= 8 BW and penetration <= 0.010 m cited as project hard-rule examples",
        "METHOD": "Document",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Provides the qualification vocabulary and historical hard-rule candidates (L4-G4/G6)",
        "LIMITATIONS": "Internal",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "YES",
        "NOTES": "RETAINED as candidate project thresholds subject to OD-04 re-approval",
    },
    {
        "SOURCE_ID": "P03",
        "FULL_CITATION": "Loaded CMJ project. INTENDED_USE_AND_CLAIM_BOUNDARY.md (repository canonical document, v1.0.0)",
        "DOI_PMID_OR_STANDARD": "N/A (project internal authority)",
        "SOURCE_TYPE": "Project internal authority",
        "POPULATION": "Computational system",
        "TASK": "Claim boundary",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "Acceptable claim / claim ceiling",
        "DEFINITION": "Simulation qualification only; no human predictive validity without referent",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Document",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Source for the successor claim ceiling",
        "LIMITATIONS": "Internal",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Internal authority",
    },
    {
        "SOURCE_ID": "P04",
        "FULL_CITATION": "Loaded CMJ project. BILATERAL_SUPPORT_CONTINUITY_CONTRACT (RES-57) and support_continuity_spec.json",
        "DOI_PMID_OR_STANDARD": "N/A (project internal authority; spec hash cde531e9...)",
        "SOURCE_TYPE": "Project internal authority",
        "POPULATION": "Computational system",
        "TASK": "Support-continuity measurement semantics",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "Virtual force plates + geometry",
        "VARIABLE": "GEOMETRIC_ENGAGEMENT, COMPRESSIVE_SUPPORT, UNILATERAL_FORCE_DROPOUT, GEOMETRIC_LIFTOFF, SEPARATION_EVIDENCE, CONTROL_RELEVANT_SUPPORT_LOSS_EPISODE, CANONICAL_REFLIGHT",
        "DEFINITION": "Force zero never equals liftoff without geometry; short dropout < 5 ms is not control-relevant; canonical reflight = whole Fz < 10 N for >= 4 steps",
        "THRESHOLD_IF_ANY": "Per-foot Fz 10 N; control interval 5 ms; reflight 4 steps (0.5 ms); chatter <= 8 transitions",
        "METHOD": "Frozen contract + pure helpers",
        "UNCERTAINTY_OR_RELIABILITY": "Historical RES-56 FAIL preserved",
        "APPLICABILITY_TO_OUR_TASK": "Measurement layer for successor support-continuity scopes and reflight/chatter semantics",
        "LIMITATIONS": "Scoped originally to a 150 ms window; successor contract supplies episode-wide scope binding (MED-012)",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "YES",
        "NOTES": "Retained; scope binding added by RES-82",
    },
    {
        "SOURCE_ID": "P05",
        "FULL_CITATION": "RES-80 sealed forensic audit: DEFECT_REGISTER (53 defects; CRIT-003, HIGH-010/011/012, MED-001/002/012/013/020)",
        "DOI_PMID_OR_STANDARD": "RES80_AUDIT_HEAD 8c1cbb49...; RES80_EVIDENCE_SEAL c921e6de...",
        "SOURCE_TYPE": "Project historical evidence",
        "POPULATION": "V2.1-R001 trajectory and V2 system",
        "TASK": "Forensic defect audit",
        "LOAD": "20 kg",
        "MEASUREMENT_SYSTEM": "Sealed traces + source",
        "VARIABLE": "Defect evidence",
        "DEFINITION": "Sealed defect register",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Forensic audit",
        "UNCERTAINTY_OR_RELIABILITY": "Independently recomputed in RES-81",
        "APPLICABILITY_TO_OUR_TASK": "Defines the defect closure obligations owned by RES-82",
        "LIMITATIONS": "Historical; R001 remains BLOCKED",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "R001 is the canonical negative example",
    },
    {
        "SOURCE_ID": "P06",
        "FULL_CITATION": "RES-81 sealed authority reset: RES80_DEFECT_TO_ROADMAP_MATRIX (53/53 mapped)",
        "DOI_PMID_OR_STANDARD": "RES81_EVIDENCE_SEAL a0ed5304e6835fa9a367e3dfb11d36d652c80fbc99e0eca60fd1d99027a5eeca (sealed in the external evidence root EXP-RES81-POST-RES80-AUTHORITY-RESET-001/SEAL.json)",
        "SOURCE_TYPE": "Project historical evidence",
        "POPULATION": "Program roadmap",
        "TASK": "Defect ownership mapping",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "Primary/secondary ownership",
        "DEFINITION": "RES-82 primary owner: CRIT-003, HIGH-010, HIGH-011, MED-001, MED-002, MED-012, MED-013, MED-020",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Matrix",
        "UNCERTAINTY_OR_RELIABILITY": "Reviewed 42/42 PASS",
        "APPLICABILITY_TO_OUR_TASK": "Scope of RES-82",
        "LIMITATIONS": "N/A",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Ownership authority",
    },
    {
        "SOURCE_ID": "P07",
        "FULL_CITATION": "RES-81 sealed errata: RES80_ERRATA_001 (jump-height terminology, takeoff timeline, action-step timestamp, lead times, one-sided balance wording)",
        "DOI_PMID_OR_STANDARD": "RES81_EVIDENCE_SEAL a0ed5304e6835fa9a367e3dfb11d36d652c80fbc99e0eca60fd1d99027a5eeca (sealed in the external evidence root EXP-RES81-POST-RES80-AUTHORITY-RESET-001/SEAL.json)",
        "SOURCE_TYPE": "Project historical evidence",
        "POPULATION": "R001 artifacts",
        "TASK": "Numeric/causal corrections",
        "LOAD": "20 kg",
        "MEASUREMENT_SYSTEM": "Sealed arrays",
        "VARIABLE": "Takeoff timeline; jump-height names",
        "DEFINITION": "FIRST_TRANSIENT_FORCE_DROPOUT 0.640 s; SUSTAINED_TAKEOFF_START 0.64675 s; CANONICAL_E6 0.648125 s; APEX_ABOVE_INITIAL_STANDING_COM 0.036265 m; E6 rise 0.075158 m; true-support-off rise 0.076836 m; E6 vz 1.21446 m/s; ballistic 0.075174 m",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Independent recomputation",
        "UNCERTAINTY_OR_RELIABILITY": "0.125 ms grid",
        "APPLICABILITY_TO_OUR_TASK": "Qualified naming and historical reference values; never successor thresholds",
        "LIMITATIONS": "Historical R001 only",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Explicitly not reused as successor thresholds",
    },
    {
        "SOURCE_ID": "P08",
        "FULL_CITATION": "Loaded CMJ project. CANONICAL_V2_RUNTIME_CONTRACT.md / CANONICAL_RUNTIME_AUTHORITY.md / TRACE_SCHEMA_V2.md",
        "DOI_PMID_OR_STANDARD": "N/A (project internal authority)",
        "SOURCE_TYPE": "Project internal authority",
        "POPULATION": "Computational system",
        "TASK": "Runtime and trace schema",
        "LOAD": "20 kg",
        "MEASUREMENT_SYSTEM": "MuJoCo + virtual plates",
        "VARIABLE": "Runtime contract, observation contract, trace schema",
        "DEFINITION": "Frozen runtime/composition and trace fields",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Document + code",
        "UNCERTAINTY_OR_RELIABILITY": "Subject to RES-88 provenance rebuild",
        "APPLICABILITY_TO_OUR_TASK": "Defines the measurement surfaces the successor metrics will be computed from",
        "LIMITATIONS": "Historical implementation defects owned by other RES",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "Context",
    },
    {
        "SOURCE_ID": "B01",
        "FULL_CITATION": "Robertson DGE, Caldwell GE, Hamill J, Kamen G, Whittlesey SN. Research Methods in Biomechanics (2nd ed.). Human Kinetics.",
        "DOI_PMID_OR_STANDARD": "ISBN 9780736093408",
        "SOURCE_TYPE": "Authoritative biomechanics text",
        "POPULATION": "N/A",
        "TASK": "Biomechanics measurement methodology",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "N/A",
        "DEFINITION": "N/A",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Textbook",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Not located in accessible project paths during RES-82; no citation used",
        "LIMITATIONS": "NOT_LOCATED",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "SOURCE_REVIEW_COVERAGE records the attempted inspection",
    },
    {
        "SOURCE_ID": "B02",
        "FULL_CITATION": "Zatsiorsky VM. Kinematics of Human Motion. Human Kinetics.",
        "DOI_PMID_OR_STANDARD": "ISBN 9780880116763",
        "SOURCE_TYPE": "Authoritative biomechanics text",
        "POPULATION": "N/A",
        "TASK": "Human motion kinematics",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "N/A",
        "DEFINITION": "N/A",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Textbook",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Not located in accessible project paths during RES-82; no citation used",
        "LIMITATIONS": "NOT_LOCATED",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "SOURCE_REVIEW_COVERAGE records the attempted inspection",
    },
    {
        "SOURCE_ID": "B03",
        "FULL_CITATION": "Zatsiorsky VM. Kinetics of Human Motion. Human Kinetics.",
        "DOI_PMID_OR_STANDARD": "ISBN 9780736045780",
        "SOURCE_TYPE": "Authoritative biomechanics text",
        "POPULATION": "N/A",
        "TASK": "Human motion kinetics",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "N/A",
        "DEFINITION": "N/A",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Textbook",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Not located in accessible project paths during RES-82; no citation used",
        "LIMITATIONS": "NOT_LOCATED",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "SOURCE_REVIEW_COVERAGE records the attempted inspection",
    },
    {
        "SOURCE_ID": "B04",
        "FULL_CITATION": "Oberkampf WL, Roy CJ. Verification and Validation in Scientific Computing. Cambridge University Press.",
        "DOI_PMID_OR_STANDARD": "ISBN 9780521761601",
        "SOURCE_TYPE": "Authoritative V&V text",
        "POPULATION": "N/A",
        "TASK": "V&V methodology",
        "LOAD": "N/A",
        "MEASUREMENT_SYSTEM": "N/A",
        "VARIABLE": "N/A",
        "DEFINITION": "N/A",
        "THRESHOLD_IF_ANY": "N/A",
        "METHOD": "Textbook",
        "UNCERTAINTY_OR_RELIABILITY": "N/A",
        "APPLICABILITY_TO_OUR_TASK": "Not located in accessible project paths during RES-82; V&V principles represented by ASME V&V 40 (S24) and the project taxonomy (P02)",
        "LIMITATIONS": "NOT_LOCATED",
        "DIRECTLY_SUPPORTS_NUMERIC_GATE": "NO",
        "NOTES": "SOURCE_REVIEW_COVERAGE records the attempted inspection",
    },
]


def main() -> None:
    csv_path = OUT / "SCIENTIFIC_CONTRACT_EVIDENCE_TABLE.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDS)
        writer.writeheader()
        for row in ROWS:
            missing = [f for f in FIELDS if f not in row]
            if missing:
                raise ValueError(f"{row['SOURCE_ID']} missing fields: {missing}")
            writer.writerow({f: row[f] for f in FIELDS})

    md_path = OUT / "SCIENTIFIC_CONTRACT_EVIDENCE_TABLE.md"
    lines = [
        "# SCIENTIFIC_CONTRACT_EVIDENCE_TABLE",
        "",
        "MISSION: `RES82_SUCCESSOR_LOADED_CMJ_SCIENTIFIC_TASK_CONTRACT_001`",
        "",
        "Every numerical threshold entering the successor contract must cite a row here.",
        "Source classes: WEB/EXTERNAL LITERATURE, STANDARD, PROJECT INTERNAL AUTHORITY,",
        "PROJECT HISTORICAL EVIDENCE. `DIRECTLY_SUPPORTS_NUMERIC_GATE=YES` rows are the only",
        "rows from which a numeric gate value may be taken; all other numeric values are",
        "physics identities, numerical tolerances, model-dependent items, or explicit owner",
        "decisions.",
        "",
        f"Rows: {len(ROWS)} (external = {sum(1 for r in ROWS if r['SOURCE_ID'].startswith('S'))}, "
        f"project = {sum(1 for r in ROWS if r['SOURCE_ID'].startswith('P'))}, "
        f"books attempted = {sum(1 for r in ROWS if r['SOURCE_ID'].startswith('B'))})",
        "",
    ]
    for row in ROWS:
        lines.append(f"## {row['SOURCE_ID']} — {row['FULL_CITATION']}")
        lines.append("")
        lines.append(f"- **Identifier:** {row['DOI_PMID_OR_STANDARD']}")
        lines.append(f"- **SOURCE_TYPE:** {row['SOURCE_TYPE']}")
        lines.append(f"- **POPULATION:** {row['POPULATION']}")
        lines.append(f"- **TASK:** {row['TASK']}")
        lines.append(f"- **LOAD:** {row['LOAD']}")
        lines.append(f"- **MEASUREMENT_SYSTEM:** {row['MEASUREMENT_SYSTEM']}")
        lines.append(f"- **VARIABLE:** {row['VARIABLE']}")
        lines.append(f"- **DEFINITION:** {row['DEFINITION']}")
        lines.append(f"- **THRESHOLD_IF_ANY:** {row['THRESHOLD_IF_ANY']}")
        lines.append(f"- **METHOD:** {row['METHOD']}")
        lines.append(f"- **UNCERTAINTY_OR_RELIABILITY:** {row['UNCERTAINTY_OR_RELIABILITY']}")
        lines.append(f"- **APPLICABILITY_TO_OUR_TASK:** {row['APPLICABILITY_TO_OUR_TASK']}")
        lines.append(f"- **LIMITATIONS:** {row['LIMITATIONS']}")
        lines.append(f"- **DIRECTLY_SUPPORTS_NUMERIC_GATE:** {row['DIRECTLY_SUPPORTS_NUMERIC_GATE']}")
        lines.append(f"- **NOTES:** {row['NOTES']}")
        lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"rows": len(ROWS), "csv": str(csv_path), "md": str(md_path)}, indent=2))


if __name__ == "__main__":
    main()
