#!/usr/bin/env python3
"""Render the RES-95 Plant model authority bundle (JSON + Markdown + evidence table).

Deterministic, idempotent. Reads AUTHORITY_INPUTS.json and DERIVED_QUANTITIES.json.
Writes the authority artifacts listed in ARTIFACTS plus the evidence table.
Does not write the hash manifest, the validation report, or the review/receipt
(authored separately and sealed afterwards).

Run:  python3 render_authority_bundle.py
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
INPUTS = json.loads((HERE / "AUTHORITY_INPUTS.json").read_text())
DER = json.loads((HERE / "DERIVED_QUANTITIES.json").read_text())

AUTHORITY_ID = INPUTS["authority_id"]
MISSION = INPUTS["mission"]
CONTEXT = INPUTS["sport_context_id"]

# --------------------------------------------------------------------------------------
# Source registry
# --------------------------------------------------------------------------------------
SOURCES = [
    dict(id="S01", citation="de Leva P. Adjustments to Zatsiorsky-Seluyanov's segment inertia parameters. Journal of Biomechanics 1996;29(9):1223-1230.",
         doi="10.1016/0021-9290(95)00178-6; PMID 8872282", type="Primary anthropometry / BSIP",
         scope="Adjusted male body-segment mass fractions, segment lengths, COM positions and radii of gyration referenced to joint centers",
         verification="REVERIFIED_PRIMARY_TABLE",
         notes="Tables 1-4 and the alternative-endpoint rows were read directly from the paper PDF during RES-95; Table 4 male values reproduced here as machine-readable inputs."),
    dict(id="S02", citation="Matsumoto Y, Ogihara N, Hanawa H, Kokubun T, Kanemura N. Novel multi-segment foot model incorporating plantar aponeurosis for detailed kinematic and kinetic analyses of the foot with application to gait studies. Frontiers in Bioengineering and Biotechnology 2022;10:894731.",
         doi="10.3389/fbioe.2022.894731", type="Primary foot-segment inertial parameters",
         scope="Three-segment foot (hindfoot/forefoot/phalanx) relative mass, relative COM and relative inertial tensor from CT",
         verification="REVERIFIED_PRIMARY_TABLE",
         notes="Table 3 read directly; relative masses 43.2/42.4/14.4 % and relative inertia scaling rule I = I_rel * m^(5/3)."),
    dict(id="S03", citation="Drillis R, Contini R. Body segment parameters. New York University / DHEW report, 1966; reproduced in Winter DA, Biomechanics and Motor Control of Human Movement, Fig. 4.1 (body segment lengths as a fraction of stature H).",
         doi="Report DHEW 1166-03 (1966); figure reproduced in Winter 2009 4th ed.", type="Anthropometric reference figure",
         scope="General adult body segment length fractions of stature, including ankle joint height 0.039H, foot length 0.152H, foot breadth 0.055H",
         verification="REVERIFIED_PRIMARY_FIGURE",
         notes="Figure 4.1 read directly during RES-95; used for ankle joint height only, where no joint-center-resolved de Leva value exists."),
    dict(id="S04", citation="International Weightlifting Federation (IWF) Technical and Competition Rules; men's 20 kg Olympic bar specification.",
         doi="IWF TCR (bar specification section)", type="Equipment standard",
         scope="20 kg bar, 2.200 m total length, 28 mm grip section, 50 mm x 415 mm sleeves, 1.310 m grip section",
         verification="AUTHORITY_SYNCED",
         notes="Geometry frozen from the Linear system authority; no uniform-rod representation may be called IWF geometry."),
    dict(id="S05", citation="Bongiovanni T, Rossi A, Genovesi F, Martera G, Puleo G, Orlandi C, Spedicato M, Iaia FM, Del Vescovo R, Gallo S, Cannataro R, Ripari P, Levi Micheli M, Cataldi S, Trecroci A. How do football playing positions differ in body composition? A first insight into white Italian Serie A and Serie B players. Journal of Functional Morphology and Kinesiology 2023;8(2):80.",
         doi="10.3390/jfmk8020080; PMCID PMC10299074; PMID 37367244", type="Elite soccer anthropometry cohort",
         scope="506 male professional Italian Serie A/B players; age 25.72 +/- 4.02 y, stature 183.72 +/- 5.86 cm, mass 79.91 +/- 6.31 kg, positional differences",
         verification="REVERIFIED_PRIMARY_TABLE",
         notes="Abstract and Table 1 read directly; source is referred to as 'Campa et al.' in the Linear synchronization, corrected to Bongiovanni et al. here."),
    dict(id="S06", citation="Badby AJ, et al. Contemporary English Football League force-plate normative benchmarks for professional soccer players. Journal of Sports Sciences 2025.",
         doi="10.1080/02640414.2025.2523671", type="Elite soccer performance cohort",
         scope="139 professionals from seven clubs (184 +/- 7 cm; 81 +/- 9 kg); ~0.35 m unloaded CMJ and ~0.23 m countermovement depth on its method",
         verification="AUTHORITY_SYNCED",
         notes="Report/calibration anchor only; not a +20 kg direct SYSTEM_COM norm."),
    dict(id="S07", citation="Asimakidis ND, et al. Assessment of strength and power capacities in elite male soccer. Sports Medicine 2024.",
         doi="10.1007/s40279-024-02071-8", type="Elite soccer performance review",
         scope="Elite male soccer strength/power testing practice incl. CMJ; heterogeneous methods across 54 studies (unloaded means ~33.6-57.2 cm)",
         verification="AUTHORITY_SYNCED",
         notes="Method heterogeneity is the reason no single elite +20 kg direct H2 gate is frozen."),
    dict(id="S08", citation="Yamauchi J, et al. Mechanical role of the metatarsophalangeal joint in human jumping. PLOS ONE 2022.",
         doi="10.1371/journal.pone.0268634", type="Primary MTP/jumping experiment",
         scope="Restricting MTP motion reduces CMJ height and net vertical impulse; toe-flexor strength correlates with jump performance",
         verification="AUTHORITY_SYNCED",
         notes="Basis for requiring an active bounded MTP channel in addition to a passive prior."),
    dict(id="S09", citation="Smith RE, et al. Selective loss of intrinsic foot muscle activity reduces MTP quasi-stiffness, ankle leverage and jump height (nerve-block study). Journal of Sport and Health Science 2023.",
         doi="10.1016/j.jshs.2022.07.002", type="Primary foot-muscle experiment",
         scope="Intrinsic foot muscle contribution to MTP stiffness and jump height",
         verification="AUTHORITY_SYNCED",
         notes="Corroborates that a passive-only MTP is insufficient for a human-valid maximal-CMJ claim."),
    dict(id="S10", citation="Dynamic predictive foot model for simulations of human gait (2024). PLOS Computational Biology.",
         doi="10.1371/journal.pcbi.1012219", type="Predictive gait model",
         scope="Gait-model passive foot/MTP compliance priors (including ~25 N m/rad and ~2 N m s/rad class values used as one engineering baseline)",
         verification="AUTHORITY_SYNCED",
         notes="The 25/2 pair is a gait-derived engineering prior, not a CMJ measurement; mandatory sensitivity including zero-passive."),
    dict(id="S11", citation="Eythorsdottir I, et al. The battle of the equations: a systematic review of jump height calculations using force platforms. Sports Medicine 2024.",
         doi="10.1007/s40279-024-02098-x; PMID 39425876", type="Systematic review",
         scope="Jump-height equations and processing choices; equation choice can change jump height by up to ~15 cm on the same jump",
         verification="AUTHORITY_SYNCED",
         notes="Method-matched comparison is mandatory before any elite numeric H2 gate."),
    dict(id="S12", citation="Xu J, et al. A systematic review of the different calculation methods for measuring jump height during the countermovement and drop jump tests. Sports Medicine 2023.",
         doi="10.1007/s40279-023-01828-x; PMID 36940054", type="Systematic review",
         scope="Impulse-momentum preferred for takeoff-to-apex; method definitions differ",
         verification="AUTHORITY_SYNCED",
         notes="Supports direct SYSTEM_COM takeoff-to-apex as the primary simulation truth and impulse/flight-time as comparators."),
    dict(id="S13", citation="Kraska JM, et al. Relationship between strength characteristics and unweighted and weighted vertical jump height. International Journal of Sports Physiology and Performance 2009.",
         doi="10.1123/ijspp.4.4.461; PMID 20029097", type="Primary loaded-jump study",
         scope="+20 kg CMJ flight-time heights in collegiate athletes; strongest subgroup ~27.6 cm, weakest ~18.7 cm",
         verification="AUTHORITY_SYNCED",
         notes="Cross-family comparator only (flight-time, collegiate), not a direct SYSTEM_COM band."),
    dict(id="S14", citation="Lopez-Segovia M, et al. Effects of loaded CMJ on soccer players (+20/+30/+40 kg). Journal of Human Kinetics 2011.",
         doi="10.2478/v10078-011-0081-2", type="Primary soccer loaded-jump study",
         scope="U21 soccer loaded CMJ; +20 kg is task-relevant but does not provide a senior-elite method-matched H2 distribution",
         verification="AUTHORITY_SYNCED",
         notes="Task-relevance evidence only."),
    dict(id="S15", citation="Fritz J, et al. Loaded barbell jump landing kinetics. Journal of Biomechanics 2021.",
         doi="10.1016/j.jbiomech.2021.110354", type="Primary landing mechanics study",
         scope="Increasing barbell load changes landing kinematics, reduces hip/knee peak power, increases ankle energy dissipation",
         verification="AUTHORITY_SYNCED",
         notes="Landing validation must inspect ankle/MTP behavior, not COM alone."),
    dict(id="S16", citation="Proximal trunk-borne load countermovement jump coordination study. PMID 30126721.",
         doi="PMID 30126721", type="Primary coordination study",
         scope="External trunk load shifts coordination toward greater hip contribution early and hip+ankle contribution late",
         verification="AUTHORITY_SYNCED",
         notes="Strategy envelope: no unloaded knee-dominant template may be forced."),
    dict(id="S17", citation="Takeoff-threshold comparison study in countermovement jumps. PMID 38863789.",
         doi="PMID 38863789", type="Primary methodological study",
         scope="10 N / 10 ms class force thresholds are measurement comparators, reliable but not physical truth",
         verification="AUTHORITY_SYNCED",
         notes="Comparator-only status frozen in EVENT_MEASUREMENT_BOUNDARY."),
    dict(id="S18", citation="White RM. Comparative anthropometry of the foot. US Army Natick Research & Development Laboratories, 1983.",
         doi="ADA126189", type="Anthropometric survey",
         scope="Adult foot breadth and heel breadth distributions; heel breadth materially below ball breadth",
         verification="AUTHORITY_SYNCED",
         notes="Context for the heel contact patch being narrower than the forefoot patch; patch dimensions remain engineering nominals."),
    dict(id="S19", citation="CDC / general adult joint range-of-motion reference values.",
         doi="CDC normal joint ROM reference (as recorded in the Linear system authority)", type="Clinical anatomy reference",
         scope="General-human ROM including weight-bearing dorsiflexion ~39-45 deg and soccer jump-landing peak dorsiflexion ~32-38 deg",
         verification="AUTHORITY_SYNCED",
         notes="Structural capability bounds are anatomy-driven, not soccer-specific technique targets."),
    dict(id="S20", citation="Elite-soccer foot-length source recorded in the Linear system authority (reports 27.2 +/- 0.9 with an internally implausible unit label).",
         doi="not resolved in the synced authority", type="Secondary anthropometric context",
         scope="Elite soccer foot length",
         verification="AUTHORITY_SYNCED",
         notes="Unit label internally inconsistent relative to reported stature; corroborative only, never sole direct authority."),
    dict(id="S21", citation="Adolescent male football anthropometry (foot length ~27.23 +/- 1.89 cm, width ~10.41 +/- 0.57 cm in the oldest group).",
         doi="as recorded in the Linear system authority", type="Secondary anthropometric context",
         scope="Adolescent male football foot dimensions",
         verification="AUTHORITY_SYNCED",
         notes="Supports the 0.275 x 0.105 m literature-informed synthetic nominal."),
    dict(id="S22", citation="Project canonical methodology books: force-platform measurement, inverse/forward dynamics, uncertainty propagation, impact/contact mechanics, and V&V (as recorded in the Linear system authority).",
         doi="project internal authority", type="Project methodology authority",
         scope="V&V separation, measurement definitions, contact mechanics framing",
         verification="PROJECT_AUTHORITY",
         notes="Methodological framing only; no numeric value is taken from this row."),
]


def d(path: str):
    node = DER
    for part in path.split("."):
        node = node[part]
    return node


def n(v, sig=9):
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, (int, float)):
        if v == 0:
            return "0"
        return f"{v:.{sig}g}"
    if isinstance(v, list):
        return "[" + ", ".join(n(x, sig) for x in v) + "]"
    return str(v)


def D(id, statement, value, units, classification, sources, locator, sensitivity="—", notes=""):
    return dict(id=id, statement=statement, value=value, units=units, classification=classification,
                sources=sources, locator=locator, sensitivity=sensitivity, notes=notes)


# --------------------------------------------------------------------------------------
# Decision registry
# --------------------------------------------------------------------------------------
DECISIONS = {
    "sport_context": [
        D("SC-01", "Sport-context identifier for the successor Plant reference population.",
          CONTEXT, "—", "LITERATURE_INFORMED_SYNTHETIC", "S05;S06;S07",
          "Linear Elite Soccer System Authority V1 section 1; Bongiovanni 2023 cohort",
          "—", "Synthetic population identifier; not a claim about any individual."),
        D("SC-02", "Reference population definition.",
          "healthy senior adult male first-team professional outfield soccer player, top-tier European domestic league / UEFA-caliber environment; goalkeepers excluded; field position not frozen",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S05;S06;S07",
          "System authority section 1; S05 positional differences", "—",
          "Position-specific variants are future calibrations."),
        D("SC-03", "Task definition.",
          "maximal voluntary bilateral +20.0 kg back-loaded countermovement jump, hands fixed to the bar, no arm swing, dual-force-plate laboratory setting, full standing-countermovement-flight-landing-recovery sequence",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S13;S14;S16",
          "System authority section 1; loaded-CMJ task evidence", "—",
          "Sagittal-dominant reduced rigid-body model."),
        D("SC-04", "Claim boundary of the V1 reduction.",
          "sagittal-plane mechanics only; lateral translation, roll and yaw are structurally removed; no 3-D cutting/lateral/asymmetric validity claim",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22",
          "System authority sections 7 and 20; PLAN_TOPOLOGY_AUTHORITY", "—",
          "Any materially asymmetric control claim requires a future true 3-D/6-DOF Plant."),
        D("SC-05", "Evidence hierarchy for authority decisions.",
          "1 human anatomy/joint mechanics/BSIP; 2 elite senior male first-division soccer anthropometry; 3 elite/professional soccer CMJ testing evidence; 4 soccer +20 kg loaded-jump evidence supplemented by broader loaded-CMJ work; 5 NBA elite CMJ data as secondary strategy comparator; 6 engineering choices only where literature does not determine a unique value, always tagged and sensitivity-tested",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S01;S05;S06;S07;S13;S14",
          "Linear RES-95 description; System authority section 2", "—",
          "No engineering value may be relabeled as an elite-soccer measurement."),
        D("SC-06", "Use of NBA CMJ cohort data.",
          "secondary elite movement-strategy comparator only; it sets neither soccer anthropometry nor +20 kg performance thresholds",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S07",
          "System authority sections 1 and 14", "—",
          "Recorded to prevent strategy-template drift."),
        D("SC-07", "Claim ceiling after the Plant rebuild (M6).",
          "the Plant may be called a sagittal-dominant rigid-body model parameterized to a nominal elite senior male professional outfield soccer athlete and configured for a maximal 20 kg loaded countermovement jump; no subject-specific, population-norm, injury-risk, optimality, midfoot-fidelity or field/turf claim",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S22",
          "System authority section 20; RES-82 SCIENTIFIC_CLAIM_CEILING.md", "—",
          "verification != validation; determinism != biomechanical validity."),
    ],
    "reference_athlete": [
        D("RA-01", "Synthetic nominal athlete sex and age class.",
          "male; senior_adult; reference age 24 y (nominal)", "—", "LITERATURE_INFORMED_SYNTHETIC", "S05;S06",
          "System authority section 3", "—", "Not a real person and not the exact population mean."),
        D("RA-02", "Reference stature.", INPUTS["reference_athlete"]["ATHLETE_STATURE_M"], "m",
          "LITERATURE_INFORMED_SYNTHETIC", "S05;S06",
          "S05 183.72 +/- 5.86 cm; S06 184 +/- 7 cm; rounded synthetic consensus",
          "sensitivity set " + n(INPUTS["reference_athlete"]["stature_sensitivity_m"]) + " m",
          "Inside contemporary first-team professional distributions."),
        D("RA-03", "Reference athlete mass.", INPUTS["reference_athlete"]["ATHLETE_MASS_KG"], "kg",
          "LITERATURE_INFORMED_SYNTHETIC", "S05;S06",
          "S05 79.91 +/- 6.31 kg; S06 81 +/- 9 kg", "sensitivity set " + n(INPUTS["reference_athlete"]["mass_sensitivity_kg"]) + " kg",
          "Rounded synthetic consensus; not a population mean claim."),
        D("RA-04", "External load mass.", INPUTS["reference_athlete"]["EXTERNAL_LOAD_MASS_KG"], "kg",
          "LITERATURE_DIRECT", "S04;S13;S14", "IWF men's bar standard; loaded-CMJ task",
          "—", "Rigid 20 kg composite bar surrogate; see LOAD_BAR_AUTHORITY."),
        D("RA-05", "Total mechanical system mass.", INPUTS["reference_athlete"]["TOTAL_SYSTEM_MASS_KG"], "kg",
          "PHYSICS_IDENTITY", "—", "athlete + rigid bar mass sum", "—",
          "Force/impulse and ballistic identities use this mass; machine check in ANTHROPOMETRY_BSIP_AUTHORITY."),
        D("RA-06", "Load-to-athlete mass ratio.", d("load_to_athlete_mass_ratio"), "—",
          "PHYSICS_IDENTITY", "—", "20.0 / 79.0", "—", "Derived identity."),
        D("RA-07", "Nominal system weight at the project gravity constant.",
          d("system_weight_N"), "N", "PHYSICS_IDENTITY", "—",
          "99.0 kg * 9.81 m/s^2", "—", "Athlete-only weight is " + n(d("athlete_weight_N")) + " N; system authority uses the full carried system."),
        D("RA-09", "Reconciliation of the historical RES-82 body-weight constant.",
          {"RES82_BW": "95.0 kg * 9.81 = 931.95 N (historical V2 75 kg athlete + 20 kg load)",
           "SUCCESSOR_SYSTEM_WEIGHT": "99.0 kg * 9.81 = 971.19 N",
           "rule": "RES-82 thresholds expressed in units of BW are recomputed on the 99.0 kg successor base; no downstream artifact may inherit the 95 kg BW silently"},
          "N", "PHYSICS_IDENTITY", "S22",
          "RES-82 EVENT_CONTRACT term BW versus the controlling Linear system authority section 3",
          "—",
          "Historical RES-82 BW remains in RES-82's sealed artifacts; this decision is the successor reconciliation so force thresholds are computed on one base."),
        D("RA-08", "Reference athlete is a synthetic nominal, not a measured subject.",
          "no individual prediction or exact-mean claim is permitted from this nominal", "—",
          "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S05;S06", "System authority section 3", "—",
          "All downstream claims inherit this ceiling."),
    ],
    "anthropometry": [
        D("AB-01", "Primary BSIP authority.",
          "de Leva (1996) adjustment of Zatsiorsky-Seluyanov parameters, joint-center referenced", "—",
          "LITERATURE_DIRECT", "S01", "S01 Tables 1-4", "—",
          "Machine-readable coefficients in AUTHORITY_INPUTS.json; no uniform-density torso shortcut may be called anthropometric authority."),
        D("AB-02", "Male segment mass fractions (head 0.0694; upper trunk 0.1596; middle trunk 0.1633; pelvis/lower trunk 0.1117; upper arm 0.0271 each; forearm 0.0162 each; hand 0.0061 each; thigh 0.1416 each; shank 0.0433 each; whole foot 0.0137 each).",
          [0.0694, 0.1596, 0.1633, 0.1117, 0.0271, 0.0162, 0.0061, 0.1416, 0.0433, 0.0137],
          "fraction of athlete mass", "LITERATURE_DIRECT", "S01", "S01 Table 4, male column", "—",
          "Fractions sum to 1.0000 across all segments."),
        D("AB-03", "Segment masses at the reference athlete mass.",
          {"head": d("segment_masses_kg.head"), "upt": d("segment_masses_kg.upt"), "mpt": d("segment_masses_kg.mpt"),
           "pelvis": d("segment_masses_kg.lpt_pelvis"), "upper_arm": d("segment_masses_kg.upper_arm"),
           "forearm": d("segment_masses_kg.forearm"), "hand": d("segment_masses_kg.hand"),
           "thigh": d("segment_masses_kg.thigh"), "shank": d("segment_masses_kg.shank"),
           "whole_foot": d("segment_masses_kg.whole_foot")}, "kg",
          "LITERATURE_DIRECT", "S01", "S01 Table 4 mass fractions * 79.0 kg", "—",
          "Recomputed deterministically by build_authority_numbers.py."),
        D("AB-04", "Athlete and system mass closure.",
          d("mass_closure_kg"), "kg", "PHYSICS_IDENTITY", "S01",
          "sum of body segments; plus bar mass", "—",
          "Machine test: athlete total = 79.0 kg and system total = 99.0 kg within numerical tolerance."),
        D("AB-05", "Thigh segment length (normative form).", d("segment_lengths_m.thigh"), "m",
          "LITERATURE_DIRECT", "S01", "frozen stature ratio 0.2425 * H; de Leva Table 4 male thigh (HJC-KJC) 422.2 mm x stature scale as cross-check",
          "—", "Normative 0.2425 * H = " + n(d("segment_lengths_m.thigh")) + " m; de Leva-scaled cross-check " + n(d("segment_lengths_m.thigh_deleva_scaled_crosscheck_m")) + " m (delta " + n(d("segment_lengths_m.thigh_crosscheck_delta_m")) + " m)."),
        D("AB-06", "Shank segment length (normative form).", d("segment_lengths_m.shank"), "m",
          "LITERATURE_DIRECT", "S01", "frozen stature ratio 0.2493 * H; de Leva Table 4 male shank (KJC-LMAL) 434.0 mm x stature scale as cross-check",
          "—", "Normative 0.2493 * H = " + n(d("segment_lengths_m.shank")) + " m; de Leva-scaled cross-check " + n(d("segment_lengths_m.shank_deleva_scaled_crosscheck_m")) + " m (delta " + n(d("segment_lengths_m.shank_crosscheck_delta_m")) + " m)."),
        D("AB-07", "HAT component segment lengths (head VERT-CERV; upper trunk CERV-XYPH; middle trunk XYPH-OMPH).",
          {"head": d("segment_lengths_m.head"), "upt": d("segment_lengths_m.upt"), "mpt": d("segment_lengths_m.mpt")},
          "m", "LITERATURE_DIRECT", "S01", "S01 Table 4 male alternative-endpoint rows x stature scale",
          "—", "Stature scaling rule: lengths scale linearly with H / 1.741 m."),
        D("AB-08", "Pelvis body parameterization.",
          {"mass_kg": d("pelvis.mass_kg"), "com_z_above_midh_m": d("pelvis.com_z_above_midh_m"),
           "length_m": d("segment_lengths_m.lpt")},
          "kg / m", "LITERATURE_DIRECT", "S01", "S01 Table 4 male lower trunk OMPH-MIDH",
          "—", "The pelvis body carries the de Leva lower-trunk (LPT) parameters; MIDH is the trunk-pelvis hinge center."),
        D("AB-09", "Foot length and width nominal.",
          {"FOOT_LENGTH_M": INPUTS["frozen_geometry"]["FOOT_LENGTH_M"], "FOOT_WIDTH_M": INPUTS["frozen_geometry"]["FOOT_WIDTH_M"]},
          "m", "LITERATURE_INFORMED_SYNTHETIC", "S03;S20;S21",
          "S03 D-C foot length 0.152H = 0.279 m at H; S20/S21 elite and adolescent soccer feet",
          "foot geometry sensitivity: FOOT_LENGTH +/- 0.010 m; FOOT_WIDTH +/- 0.007 m",
          "0.275 x 0.105 m is a literature-informed synthetic nominal, not one-paper direct."),
        D("AB-10", "Ankle joint center height above the sole.", d("foot.ankle_joint_height_m"), "m",
          "HUMAN_ANATOMY_REFERENCE", "S03", "Drillis-Contini Fig. 4.1: ankle height = 0.039 H",
          "ankle-height sensitivity +/- 0.010 m", "Used for standing geometry and contact placement."),
        D("AB-11", "Ankle joint center horizontal position from the heel.",
          INPUTS["frozen_geometry"]["ANKLE_X_FROM_HEEL_M"], "m",
          "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01;S03",
          "no joint-center-resolved public value located; 0.20 * foot length",
          "sensitivity " + n([0.045, 0.065]) + " m",
          "Explicit engineering reduction; must not be presented as measured anatomy."),
        D("AB-12", "de Leva radius-of-gyration axis interpretation.",
          {"sagittal": "about the model medio-lateral axis (sagittal-plane rotation)",
           "transverse": "about the in-plane axis perpendicular to the segment long axis",
           "longitudinal": "about the segment long axis"},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01",
          "S01 Table 4 column semantics (sagittal / transverse / longitudinal r)",
          "segment-inertia sensitivity 0.9x/1.1x on all segment inertia terms",
          "Axis-to-model mapping is an engineering reduction of the published axes; it is applied identically to every segment."),
        D("AB-13", "Segment-chain closure check against reference stature.",
          d("segment_chain_closure"), "m", "PHYSICS_IDENTITY", "S01;S03",
          "ankle height + shank + thigh + (MIDH to vertex chain)",
          "—", "The joint-center-resolved chain overshoots stature by ~3.1 cm (~1.7%); the causes are mixed landmark systems between sources. RES-83 must absorb this in the standing pose and must not rescale the frozen segment lengths to force closure."),
        D("AB-14", "Lower-limb segment inertias about their own COMs (thigh Ixx=Iyy/Izz; shank Ixx/Iyy/Izz).",
          {"thigh_kg_m2": d("thigh.inertia_about_com_kg_m2"), "shank_kg_m2": d("shank.inertia_about_com_kg_m2"),
           "pelvis_kg_m2": d("pelvis.inertia_about_com_kg_m2")},
          "kg m^2", "LITERATURE_DIRECT", "S01", "S01 Table 4 radii of gyration * segment lengths",
          "segment-inertia sensitivity 0.9x/1.1x",
          "Body-frame origins: pelvis at MIDH, thigh at HJC, shank at KJC; z is proximal-to-distal."),
        D("AB-15", "Whole-foot de Leva cross-check versus the multi-segment foot construction.",
          {"whole_foot_sagittal_I_about_com_kg_m2": d("whole_foot_deleva_reference.inertia_about_sagittal_axis_through_com_kg_m2"),
           "assembled_segment_com_x_from_heel_m": d("foot.assembled_foot_com_x_from_heel_m"),
           "deleva_com_x_from_heel_m": d("foot.deleva_foot_com_x_from_heel_m"),
           "com_x_delta_m": d("foot.com_x_delta_vs_deleva_m")},
          "kg m^2 / m", "LITERATURE_DIRECT", "S01;S02",
          "S01 whole-foot row vs S02 three-segment construction",
          "foot-inertia sensitivity 0.5x/1.5x (Matsumoto practice) plus the compliant-midfoot alternative",
          "Cross-check deltas are declared, not hidden; the three-segment construction controls because it is what the Plant implements."),
        D("AB-16", "Stature scaling rule for de Leva component lengths.",
          "linear scaling factor s = H / 1.741 = " + n(DER["scale_factor_s"]), "—",
          "LITERATURE_INFORMED_SYNTHETIC", "S01", "S01 male sample stature 1.741 m",
          "anthropometry sensitivity: stature set " + n(INPUTS["reference_athlete"]["stature_sensitivity_m"]) + " m and mass set " + n(INPUTS["reference_athlete"]["mass_sensitivity_kg"]) + " kg (approximately +/-1 SD of the S05 cohort: 5.86 cm, 6.31 kg)",
          "Applies to HAT components, pelvis and whole-foot reference length; thigh/shank are frozen by their stature ratios."),
        D("AB-17", "No silent anthropometric reinterpretation.",
          "any change to a frozen ratio, mass fraction or length is an explicit authority amendment with downstream requalification",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "System authority section 22", "—",
          "Silent tuning is prohibited."),
    ],
    "upper_body": [
        D("UB-01", "Frozen reduced HAT decomposition.",
          "head + upper trunk + middle trunk + 2x upper arm + 2x forearm + 2x hand (pelvis excluded and carried by the root pelvis body)",
          "—", "LITERATURE_DIRECT", "S01", "S01 Table 4 component rows",
          "—", "HAT mass " + n(d("hat.mass_kg")) + " kg equals the Linear authority value 38.7969 kg."),
        D("UB-02", "Fixed bar-hold posture parameterization (inertia aggregation reference posture).",
          {"trunk": "MPT+UPT collinear on +z", "head_pitch_deg": INPUTS["hat_posture"]["head_pitch_deg"],
           "shoulder_joint_x_m": INPUTS["hat_posture"]["shoulder_joint_x_m"],
           "shoulder_joint_y_m": INPUTS["hat_posture"]["shoulder_joint_y_m"],
           "shoulder_joint_z_m": d("hat.shoulder_joint_m")[2],
           "wrist_dz_m": INPUTS["hat_posture"]["wrist_dz_m"],
           "hand_grip_half_width_y_m": INPUTS["hat_posture"]["hand_grip_half_width_y_m"],
           "elbow_rule": INPUTS["hat_posture"]["elbow_solution_rule"]},
          "m / deg", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01;S04",
          "de Leva component geometry; frozen engineering bar-hold pose",
          "declared perturbations: " + n(DER["hat_sensitivity"]["declared_perturbations"]),
          "Every unmeasured posture parameter is engineering nominal with mandatory sensitivity; none is anthropometric truth."),
        D("UB-03", "Aggregated HAT mass.", d("hat.mass_kg"), "kg", "LITERATURE_DIRECT", "S01",
          "sum of de Leva mass fractions", "—", "Machine-recomputed."),
        D("UB-04", "Aggregated HAT COM in the HAT frame (origin MIDH).",
          d("hat.com_m"), "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01",
          "de Leva component masses (LITERATURE_DIRECT) aggregated under the frozen engineering bar-hold posture UB-02",
          "covered by UB-02 perturbations",
          "The component masses are literature-direct; the aggregate COM inherits the engineering posture classification and is not an anthropometric measurement."),
        D("UB-05", "Aggregated HAT inertia tensor about its COM (full 3x3, HAT frame).",
          d("hat.inertia_about_com_kg_m2"), "kg m^2", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01",
          "de Leva component tensors (LITERATURE_DIRECT) rotated into the HAT frame and translated under the frozen engineering bar-hold posture UB-02",
          "covered by UB-02 perturbations; system Iyy range " + n([DER["hat_sensitivity"]["system_iyy_min"], DER["hat_sensitivity"]["system_iyy_max"]]) + " kg m^2 over the declared set",
          "Ixy=Iyz=0 by left-right symmetry; Ixz is non-zero and must not be silently dropped."),
        D("UB-06", "HAT principal moments and principal rotation.",
          {"principal_moments_kg_m2": d("hat.principal_moments_kg_m2"),
           "principal_rotation_about_y_deg": d("hat.principal_rotation_about_y_deg")},
          "kg m^2 / deg", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—",
          "eigendecomposition of UB-05 (which inherits the engineering posture classification)", "—",
          "The principal rotation is small (~1.4 deg); a diagonal implementation is permitted only with this declared rotation or with the full tensor."),
        D("UB-07", "Bar local placement relative to the HAT frame.",
          {"center_m": d("bar.com_in_hat_frame_m"), "orientation": "identity (bar axis along +y)"},
          "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S04",
          "upper-back/shoulder-girdle placement, posterior of the trunk axis",
          "placement sensitivity +/- " + n(INPUTS["bar"]["placement_sensitivity_m"]) + " m in x and z",
          "RES-83 must not silently move the nominal; any change is an authority amendment."),
        D("UB-08", "Combined HAT+bar mass, COM and inertia about the combined COM.",
          {"mass_kg": d("hat_bar_system.mass_kg"), "com_m": d("hat_bar_system.com_m"),
           "inertia_about_com_kg_m2": d("hat_bar_system.inertia_about_com_kg_m2")},
          "kg / m / kg m^2", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01;S04",
          "rigid HAT (engineering posture) and rigid bar at the engineering placement UB-07; combination uses exact parallel-axis identity",
          "covered by placement sensitivity",
          "The sagittal-plane relevant inertia is Iyy = " + n(d("hat_bar_system.inertia_about_com_kg_m2")[1][1]) + " kg m^2; transverse (pitch-axis) values are larger because of the 2.2 m bar."),
        D("UB-09", "Arm-fold disclosure.",
          {"elbow_flexion_deg": d("hat.elbow_flexion_deg"),
           "elbow_interior_angle_deg": d("hat.elbow_interior_angle_deg")},
          "deg", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01",
          "geometric consequence of frozen hand placement and published arm lengths",
          "covered by grip-width and wrist-offset sensitivity",
          "The reduced HAT inertially represents a fixed bar-hold; it is not a claim about achievable articulated elbow angles."),
        D("UB-10", "No arm swing, no bar roll, no bar compliance.",
          "arms/hands rigidly attach to the bar; bar is rigidly attached to HAT in V1; sleeve rotation, bar flex and hand compliance are outside V1",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S04;S16",
          "task definition; system authority section 8", "—",
          "Any future arm-swing or bar-compliance variant is a new model revision."),
        D("UB-11", "System COM versus athlete COM.",
          "SYSTEM_COM (athlete + rigid bar, 99 kg) is the primary mechanics authority; ATHLETE_COM is secondary/report-only",
          "—", "PHYSICS_IDENTITY", "—", "carried-bar closure of the airborne system",
          "—", "Force-impulse and ballistic identities use SYSTEM_COM and 99 kg."),
    ],
    "load_bar": [
        D("LB-01", "Bar mass.", d("bar.mass_kg"), "kg", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-02", "Bar total length.", d("bar.length_m"), "m", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-03", "Bar grip-section diameter.", INPUTS["bar"]["BAR_GRIP_DIAMETER_M"], "m", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-04", "Grip section length.", INPUTS["bar"]["BAR_GRIP_SECTION_LENGTH_M"], "m", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-05", "Sleeve diameter.", INPUTS["bar"]["BAR_SLEEVE_DIAMETER_M"], "m", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-06", "Sleeve length (each).", INPUTS["bar"]["BAR_SLEEVE_LENGTH_M"], "m", "LITERATURE_DIRECT", "S04", "IWF men's bar standard", "—", ""),
        D("LB-07", "Composite inertial surrogate construction.",
          {"shaft_length_m": INPUTS["bar"]["BAR_SHAFT_LENGTH_M"], "shaft_diameter_m": INPUTS["bar"]["BAR_GRIP_DIAMETER_M"],
           "sleeves": [INPUTS["bar"]["BAR_SLEEVE_LENGTH_M"], INPUTS["bar"]["BAR_SLEEVE_DIAMETER_M"]],
           "rho_eff_kg_m3": d("bar.rho_eff_kg_m3"), "m_shaft_kg": d("bar.m_shaft_kg"),
           "m_sleeve_each_kg": d("bar.m_sleeve_each_kg")},
          "m / kg/m^3 / kg", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S04",
          "coaxial stepped-cylinder surrogate; rho_eff chosen so total mass equals exactly 20 kg",
          "declared alternative surrogate: uniform 2.200 m x 0.028 m rod (non-IWF) with I_transverse " + n(d("bar_uniform_rod_surrogate.I_transverse_kg_m2")) + " kg m^2",
          "A uniform 2.2 m x 28 mm rod must never be presented as the IWF bar geometry."),
        D("LB-08", "Composite bar inertia about its COM (bar axis along y).",
          {"I_transverse_kg_m2": d("bar.I_transverse_kg_m2"), "I_axis_kg_m2": d("bar.I_axis_kg_m2")},
          "kg m^2", "PHYSICS_IDENTITY", "S04", "analytic stepped-cylinder inertia",
          "surrogate-shape sensitivity: uniform-rod case; sleeve/shaft mass redistribution +/-10%",
          "Bar pitch inertia materially exceeds a uniform-rod estimate (mass concentration in the sleeves)."),
        D("LB-09", "Bar collision geometry.",
          "composite collision representation matching LB-07 dimensions (grip/shaft segment plus two sleeves); exact MuJoCo primitive choice is a RES-83 implementation detail; bar-floor collision physically enabled and its contact is a task failure",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S04",
          "system authority section 8; COLLISION_CONTACT_POLICY", "—",
          "No disabled bar shell may simultaneously serve as evidence for a prohibited-contact claim."),
        D("LB-10", "Attachment semantics.",
          "rigid attachment to HAT in V1; no bar roll/compliance; intentional bar/HAT/hand attachment contacts excluded from the fall/prohibited-contact register",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S04;S16", "task definition", "—", ""),
    ],
    "joint_rom": [
        D("JC-01", "World axis convention.",
          {"+x": "anterior/forward", "+y": "athlete left", "+z": "up"}, "—", "PHYSICS_IDENTITY", "—",
          "system authority section 5", "—", "Right-handed frame."),
        D("JC-02", "Root joint semantics.",
          "unconstrained planar base: root_tx, root_tz, root_ry with zero stiffness, zero damping, zero armature and no positional catch; NOT a 6-DOF free root",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "system authority section 7",
          "—", "Lateral translation, roll and yaw are structurally removed; removed DOFs must never be called 'free'."),
        D("JC-03", "Trunk-pelvis sagittal hinge.",
          {"semantic": "TRUNK_PELVIS_SAGITTAL_HINGE (legacy code name 'lumbar' permitted only with this semantic exposed)",
           "range_rad": INPUTS["rom_rad"]["trunk_pelvis_hinge"],
           "range_deg": [-35.0, 35.0]},
          "rad / deg", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S19",
          "aggregate reduced-model trunk-pelvis flexion-extension; not a literal lumbar-spine joint",
          "sensitivity on the reduced bound is part of the strategy-envelope study, not a calibration to exceed",
          "Explicit reduced-model engineering bound; must not be presented as measured lumbar ROM."),
        D("JC-04", "Hip structural ROM.", {"range_rad": INPUTS["rom_rad"]["hip"], "range_deg": [-20.0, 130.0]},
          "rad / deg", "HUMAN_ANATOMY_REFERENCE", "S19", "general-human hip flexion/extension capacity",
          "—", "Structural capability bound, not a technique target."),
        D("JC-05", "Knee structural ROM.", {"range_rad": INPUTS["rom_rad"]["knee"], "range_deg": [0.0, 140.0]},
          "rad / deg", "HUMAN_ANATOMY_REFERENCE", "S19", "general-human knee flexion capacity",
          "—", "No nominal hyperextension; reverse-knee geometry is structurally impossible under the V3 coordinate authority."),
        D("JC-06", "Ankle structural ROM.", {"range_rad": INPUTS["rom_rad"]["ankle"], "range_deg": [-55.0, 45.0]},
          "rad / deg", "HUMAN_ANATOMY_REFERENCE", "S19", "weight-bearing dorsiflexion ~39-45 deg; soccer jump-landing peaks ~32-38 deg",
          "—", "The former +20 deg dorsiflexion cap is withdrawn as too restrictive for a structural human envelope."),
        D("JC-07", "MTP structural ROM.", {"range_rad": INPUTS["rom_rad"]["mtp"], "range_deg": [-30.0, 90.0]},
          "rad / deg", "HUMAN_ANATOMY_REFERENCE", "S19", "general-human first-MTP dorsiflexion capacity",
          "—", "Negative is plantarflexion; positive is toe dorsiflexion."),
        D("JC-08", "Sagittal joint sign conventions.",
          {"root_ry": "+ about +y = forward whole-body pitch",
           "trunk_pelvis": "+ about +y = forward trunk flexion relative to pelvis",
           "hip": "axis -y, +q = hip flexion (knee moves anteriorly)",
           "knee": "axis +y, +q = knee flexion (ankle moves posteriorly relative to knee)",
           "ankle": "axis -y, +q = dorsiflexion, -q = plantarflexion",
           "mtp": "axis -y, +q = toe dorsiflexion/extension"},
          "—", "PHYSICS_IDENTITY", "—", "system authority section 5; deterministic FK derivation",
          "—", "Propulsion must reduce hip/knee flexion, drive ankle negative (plantarflexion) and permit positive MTP dorsiflexion in the forefoot/toe rocker."),
        D("JC-09", "Analytic FK sign probes (mandatory deterministic validation).",
          {"root_ry_probe": "root_ry = +10 deg with all joints zero: a point initially on +z above the root moves to +x by L*sin(10 deg); COM x increases",
           "hip_probe": "hip = +10 deg (axis -y): knee joint x increases by L_thigh*sin(10 deg) (anterior)",
           "knee_probe": "knee = +10 deg (axis +y): ankle joint x decreases by L_shank*sin(10 deg) (posterior)",
           "ankle_probe": "ankle = +10 deg (axis -y): toe-tip z increases by L_foot*cos(ankle_rest)*sin(10 deg) (dorsiflexion)",
           "mtp_probe": "mtp = +10 deg (axis -y): toe-tip z increases relative to the forefoot (dorsiflexion)",
           "trunk_probe": "trunk_pelvis hinge = +10 deg about +y: head/vertex x increases by L_MIDH_vertex*sin(10 deg) (forward flexion)",
           "root_tx_probe": "root_tx = +0.01 m: all body x coordinates increase by 0.01 m exactly",
           "root_tz_probe": "root_tz = +0.01 m: all body z coordinates increase by 0.01 m exactly"},
          "—", "PHYSICS_IDENTITY", "—", "analytic forward kinematics of the frozen topology",
          "—", "RES-83 must implement these probes as tests; any sign disagreement is a build failure, not a tuning problem."),
        D("JC-10", "ROM values are capability bounds, not targets.",
          "no controller may chase a structural limit; joint-limit hits and saturated-limit dwell are telemetry warnings",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S19", "system authority section 14", "—", ""),
    ],
    "foot_mtp": [
        D("FM-01", "Frozen foot abstraction.",
          "per foot: hindfoot body, forefoot body welded/fixed to the hindfoot in V1 (separate geometry/inertia, no midtarsal DOF), toe/phalanx body, one sagittal MTP hinge; ankle hinge connects shank -> hindfoot",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02", "system authority section 6; S02 three-segment model",
          "locked-midfoot alternative required (FM-03)", "The old single rigid box foot is rejected."),
        D("FM-02", "Locked midfoot classification.",
          "a rigid arch / locked midfoot is a MATERIAL MODEL-FORM UNCERTAINTY, not harmless omission",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02", "multi-segment foot literature",
          "mandatory compliant/articulated-midfoot alternative", "Rigid-foot assumptions can materially distort ankle ROM and quasi-stiffness."),
        D("FM-03", "Required midfoot alternative sensitivity.",
          {"requirement": "final qualification must compare the locked-midfoot Plant against a plausible compliant/articulated-midfoot alternative (at least one bounded sagittal midtarsal DOF or equivalent compliant coupling with documented range/stiffness)",
           "change_triggers_reopening_RES83": ["H2", "ankle/MTP work and power", "CoP migration", "toe-off timing", "landing absorption", "control feasibility"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02", "system authority section 6",
          "required", "If locking the midfoot materially changes these outputs, the V1 locked-midfoot Plant is not qualified."),
        D("FM-04", "Foot segment masses.",
          d("foot.segment_masses_kg"), "kg", "LITERATURE_DIRECT", "S01;S02",
          "de Leva whole-foot mass fraction 0.0137 x 79 kg, split 43.2/42.4/14.4 % per S02",
          "foot-inertia sensitivity 0.5x/1.5x", "Sum equals the de Leva whole-foot mass."),
        D("FM-05", "MTP nominal axis location and toe length.",
          {"MTP_X_FROM_HEEL_M": d("foot.mtp_x_from_heel_m"), "TOE_LENGTH_M": INPUTS["frozen_geometry"]["TOE_LENGTH_M"],
           "ratio_of_foot_length": INPUTS["frozen_geometry"]["MTP_X_FROM_HEEL_RATIO_OF_FOOT_LENGTH"]},
          "m / —", "LITERATURE_INFORMED_SYNTHETIC", "S02;S20",
          "first-MTP fulcrum locations span ~70-79% of foot length in published data",
          "MTP location sensitivity [0.70, 0.79] x foot length",
          "0.75 is a reduced-axis nominal, not subject-specific anatomy."),
        D("FM-06", "Plantar contact regions and dimensions (heel / forefoot / toe).",
          d("foot.contact_regions"), "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02;S18",
          "reduced contact patches matching the frozen foot partition; heel breadth is materially below ball breadth (S18)",
          "patch dimension sensitivity +/- 0.010 m; only these regions may create valid support",
          "The three regions are independently observable; RES-84 builds the support hull/CoP authority from their active contacts."),
        D("FM-07", "Foot frame, joint centers and segment partition.",
          {"ankle_joint_center": [0.0, 0.0, 0.0], "mid_tarsal_x_from_heel_m": d("foot.mid_tarsal_x_from_heel_m"),
           "mtp_x_from_heel_m": d("foot.mtp_x_from_heel_m"), "toe_tip_x_from_heel_m": d("foot.toe_tip_x_from_heel_m"),
           "segment_lengths_m": d("foot.segment_lengths_m"), "segment_com_ankle_frame_m": d("foot.segment_com_ankle_frame_m")},
          "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02",
          "S02 joint-chain proximal conventions applied to the frozen reduced geometry",
          "midtarsal placement sensitivity +/- 0.010 m; segment-inertia sensitivity 0.5x/1.5x",
          "Assembled foot COM cross-check against the de Leva whole-foot COM is declared in AB-15."),
        D("FM-08", "Foot segment inertia rule.",
          {"rule": INPUTS["foot_segments"]["inertia_scaling_rule"],
           "segment_inertia_about_com_kg_m2": d("foot.segment_inertia_about_com_kg_m2")},
          "kg m^2", "LITERATURE_DIRECT", "S02", "S02 Table 3 relative tensors scaled by m^(5/3)",
          "foot-inertia sensitivity 0.5x/1.5x; midfoot alternative", "Diagonal terms used with a declared axis mapping; off-diagonal products are not silently imported into the sagittal model."),
        D("FM-09", "Passive MTP baseline mechanics.",
          {"neutral_rad": INPUTS["materials"]["MTP_NEUTRAL_RAD"], "k_nominal_Nm_per_rad": INPUTS["materials"]["MTP_K_NOMINAL_NM_PER_RAD"],
           "c_nominal_Nms_per_rad": INPUTS["materials"]["MTP_C_NOMINAL_NMS_PER_RAD"]},
          "N m/rad / N m s/rad", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S10",
          "predictive gait-model prior; not a CMJ measurement",
          "k set " + n(INPUTS["materials"]["MTP_K_SENSITIVITY_NM_PER_RAD"]) + "; c set " + n(INPUTS["materials"]["MTP_C_SENSITIVITY_NMS_PER_RAD"]) + "; zero-passive case (k=0,c=0)",
          "Passive values are engineering priors only; material dependence reopens authority."),
        D("FM-10", "Active MTP channel.",
          "one bounded net plantarflexor/resistive moment per foot in parallel with the passive baseline; reduced net moment, not a literal single-muscle actuator; no hidden high-power toe motor or arbitrary flight-energy injection",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S08;S09",
          "MTP restriction reduces CMJ height/impulse; intrinsic foot muscle activity drives MTP stiffness; the actuator channel is a reduced design decision informed by that evidence",
          "final torque/rate/power caps owned by RES-85; supported-phase saturation telemetry mandatory",
          "A passive-only MTP is NOT sufficient as the sole mechanism for a human-valid maximal-CMJ claim."),
        D("FM-11", "MTP work accounting.",
          "qualification must report passive MTP work, active MTP work, total MTP work/power and an active-vs-passive sensitivity, proving no double-counting of distal power and no hidden toe-energy source",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S08;S09;S10", "S09/S10 mechanism and double-count risk",
          "active-vs-passive separation required in every qualification report", "Separation must be demonstrated, not asserted."),
        D("FM-13", "Sole plane and no-subsole-geometry rule.",
          {"sole_plane_z_in_foot_frame_m": d("foot.sole_plane_z_m"),
           "rule": d("foot.no_subsole_geometry_rule")},
          "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02",
          "locked-midfoot reduced geometry; all three contact patches are planar on the sole plane",
          "—",
          "The foot's visual/collision body above the sole is a RES-83 implementation detail, but no collision geom may protrude below the sole plane, and only the frozen patches may create valid support."),
        D("FM-12", "Foot geometry sensitivity.",
          "ankle x +/- 0.010 m; MTP location span 0.70-0.79 L; foot length +/- 0.010 m; midfoot alternative; segment inertia 0.5x/1.5x",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02;S18;S20;S21",
          "frozen foot geometry", "declared", "No sensitivity may be silently omitted from the qualification manifest."),
    ],
    "stance_lab": [
        D("SL-01", "Model leg-plane separation.",
          {"leg_plane_centerlines_y_m": INPUTS["topology"]["leg_plane_centerlines_y_m"],
           "separation_m": INPUTS["topology"]["leg_plane_separation_m"]},
          "m", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "sagittal reduction geometry",
          "plane-separation sensitivity only as engineering geometry (+/- 0.010 m)",
          "0.170 m is NOT an elite-soccer CMJ stance-width claim; true stance width and lateral balance are outside V1."),
        D("SL-02", "Foot orientation in the reduced model.",
          "feet parallel (yaw removed); no toe-out angle is modeled",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "yaw structurally removed", "—",
          "Do not run a biological stance-width sensitivity by sliding feet laterally without a coherent 3-D pelvis/hip model."),
        D("SL-03", "Laboratory context.",
          "indoor force-plate setting with training shoes; not cleat-on-turf",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "task context of use", "—",
          "Field/turf/cleat validity is outside the claim."),
        D("SL-04", "Force-plate measurement chain.",
          {"plates": "dual force plates", "export_rate_hz": 1000, "rule": ">=1000 Hz canonical comparison export with documented anti-aliasing/filter path; raw native signals retained"},
          "Hz", "LITERATURE_INFORMED_SYNTHETIC", "S11;S12;S22",
          "force-platform sampling literature recorded in the system authority", "—",
          "Native simulator state/contact resolution remains event authority."),
        D("SL-05", "Countermovement depth and stance are self-selected.",
          "no single ideal knee/hip depth is frozen; professional protocols commonly yield ~60-90 deg knee flexion while elite data show legitimate strategy variability",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S06;S07;S16",
          "system authority sections 12 and 14", "strategy-envelope study required",
          "Microscopic/noise-only dips must be rejected, but no elite squat depth may be hard-coded as optimal."),
        D("SL-06", "Relative-to-quiet-stance reporting.",
          "all performance and force metrics are reported relative to the quiet-standing reference, with raw and filtered traces retained",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S11;S12", "processing-sensitivity literature", "—", ""),
    ],
    "collision": [
        D("CC-01", "Valid floor support.",
          "only the active plantar heel / forefoot / toe regions of either foot may create valid floor support",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S02;S22", "system authority section 9",
          "contact-parameter sensitivity required", "Landing may legitimately begin toe/forefoot-first before heel."),
        D("CC-02", "Prohibited / fall contact.",
          "pelvis, HAT, thigh, shank or bar contact with the floor is prohibited/fall contact; body/bar-floor contact is a task failure",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "system authority sections 9 and 16",
          "—", "No disabled collision shell may simultaneously serve as evidence for a prohibited-contact claim."),
        D("CC-03", "Collision enablement matrix (summary).",
          {"enabled": ["plantar regions vs floor", "bar vs floor (fail register)", "bar vs nonattached lower limb", "opposite-foot collisions", "nonadjacent self-collision where physically possible"],
           "excluded_with_rationale": ["intentional bar/HAT/hand attachment contacts", "adjacent anatomical parent-child pairs where self-contact is impossible"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "system authority section 9",
          "representative-pose collision audit mandatory: standing, deep legal countermovement, takeoff extension, flight, touchdown, landing absorption, recovery",
          "All exclusions machine-readable with rationale."),
        D("CC-04", "No artificial support or catch.",
          "no artificial root limits, root springs, root damping, hidden supports or catch planes; root DOF passives are exactly zero",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "system authority sections 7 and 15",
          "zero-value verification required", "State overrides/freezes fail NO_ARTIFICIAL_SUPPORT."),
        D("CC-05", "Contact dimension (condim) classification.",
          {"nominal_plantar_floor": 4, "nominal_other_contacts": 3,
           "sensitivity": [3, 4, 6],
           "rationale": "plantar-floor contacts carry sliding + torsional friction authority; other contacts are declared nominal"},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "MuJoCo contact model semantics",
          "condim sensitivity must be executed if enabled dimensions differ from nominal",
          "Contact authority is never reduced to one scalar friction coefficient."),
        D("CC-06", "Sliding friction.",
          {"mu_slide_nominal": INPUTS["constants"]["mu_slide_nominal"], "sensitivity": INPUTS["constants"]["mu_slide_sensitivity"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22",
          "sports shoe/surface measurements span materially different values by outsole and method",
          "mandatory sweep [0.50, 1.50]", "0.90 is not a measured universal athletic-surface truth."),
        D("CC-07", "Torsional friction.",
          {"status": "numeric value DEFERRED_TO_LATER_AUTHORITY (RES-84)",
           "ownership": "RES-84 owns the numeric value and its solution-verification justification",
           "qualification_domain_frozen_here": "must be selected by solution verification, declared in candidate identity, sensitivity-tested, and shown not to create artificial spin or yaw-drift authority"},
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "MuJoCo friction-cone semantics",
          "required alongside CC-05/CC-06", "Deferral is bounded: value + sensitivity domain are frozen by RES-84, not silently chosen at run time."),
        D("CC-08", "Rolling friction.",
          {"nominal": 0.0, "rationale": "nominal foot contact is box-like; rolling friction is not needed for box-floor contact",
           "condition": "if any round/capsule plantar contact geometry is introduced, a numeric rolling-friction value becomes DEFERRED_TO_LATER_AUTHORITY (RES-84) and must be sensitivity-tested"},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "MuJoCo rolling-friction semantics",
          "required if round contact geoms are introduced", "Nominal zero is a statement about the nominal geometry, not a claim about shoes."),
        D("CC-09", "Contact margin and gap.",
          {"margin": "numeric value DEFERRED_TO_LATER_AUTHORITY (RES-84); semantics frozen: included in the takeoff clearance guard max(2 mm, margin + verified numerical/penetration allowance)",
           "gap": "numeric value DEFERRED_TO_LATER_AUTHORITY (RES-84); semantics frozen: zero nominal or declared and included in clearance accounting"},
          "m", "DEFERRED_TO_LATER_AUTHORITY", "S22", "MuJoCo margin/gap semantics; EVENT_MEASUREMENT_BOUNDARY",
          "RES-84 must seal exact evaluated values in the candidate identity", "Margin/gap may never silently shrink the takeoff clearance definition."),
        D("CC-10", "solref ownership.",
          {"owner": "RES-84 / RES-86",
           "provisional_rule": "any provisional standing-contact setting is labeled PROVISIONAL_NUMERICAL and cannot silently become final candidate authority",
           "must_survive": ["timestep refinement", "impact/contact sensitivity", "no qualitative task reversal"]},
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "MuJoCo contact compliance",
          "mandatory solution-verification study", "Extremely stiff contact is not automatically more physical."),
        D("CC-11", "solimp ownership.",
          {"owner": "RES-84 / RES-86",
           "provisional_rule": "provisional values labeled PROVISIONAL_NUMERICAL; final values selected by solution verification, never by labeling them human soft tissue"},
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "MuJoCo contact impedance",
          "mandatory solution-verification study", "Same bounded-deferral rule as CC-10."),
        D("CC-12", "Penetration authority.",
          {"numeric_tolerance": "DEFERRED_TO_LATER_AUTHORITY (RES-84/RES-86 solution verification)",
           "frozen_constraints": ["bounded penetration with no tunneling", "no contact inversion/chatter exploitation", "penetration allowance declared in the clearance guard", "the historical project candidate hard cap 0.010 m remains RES-82-owned and is NOT re-frozen here"]},
          "m", "DEFERRED_TO_LATER_AUTHORITY", "S22", "solution verification; RES-82 project hard-rule candidate",
          "declared tolerance in candidate identity", "Penetration evidence must be reported raw, not only aggregated."),
        D("CC-13", "Engineered-contact realism rule.",
          "final candidate must show no material dependence on the declared contact/friction sensitivity and no uncontrolled slip, artificial sticking, friction-cone saturation or solver-dependent qualitative reversal",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "system authority section 10",
          "material qualitative reversal blocks final authority until explained or narrowed", "No numerical contact choice may be presented as a sports-science measurement."),
    ],
    "topology": [
        D("PT-01", "Model revision identity.", {"MODEL_REVISION": INPUTS["model"]["MODEL_REVISION"], "MODEL_ID": INPUTS["model"]["MODEL_ID"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "successor Plant identity", "—", ""),
        D("PT-02", "Body list including world.", INPUTS["topology"]["bodies"], "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S01;S04",
          "world, pelvis, HAT, bar, bilateral thigh/shank/hindfoot/forefoot/toe",
          "—", "Expected NBODY including world = " + str(INPUTS["topology"]["NBODY_including_world"]) + "."),
        D("PT-03", "Joint topology and generalized dimensions.",
          {"joints": INPUTS["topology"]["joints"], "NQ": INPUTS["topology"]["NQ"], "NV": INPUTS["topology"]["NV"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "planar root + trunk-pelvis hinge + bilateral lower limb chain",
          "—", "3 root + 1 trunk + 2*4 limb DOF = 12."),
        D("PT-04", "Actuator channel topology.",
          {"channels": INPUTS["topology"]["actuator_channels"], "NU": INPUTS["topology"]["NU"]},
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S08;S09", "9 physical net-moment channels incl. bilateral MTP",
          "final torque/rate/power limits owned by RES-85", "The superseded 7-channel V2 topology is not successor authority."),
        D("PT-05", "Planar-root consequence and nominal symmetry.",
          "because lateral translation, roll and yaw are absent, V1 nominal sagittal actions must be bilaterally symmetric to numerical tolerance",
          "—", "PHYSICS_IDENTITY", "—", "system authority section 7",
          "bilateral tolerance declared and audited", "Materially asymmetric corrective control requires a future true 3-D/6-DOF Plant."),
        D("PT-06", "Out-of-plane reaction audit (V1 fail-closed rule).",
          "qualification must audit out-of-plane contact/reaction quantities (Fy, roll/yaw moments where available) and demonstrate they are negligible; if omitted DOFs materially support the trajectory, V1 fails",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "mission freeze item 7; system authority section 7",
          "mandatory audit in every qualification report", "External reaction quantities are evidence, never a control channel."),
        D("PT-07", "Passive mechanics defaults.",
          "hip/knee/ankle/trunk-pelvis passive stiffness and damping default to 0 at Plant authority level; root passives exactly 0; any numerical damping needed for stability is declared, justified, sensitivity-tested and classified as numerical regularization",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S22", "system authority section 15",
          "any non-zero value requires a declared justification", "R001 major-joint passive stiffness/damping may not be carried forward as human physiology."),
        D("PT-08", "Body inertial provenance (summary table).",
          {"pelvis": "AB-08", "HAT": "UB-03..UB-06", "bar": "LB-07..LB-08",
           "thigh": "AB-14", "shank": "AB-14", "hindfoot/forefoot/toe": "FM-04, FM-07, FM-08"},
          "—", "LITERATURE_DIRECT", "S01;S02;S04", "per-body authority mapping",
          "—", "No body inertia value may live only in implementation code."),
        D("PT-09", "No candidate creation in RES-95.",
          "RES-95 freezes model authority only; candidate authorization remains RES-90",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "—", "mission freeze item; Linear RES-90 boundary",
          "—", "No successor candidate ID is created here."),
    ],
    "event": [
        D("EM-01", "Primary COM signal.", "SYSTEM_COM (athlete + rigid 20 kg bar) = primary mechanics authority; ATHLETE_COM = secondary report/comparability signal",
          "—", "PHYSICS_IDENTITY", "—", "carried-bar closure", "—", "All event predicates use SYSTEM_COM."),
        D("EM-02", "Primary takeoff time.",
          "TAKEOFF_OCCURRENCE = the final transition from at least one active legal plantar support contact to zero active legal plantar support contacts, with interpolated/contact-event time if available",
          "—", "PHYSICS_IDENTITY", "S17", "Linear system authority section 12, physical takeoff (no RES-82 E-number label)",
          "—", "This is the physical takeoff time used for H2 and takeoff velocity."),
        D("EM-03", "Takeoff confirmation.",
          "TAKEOFF_CONFIRMATION = a later fail-closed confirmation that bilateral geometric clearance exceeds the numerical guard, SYSTEM_COM_vz(TAKEOFF_OCCURRENCE) > 0, no prohibited contact exists, and no legal plantar recontact occurs throughout the genuine-flight dwell",
          "—", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S17", "Linear system authority section 12, takeoff occurrence/confirmation split",
          "dwell and clearance guard sensitivity required downstream",
          "If confirmation fails the candidate takeoff occurrence is rejected, never shifted."),
        D("EM-04", "Confirmation must not shift the takeoff timestamp.",
          "TAKEOFF_CONFIRMATION must never replace TAKEOFF_OCCURRENCE as the H2 time origin",
          "—", "PHYSICS_IDENTITY", "—", "mission freeze item 10; system authority section 13",
          "—", "Prevents a delayed-clearance threshold from artificially lowering H2."),
        D("EM-05", "Primary jump-height metric.",
          "H2 = SYSTEM_COM_z(apex) - SYSTEM_COM_z(TAKEOFF_OCCURRENCE)",
          "m", "PHYSICS_IDENTITY", "—", "direct last-legal-contact-loss to apex displacement",
          "—", "Mandatory cross-checks: H_ballistic = vz_takeoff^2 / (2g); H_impulse from total vertical impulse / 99 kg."),
        D("EM-06", "Genuine flight dwell.",
          "starting from the candidate TAKEOFF_OCCURRENCE, zero legal plantar contacts must persist for at least 0.050 s; within the confirmation window both feet establish positive clearance above the numerical guard and no prohibited contact occurs",
          "s", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "S17", "Linear system authority section 12, genuine flight",
          "dwell sensitivity (e.g. 0.030/0.050/0.080 s) required downstream",
          "The 50 ms dwell is an engineering debounce, not a measured human constant."),
        D("EM-07", "Clearance guard.",
          "clearance guard = max(2 mm, contact_margin + verified numerical penetration/error allowance); exact evaluated value sealed by RES-84",
          "m", "DEFERRED_TO_LATER_AUTHORITY", "S22", "system authority section 12",
          "RES-84 seals exact value; guard participates in confirmation only",
          "The clearance guard is a confirmation tolerance, not the definition of the takeoff instant."),
        D("EM-08", "Apex definition.",
          "inside genuine flight, SYSTEM_COM_vz crosses positive -> nonpositive; compute the zero crossing by interpolation; no arbitrary apex dwell",
          "—", "PHYSICS_IDENTITY", "—", "Linear system authority section 12, apex", "—", ""),
        D("EM-09", "Touchdown definition.",
          "first renewed valid plantar-floor contact after genuine flight; toe/forefoot-first is valid; body/bar-floor contact is not",
          "—", "PHYSICS_IDENTITY", "S15", "Linear system authority section 12, physical touchdown", "—",
          "Landing absorption must be realized by the calibrated contact model and human joint motion, not a hidden vertical clamp."),
        D("EM-10", "Measurement takeoff comparator.",
          "bilateral per-foot vertical GRF threshold 10 N with 0.010 s persistence (the RES-82 F_thr convention; an equivalent total-GRF display may be reported) is comparator/diagnostic only and never defines the simulated physical event",
          "N / s", "LITERATURE_INFORMED_SYNTHETIC", "S17", "takeoff-threshold comparison study; RES-82 EVENT_CONTRACT F_thr",
          "comparator threshold sensitivity is a reporting obligation", ""),
        D("EM-11", "Force-plate comparison export.",
          "resampled at >=1000 Hz (1000 Hz canonical) with a documented anti-aliasing/filter path; raw native signals retained for independent recomputation",
          "Hz", "LITERATURE_INFORMED_SYNTHETIC", "S11", "force-platform processing literature",
          "processing sensitivity is a reporting obligation", "Native simulator states/contacts remain event authority."),
        D("EM-12", "Event chain and dwell semantics (with explicit takeoff supersession).",
          {"retained_from_RES82": "E1-E12 chain, PHYSICAL_TIME dwell convention, negative controls, cross-event independence",
           "superseded_for_successor": "the clearance-gated historical takeoff anchor; for the successor the H2 time origin is TAKEOFF_OCCURRENCE (final legal plantar contact loss), and clearance/dwell survive only as TAKEOFF_CONFIRMATION",
           "label_rule": "RES-95 does not use RES-82 E-number labels for takeoff/flight/apex/touchdown so downstream readers cannot collide the two numbering systems"},
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S22", "RES-82 EVENT_CONTRACT_E1_E12.json; DWELL_SEMANTICS.json; Linear system authority section 12",
          "downstream sensitivity execution owned by later RES",
          "This supersession is explicit so zero unresolved conflict remains between RES-82 labels and the controlling Linear takeoff semantics."),
        D("EM-13", "No clearance-defined delayed H2 takeoff.",
          "the H2 time origin is the last legal plantar contact loss; a later clearance-defined sample must never become the H2 origin",
          "—", "PHYSICS_IDENTITY", "—", "mission freeze item 10", "—",
          "This closes the historical delayed-takeoff defect class."),
    ],
    "performance": [
        D("PA-01", "Anti-triviality floor.", {"H_ANTI_TRIVIALITY_FLOOR_M": 0.15,
           "meaning": "negative-control / trivial-hop rejection only; necessary but NOT sufficient for elite-context qualification"},
          "m", "LITERATURE_INFORMED_SYNTHETIC", "S13", "RES-82 PF-1 candidate; mixed-athlete +20 kg evidence",
          "—", "Retained as the only frozen numeric height gate."),
        D("PA-02", "Elite +20 kg direct H2 target.",
          {"ELITE_SOCCER_PLUS20_DIRECT_H2_TARGET": "NOT_FROZEN",
           "ELITE_SOCCER_PLUS20_DIRECT_H2_HARD_GATE": "DEFERRED_PENDING_METHOD_MATCHED_MAPPING",
           "H_ANTI_TRIVIALITY_FLOOR_M": 0.15},
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S07;S11;S12;S13",
          "method heterogeneity across unloaded impulse-momentum, +20 kg flight-time and +20 kg LVT studies",
          "RES-85/91 must produce the mapping before any hard gate",
          "No fabricated conversion when uncertainty cannot be bounded."),
        D("PA-03", "Withdrawn performance authority (superseded, not current).",
          {"0.200 m elite-context target": "WITHDRAWN as qualification authority; remains at most a non-authoritative historical notation",
           "0.280-0.400 m expected band": "WITHDRAWN",
           "0.350 m nominal target": "WITHDRAWN"},
          "m", "DEFERRED_TO_LATER_AUTHORITY", "S07;S11;S12;S13;S14",
          "adversarial correction recorded in the Linear system authority",
          "—", "These values must not reappear as current authority in any downstream artifact."),
        D("PA-04", "Mandatory method-matched comparator analysis.",
          {"methods_to_compare": ["direct SYSTEM_COM takeoff->apex", "impulse-momentum", "takeoff-velocity", "flight-time", "bar/LVT displacement"],
           "requirement": "RES-85/91 predeclare the mapping before any elite-performance hard gate is created"},
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S07;S11;S12", "system authority section 13",
          "owned by RES-85/RES-91", "Results far below comparator evidence trigger scientific review, not automatic failure."),
        D("PA-05", "Controller objective.",
          "maximize physically valid direct SYSTEM_COM takeoff->apex H2 subject to the frozen human actuation, energy/work, joint-limit, contact, landing and recovery constraints",
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S16;S22", "system authority section 13",
          "—", "Not tune to a fabricated height target."),
        D("PA-06", "Report-only comparators.",
          ["countermovement depth", "knee/hip/ankle/MTP ROM", "eccentric/braking/propulsive durations",
           "peak and mean GRF normalized to athlete and system mass", "joint moments/powers/work",
           "total and joint impulse/work contributions", "peak landing force (method-matched pending)"],
          "—", "LITERATURE_INFORMED_SYNTHETIC", "S06;S07;S15;S16", "system authority sections 13-16",
          "report-only until method-matched data exist", ""),
    ],
    "deferred": [
        D("DF-01", "Contact numerical calibration.",
          "solref, solimp, margin, gap, torsional-friction and rolling-friction numeric values, penetration tolerance",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-84 / RES-86",
          "classification and qualification domain frozen in COLLISION_CONTACT_POLICY CC-07..CC-12",
          "Provisional settings must be labeled PROVISIONAL_NUMERICAL."),
        D("DF-02", "Takeoff clearance guard exact value.", "max(2 mm, contact_margin + verified numerical/penetration allowance) evaluated and sealed",
          "m", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-84", "sealed in candidate identity", "Confirmation-only semantics frozen here."),
        D("DF-03", "MTP active moment limits.", "torque cap, rate limit, power limit and allowed stance-phase action for the reduced net MTP moment",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S08;S09", "RES-85",
          "must be validated against jump/foot mechanics; saturation telemetry mandatory",
          "Must not become a hidden high-power toe motor."),
        D("DF-04", "Major-joint actuator limits.", "hip/knee/ankle/trunk torque caps, torque-rate limits and activation/smoothing constants",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S16;S22", "RES-85",
          "elite isokinetic data are plausibility bounds only; not direct motor constants", ""),
        D("DF-05", "Balance capture and recovery envelopes.", "E11 capture envelope, E12 robust standing envelope and post-E12 observation window",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-87 / RES-91",
          "physical and robustness-calibrated; one-trace/ULP envelopes prohibited", ""),
        D("DF-06", "Landing force gate.", "peak landing force as a hard +20 kg elite scalar gate",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S15", "later method-matched authority",
          "report/validation comparator until method-matched +20 kg data exist", "No numeric transfer from drop-landing or unloaded studies."),
        D("DF-07", "Elite +20 kg H2 mapping.", "method-matched comparator/mapping analysis before any elite hard gate",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S07;S11;S12", "RES-85 / RES-91",
          "required before gate authorization", "See PA-02/PA-04."),
        D("DF-08", "Solver and timestep verification.", "timestep refinement, solver iteration/tolerance sensitivity, contact compliance sweep, friction sweep, MTP passive sweep, midfoot alternative, placement/pose/anthropometry/initial-pose perturbations, deterministic repeatability",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-86 / RES-89 / RES-91",
          "each sensitivity run records event ordering, H2, takeoff velocity, GRF, joint-limit margins, prohibited contacts, saturation, landing capture, final standing",
          "Execution of the frozen sensitivity sets is a downstream obligation; omission is a qualification defect."),
        D("DF-09", "Controller phase machine and calibration.", "state-causal hybrid phase machine, transition hysteresis/persistence and command continuity",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-85",
          "no wall-clock-only transitions; no instantaneous torque cliffs", ""),
        D("DF-10", "Bar placement versus RES-83 collision shells.", "post-implementation non-penetration confirmation in standing and all representative poses; any nominal placement change requires an authority amendment",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S04;S22", "RES-83 + this authority",
          "report-level confirmation; nominal frozen in UB-07", "No silent nominal movement."),
        D("DF-11", "Stance/lateral validation.", "true stance width and lateral balance authority",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "future 3-D/6-DOF Plant program",
          "outside V1 claim", "0.170 m remains a model geometry nominal only."),
        D("DF-12", "Candidate authorization and qualification.", "successor candidate creation, provenance/determinism/test/visual qualification",
          "—", "DEFERRED_TO_LATER_AUTHORITY", "S22", "RES-90 / RES-91 / RES-92 / RES-93",
          "RES-95 creates no candidate", ""),
    ],
}

# --------------------------------------------------------------------------------------
# Artifact metadata
# --------------------------------------------------------------------------------------
ARTIFACTS = {
    "sport_context": dict(
        file="SPORT_CONTEXT_AUTHORITY", title="Sport Context Authority",
        purpose="Frozen context of use for the elite-soccer successor Loaded-CMJ Plant: reference population, task, evidence hierarchy and claim boundary.",
        preamble=[
            "This artifact freezes the sport context and context-of-use (COU) for the successor Plant. It is binding on RES-83/84/85/87/89/90/91 and on any qualification report derived from this model revision.",
            "The context is a synthetic nominal reference, not a claim about any individual athlete or about an exact population mean.",
        ],
        refs=["REFERENCE_ATHLETE_SPEC", "PLANT_TOPOLOGY_AUTHORITY", "PERFORMANCE_AUTHORITY_BOUNDARY", "RES-82 SCIENTIFIC_CLAIM_CEILING.md"]),
    "reference_athlete": dict(
        file="REFERENCE_ATHLETE_SPEC", title="Reference Athlete Specification",
        purpose="Frozen synthetic nominal reference athlete, external load and total mechanical system quantities.",
        preamble=[
            "The reference athlete is a rounded synthetic consensus inside contemporary first-team professional male outfield distributions. It is not a real person and not the exact population mean.",
        ],
        refs=["SPORT_CONTEXT_AUTHORITY", "ANTHROPOMETRY_BSIP_AUTHORITY", "LOAD_BAR_AUTHORITY"]),
    "anthropometry": dict(
        file="ANTHROPOMETRY_BSIP_AUTHORITY", title="Anthropometry and BSIP Authority",
        purpose="Frozen body-segment inertial authority (de Leva-adjusted Zatsiorsky-Seluyanov), geometry, foot partition and reproducibility rules.",
        preamble=[
            "Machine-readable coefficients live in AUTHORITY_INPUTS.json; all numbers in this artifact are recomputed deterministically by build_authority_numbers.py into DERIVED_QUANTITIES.json.",
            "The segment-chain closure check (AB-13) is declared rather than silently repaired: the joint-center-resolved chain overshoots the reference stature by about 3.1 cm, and RES-83 must absorb that in the standing pose, never by rescaling frozen lengths.",
        ],
        refs=["REFERENCE_ATHLETE_SPEC", "FOOT_MTP_MODEL_AUTHORITY", "UPPER_BODY_HAT_BAR_INERTIAL_AUTHORITY", "DERIVED_QUANTITIES.json"]),
    "upper_body": dict(
        file="UPPER_BODY_HAT_BAR_INERTIAL_AUTHORITY", title="Reduced Upper-Body (HAT) and Bar Inertial Authority",
        purpose="Frozen reduced HAT decomposition, fixed bar-hold representation, and the resulting numeric HAT and HAT+bar inertial properties.",
        preamble=[
            "The reduced HAT is a single rigid body. Its inertial properties are computed from de Leva component segments under one frozen engineering bar-hold posture with the parallel-axis theorem and full 3x3 tensors.",
            "Every unmeasured posture or placement parameter is ENGINEERING_NOMINAL_WITH_SENSITIVITY; none is presented as anthropometric truth. Sensitivity cases are computed in DERIVED_QUANTITIES.json (hat_sensitivity).",
        ],
        refs=["ANTHROPOMETRY_BSIP_AUTHORITY", "LOAD_BAR_AUTHORITY", "COLLISION_CONTACT_POLICY", "DERIVED_QUANTITIES.json"]),
    "load_bar": dict(
        file="LOAD_BAR_AUTHORITY", title="External Load (Barbell) Authority",
        purpose="Frozen IWF-style 20 kg composite bar geometry, inertial surrogate, collision embodiment and placement.",
        preamble=[
            "The bar is a separate rigid body with its own mass and inertia. A uniform 2.200 m x 28 mm rod must never be presented as IWF geometry; the nominal surrogate is the documented stepped-cylinder composite, and the uniform rod survives only as a declared sensitivity case.",
        ],
        refs=["REFERENCE_ATHLETE_SPEC", "UPPER_BODY_HAT_BAR_INERTIAL_AUTHORITY", "COLLISION_CONTACT_POLICY"]),
    "joint_rom": dict(
        file="JOINT_COORDINATE_ROM_AUTHORITY", title="Joint Coordinate and ROM Authority",
        purpose="Frozen world/joint coordinate conventions, structural ROM envelope and analytic forward-kinematics sign probes.",
        preamble=[
            "These are structural capability bounds, not technique targets. General-human anatomy, not soccer-specific technique, is authoritative for the limits.",
            "Every joint sign has an analytic FK probe (JC-09) that RES-83 must implement as a deterministic test.",
        ],
        refs=["PLANT_TOPOLOGY_AUTHORITY", "FOOT_MTP_MODEL_AUTHORITY", "COLLISION_CONTACT_POLICY"]),
    "foot_mtp": dict(
        file="FOOT_MTP_MODEL_AUTHORITY", title="Foot and MTP Model Authority",
        purpose="Frozen multi-segment foot abstraction, plantar contact geometry, foot-segment inertia and the passive/active MTP contract.",
        preamble=[
            "The locked-midfoot nominal is a declared material model-form uncertainty with a mandatory compliant/articulated-midfoot alternative in final qualification.",
            "Passive MTP values are engineering priors only; zero-passive and alternative passive-property cases are mandatory, and passive and active MTP work must be reported separately.",
        ],
        refs=["ANTHROPOMETRY_BSIP_AUTHORITY", "JOINT_COORDINATE_ROM_AUTHORITY", "COLLISION_CONTACT_POLICY", "DEFERRED_NUMERICAL_CALIBRATIONS"]),
    "stance_lab": dict(
        file="STANCE_LAB_CONTEXT_AUTHORITY", title="Stance and Laboratory Context Authority",
        purpose="Frozen stance/laboratory context: leg-plane geometry, force-plate chain and reporting conventions.",
        preamble=[
            "The 0.170 m leg-plane separation is reduced-model geometry. It is not an elite-soccer stance-width claim, and it must not be relabeled as one.",
        ],
        refs=["PLANT_TOPOLOGY_AUTHORITY", "EVENT_MEASUREMENT_BOUNDARY", "SPORT_CONTEXT_AUTHORITY"]),
    "collision": dict(
        file="COLLISION_CONTACT_POLICY", title="Collision and Contact Policy",
        purpose="Frozen legal-support/fall-contact boundary and explicit MuJoCo contact-parameter classification with bounded deferrals.",
        preamble=[
            "Contact authority is never reduced to one scalar friction coefficient. Each MuJoCo contact dimension is either frozen, classified engineering-nominal with sensitivity, or explicitly deferred to RES-84/86 with its qualification domain frozen here.",
            "No disabled collision shell may simultaneously serve as evidence for a prohibited-contact claim.",
        ],
        refs=["FOOT_MTP_MODEL_AUTHORITY", "PLANT_TOPOLOGY_AUTHORITY", "DEFERRED_NUMERICAL_CALIBRATIONS", "EVENT_MEASUREMENT_BOUNDARY"]),
    "topology": dict(
        file="PLANT_TOPOLOGY_AUTHORITY", title="Plant Topology Authority",
        purpose="Frozen successor Plant topology: bodies, joints, generalized dimensions, actuation channels and planar-root obligations.",
        preamble=[
            "This is not a 6-DOF free root. It is an unconstrained planar floating base in tx/tz/ry with structurally removed lateral, roll and yaw dynamics.",
            "The out-of-plane reaction audit (PT-06) is fail-closed: if the omitted DOFs materially support the trajectory, V1 fails.",
        ],
        refs=["JOINT_COORDINATE_ROM_AUTHORITY", "COLLISION_CONTACT_POLICY", "UPPER_BODY_HAT_BAR_INERTIAL_AUTHORITY", "LOAD_BAR_AUTHORITY"]),
    "event": dict(
        file="EVENT_MEASUREMENT_BOUNDARY", title="Event and Measurement Boundary",
        purpose="Frozen event-time semantics, primary COM authority, H2 anchoring and measurement-comparator boundaries.",
        preamble=[
            "Physical geometry/contact state is authoritative. Force thresholds are measurement comparators, never the truth source for takeoff or flight.",
            "TAKEOFF_OCCURRENCE and TAKEOFF_CONFIRMATION are separate; confirmation must never shift the H2 time origin.",
        ],
        refs=["PERFORMANCE_AUTHORITY_BOUNDARY", "COLLISION_CONTACT_POLICY", "PLANT_TOPOLOGY_AUTHORITY", "RES-82 EVENT_CONTRACT_E1_E12.json", "RES-82 DWELL_SEMANTICS.json"]),
    "performance": dict(
        file="PERFORMANCE_AUTHORITY_BOUNDARY", title="Performance Authority Boundary",
        purpose="Frozen performance boundary: anti-triviality floor only, withdrawn elite targets, and the mandatory method-matched mapping.",
        preamble=[
            "No current elite +20 kg direct-H2 target or band is frozen. RES-85/91 must produce a method-matched comparator/mapping analysis before any elite numeric hard gate is authorized.",
            "Controller development maximizes physically valid H2 subject to the frozen constraints instead of tuning to a fabricated height target.",
        ],
        refs=["EVENT_MEASUREMENT_BOUNDARY", "DEFERRED_NUMERICAL_CALIBRATIONS", "SPORT_CONTEXT_AUTHORITY"]),
    "deferred": dict(
        file="DEFERRED_NUMERICAL_CALIBRATIONS", title="Deferred Numerical Calibrations",
        purpose="Explicit isolation of every numerical/calibration decision that RES-95 must not freeze, with its owner and qualification domain.",
        preamble=[
            "Deferral is bounded: each deferred value has an owner, a frozen qualification domain and a required evidence form. No deferred value may silently become final candidate authority.",
        ],
        refs=["COLLISION_CONTACT_POLICY", "FOOT_MTP_MODEL_AUTHORITY", "PLANT_TOPOLOGY_AUTHORITY", "PERFORMANCE_AUTHORITY_BOUNDARY"]),
}

CLASSIFICATIONS = [
    "LITERATURE_DIRECT", "HUMAN_ANATOMY_REFERENCE", "LITERATURE_INFORMED_SYNTHETIC",
    "PHYSICS_IDENTITY", "ENGINEERING_NOMINAL_WITH_SENSITIVITY", "DEFERRED_TO_LATER_AUTHORITY",
]

def render_json(key, meta, decisions):
    payload = {
        "schema_version": "1.0.0",
        "artifact": meta["file"],
        "artifact_role": "res95_model_authority",
        "authority_id": AUTHORITY_ID,
        "mission": MISSION,
        "linear_issue": "RES-95",
        "sport_context_id": CONTEXT,
        "system_authority_id": INPUTS["system_authority_id"],
        "model_revision": INPUTS["model"]["MODEL_REVISION"],
        "model_id": INPUTS["model"]["MODEL_ID"],
        "status": "FROZEN_FOR_RES83_IMPLEMENTATION",
        "purpose": meta["purpose"],
        "machine_readable_inputs": "AUTHORITY_INPUTS.json",
        "derived_quantities": "DERIVED_QUANTITIES.json",
        "cross_references": meta["refs"],
        "classification_taxonomy": CLASSIFICATIONS,
        "decisions": decisions,
    }
    (HERE / f"{meta['file']}.json").write_text(json.dumps(payload, indent=2) + "\n")


def render_md(key, meta, decisions):
    lines = [f"# {meta['file']} — {meta['title']}", ""]
    lines += [
        f"**MISSION:** `{MISSION}`  ",
        f"**LINEAR:** `RES-95` (active unit; parent RES-83)  ",
        f"**AUTHORITY_ID:** `{AUTHORITY_ID}`  ",
        f"**SPORT_CONTEXT_ID:** `{CONTEXT}`  ",
        f"**MODEL:** `{INPUTS['model']['MODEL_REVISION']}` / `{INPUTS['model']['MODEL_ID']}`  ",
        "**STATUS:** FROZEN_FOR_RES83_IMPLEMENTATION  ",
        "**INPUTS:** `AUTHORITY_INPUTS.json` → `DERIVED_QUANTITIES.json` (deterministic; see `build_authority_numbers.py`)  ",
        "",
        f"## Purpose",
        "",
        meta["purpose"],
        "",
        "## Context",
        "",
    ]
    for p in meta["preamble"]:
        lines += [p, ""]
    lines += ["## Frozen decisions", "",
              "| ID | Decision | Value | Units | Classification | Sources |",
              "|---|---|---|---|---|---|"]
    for dec in decisions:
        val = dec["value"]
        if isinstance(val, (dict, list)):
            val = f"`{json.dumps(val, ensure_ascii=True)}`"
        else:
            val = str(val)
        if len(val) > 260:
            val = val[:257] + "..."
        stmt = dec["statement"].replace("|", "\\|")
        lines.append(f"| `{dec['id']}` | {stmt} | {val} | {dec['units']} | `{dec['classification']}` | {dec['sources']} |")
    lines += ["", "## Sensitivity and downstream obligations", ""]
    any_sens = False
    for dec in decisions:
        if dec["sensitivity"] not in ("—", ""):
            any_sens = True
            lines.append(f"- **{dec['id']}** — {dec['sensitivity']}")
    if not any_sens:
        lines.append("None beyond the generic V&V obligations.")
    notes = [d for d in decisions if d["notes"]]
    lines += ["", "## Notes and locators", ""]
    for dec in notes:
        lines.append(f"- **{dec['id']}** — {dec['notes']} (locator: {dec['locator']}; sources: {dec['sources']}).")
    lines += ["", "## Cross-references", ""]
    for r in meta["refs"]:
        lines.append(f"- `{r}`")
    lines += ["", "---", "",
              "This artifact is part of the RES-95 model authority bundle. It freezes specification only: it implements no Plant, controller or scorer code.", ""]
    (HERE / f"{meta['file']}.md").write_text("\n".join(lines))


def render_evidence_table():
    header = ["ROW_TYPE", "ROW_ID", "ARTIFACT", "DECISION_OR_CITATION", "VALUE", "UNITS", "CLASSIFICATION",
              "SOURCE_IDS", "LOCATOR", "SENSITIVITY_REQUIRED", "VERIFICATION_STATUS", "NOTES"]
    rows = []
    for s in SOURCES:
        rows.append(["SOURCE", s["id"], "SOURCE_REGISTRY", s["citation"], s["doi"], "—", "SOURCE",
                     "—", s["scope"], "—", s["verification"], s["notes"]])
    counts = {}
    for key, decs in DECISIONS.items():
        fname = ARTIFACTS[key]["file"]
        for dec in decs:
            val = dec["value"]
            if isinstance(val, (dict, list)):
                val = json.dumps(val, ensure_ascii=True)
            rows.append(["DECISION", dec["id"], fname, dec["statement"], str(val), dec["units"],
                         dec["classification"], dec["sources"], dec["locator"],
                         dec["sensitivity"], "RECOMPUTED_FROM_INPUTS", dec["notes"]])
            counts[dec["classification"]] = counts.get(dec["classification"], 0) + 1
    with (HERE / "MODEL_AUTHORITY_EVIDENCE_TABLE.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(rows)
    # markdown version
    lines = ["# MODEL_AUTHORITY_EVIDENCE_TABLE", "",
             f"Evidence table for `{AUTHORITY_ID}`. "
             f"{len(SOURCES)} sources and {sum(counts.values())} classified decisions.", "",
             "## Decision classification counts", ""]
    for c in CLASSIFICATIONS:
        lines.append(f"- `{c}`: {counts.get(c, 0)}")
    lines += ["", "## Sources", "", "| ID | Citation | DOI/Standard | Verification | Notes |", "|---|---|---|---|---|"]
    for s in SOURCES:
        cit = s["citation"]
        if len(cit) > 220:
            cit = cit[:217] + "..."
        lines.append(f"| `{s['id']}` | {cit.replace('|', '/')} | {s['doi']} | `{s['verification']}` | {s['notes'][:150].replace('|', '/')} |")
    lines += ["", "## Decisions", "", "| ID | Artifact | Decision | Value | Class | Sources | Sensitivity |", "|---|---|---|---|---|---|---|"]
    for key, decs in DECISIONS.items():
        fname = ARTIFACTS[key]["file"]
        for dec in decs:
            val = dec["value"]
            if isinstance(val, (dict, list)):
                val = json.dumps(val, ensure_ascii=True)
            val = str(val)
            if len(val) > 160:
                val = val[:157] + "..."
            lines.append(f"| `{dec['id']}` | `{fname}` | {dec['statement'].replace('|', '/')[:170]} | {val.replace('|', '/')} | `{dec['classification']}` | {dec['sources']} | {dec['sensitivity'].replace('|', '/')[:120]} |")
    lines += ["", "Full machine-readable table: `MODEL_AUTHORITY_EVIDENCE_TABLE.csv`.", ""]
    (HERE / "MODEL_AUTHORITY_EVIDENCE_TABLE.md").write_text("\n".join(lines))
    return counts


def main():
    assert set(DECISIONS) == set(ARTIFACTS), (set(DECISIONS) ^ set(ARTIFACTS))
    for key, meta in ARTIFACTS.items():
        decs = DECISIONS[key]
        for dec in decs:
            assert dec["classification"] in CLASSIFICATIONS, (dec["id"], dec["classification"])
        render_json(key, meta, decs)
        render_md(key, meta, decs)
    counts = render_evidence_table()
    print("rendered artifacts:", len(ARTIFACTS), "decision count:", sum(counts.values()))
    print(json.dumps(counts, indent=1))


if __name__ == "__main__":
    main()
